### ISSUE TITLE
VarDict realignment issue

### ISSUE THREAD

**Issue by OgnjenSB** [AstraZeneca-NGS/VarDictJava#101]
Hello!

There are certain issues with realignment that create false positives. I am unsure if they all originate from the same edge case, but sometimes realignment changes the local layout in what appear to be clear germline mutations. It happens almost always on 1/1 germline variants, and as a result, the VAF changes significantly, sometimes becoming 0/0 call and causing a somatic 1/1 false positive.

I prepared a small test BAM filtered +-100bp around the variant (available if you need it), and we tested it with versions 1.4.6 and 1.5.1 with and without realignment:

```
VarDict 1.5.1 NO realignment

10	25140411	.	G	C	206	PASS	STATUS=Germline;SAMPLE=TUMOR;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=2;SSF=0.48626;SOR=0.66016;LSEQ=CATCTTAGCAGACAGAGAAA;RSEQ=AGAAAAAAAAAAAGGAACAA	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	1/1:83:79:16,63:0,0:0,79:0.9518:0,2:25.2:1:32.8:1:1:0:60:4.267:0.9697:0:1.4	1/1:62:60:12,48:0,0:0,60:0.9677:0,2:23.4:1:31.6:1:1:0:60:3:1:0:1.6

VAF = 0.9518

VarDict 1.5.1 WITH realignment

10	25140411	.	G	C	184	PASS	STATUS=Germline;SAMPLE=TUMOR;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=2;SSF=0;SOR=0.06708;LSEQ=CATCTTAGCAGACAGAGAAA;RSEQ=AGAAAAAAAAAAAGGAACAA	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:88:43:5,38:0,0:0,43:0.4886:0,2:19.7:1:29.9:1:1:0:60:1.867:0.4058:0:1.6	1/1:62:58:12,46:0,0:0,58:0.9355:0,2:23.6:1:31.5:1:1:0:60:2.867:0.9556:0:1.6

VAF = 0.4886

VarDict 1.4.6 NO realignment

/

VarDict 1.4.6 WITH realignment

10	25140411	.	G	C	193	PASS	STATUS=Germline;SAMPLE=_1_EA661675_1.clipped.std_dedup.bam_realigned.recalibrated.filtered;TYPE=SNV;SHIFT3=0;MSI=2.000;MSILEN=2;SSF=0;SOR=12.54889;LSEQ=CATCTTAGCAGACAGAGAAA;RSEQ=AGAAAAAAAAAAAGGAACAA	GT:DP:VD:AD:RD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	1/0:108:55:17,38:0,0:0.5093:0,2:17.6:1:31:1:1:0:60:2.667:0.4494:0:1.5	1/1:71:66:20,46:0,0:0.9296:0,2:22.6:1:32:1:1:0:60:3.4:0.9444:0:1.6

VAF = 0.5093
```
The screenshot of the variant is temporarily hosted here:
https://ibb.co/iX2f9c

Please advise us if and how I should send the small BAM.

Thanks in advance!

**Comment by PolinaBevad** [comment]
@OgnjenSB, hello,
Sorry for such a late reply!
We have some changes in the realigner, but now they have not been released yet (but they are already in master branch).
Could you please send the part of BAM, the BED (or region) and the command line you used to email polina_bevad@epam.com so that I could test them on the new version?

**Comment by PolinaBevad** [comment]
@OgnjenSB, hello!
Sorry, we will close the issue because there was no answer from you about BAM file.
You can re-open it if needed. Also, there were few releases of VarDictJava since you created the issue, so maybe this error was gone. 
Thank you!
