### ISSUE TITLE
VarDictJava Depth issue in high-depth, high-indel area

### ISSUE THREAD

**Issue by bkohrn** [AstraZeneca-NGS/VarDictJava#103]
I'm working with a high-depth(~20,000+) high-indel short (~300bp) sequence area.  I was running VarDictJava with the following command:

`~/bioinformatics/programs/VarDictJava/build/install/VarDict/bin/VarDict -G ~/bioinformatics/reference/2018_02_ref/TrafficLight_sequence_2018_02.fasta -f 0 -N TL-DSB-171116-A1 -b TL-DSB-171116-A1.sscs.sort.rg.realign.bam -m 1000 -P 1000 -f 0 -K -V 0 -o 0 -q 0 -B 0 -r 0 -F 0 -3 -p -c 1 -S 2 -E 3 -g 4 ~/bioinformatics/reference/2018_02_ref/TrafficLight_sequence_2018_02.bed | ~/bioinformatics/programs/VarDictJava/VarDict/teststrandbias.R | ~/bioinformatics/programs/VarDictJava/VarDict/var2vcf_valid.pl -N TL-DSB-171116-A1 -E -f 0 > VarDictJavaTest2.vcf`

and I noticed that at a particular locus, depth was being reported as ~10,000 less than the depth observed using IGV.  After looking at the issues page on this github, I decided to try running it with the perl version using the following command:

`~/bioinformatics/programs/VarDict/vardict -G ~/bioinformatics/reference/2018_02_ref/TrafficLight_sequence_2018_02.fasta -f 0 -N TL-DSB-171116-A1 -b TL-DSB-171116-A1.sscs.sort.rg.realign.bam -m 1000 -P 1000 -f 0 -V 0 -o 0 -q 0 -B 0 -r 0 -F 0 -3 -p -c 1 -S 2 -E 3 -g 4 ~/bioinformatics/reference/2018_02_ref/TrafficLight_sequence_2018_02.bed | ~/bioinformatics/programs/VarDictJava/VarDict/teststrandbias.R | ~/bioinformatics/programs/VarDictJava/VarDict/var2vcf_valid.pl -N TL-DSB-171116-A1 -E -f 0 > VarDictTest2.vcf`

and noticed that the depth was much more similar to that reported by IGV.  

I've attached the output files from my two tests.  Just thought that you should know about this issue.

Sincerely, 
Brendan

Files:
VarDictJava: [VarDictJavaTest2.vcf.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/1932901/VarDictJavaTest2.vcf.txt)
VarDictPerl: [VarDictTest2.vcf.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/1932902/VarDictTest2.vcf.txt)

**Comment by mjafin** [comment]
Hi @bkohrn , the reason for this is that the Java version (which is ahead of Perl in development) of VarDict counts fragments rather than reads. For overlapping paired reads the true depth is reflected better by the Java version.

**Comment by bkohrn** [comment]
I don't think that's the problem.  The depth reported by the Perl vardict is much higher (~ 10000 higher), and matches the count in IGV better.   The reads are non-overlapping (they've been run through fgbio's ClipOverlappingReads method), so that shouldn't be an issue.
