### ISSUE TITLE
running time/question on -th parameter

### ISSUE THREAD

**Issue by koriege** [AstraZeneca-NGS/VarDictJava#104]
Hi,

I recognized a strange behavior, that independent of the presence of the '-th' parameter or an assignment of '-th 1' or '-th 100' I stick to 40 threads on 56 cores, 80 on 128 cores respectively. I want to call somatic variants from multiple paried mouse WGS experiments (each 2x20GB SAM) which takes very long ~12h each. Is this normal?

My commands
vardict -R chr1:1-195471971 -G $genome -f 0.01 -V 0.01 -N TUMOR -th 56 -q 20 -v -F 0x400 -b '$tumor|$normal' | testsomatic.R | var2vcf_paired.pl -q 20 -Q 0 -d 10 -v 3 -F 0.3 -f 0.01 -A -M -N 'TUMOR|NORMAL' > chr1.vcf
vardict -R chr2:1-182113224 -G $genome -f 0.01 -V 0.01 -N TUMOR -th 56 -q 20 -v -F 0x400 -b '$tumor|$normal' | testsomatic.R | var2vcf_paired.pl -q 20 -Q 0 -d 10 -v 3 -F 0.3 -f 0.01 -A -M -N 'TUMOR|NORMAL' > chr2.vcf
...

**Comment by PolinaBevad** [comment]
@koriege, hello!
Sorry for such a late reply.
Multithreading mode in VarDictJava works by splitting BED file between threads by lines. So each thread will run on one line. In this run, you specify the region option (`-R`), but not BED file, so my guess is that it is the reason: if the region is big, it will be processed a long time (VarDictJava is linear by memory) and sometimes maybe on only one core. 

Did you try to run VarDict with bed file that contains small parts of needed region? Does the behavior was the same? We have test case with 30Gb BAM, 35 Mb BED that processed on 8 threads in about 1h 20m.

**Comment by koriege** [comment]
Hey, I already found this solution in former issues and also the information, that overlapping BED regions - to not miss any variation - will be handled automatically. Anyways, thanks for your reply!
