### ISSUE TITLE
VarDict can't seem to detect AF at 0.01 or lower

### ISSUE THREAD

**Issue by gandalfone** [AstraZeneca-NGS/VarDictJava#105]
I have 3 artificial SNPs with AF exactly at 0.01, 0.02 and 0.05 in my duplex UMI-tagged paired reads.  After grouping by UMI and consensus building, VarDict was used for variant calling.   The minimum AF was set at 0.005.  But the SNP with AF at 0.01 never gets called.  The SNPs at 0.02 and 0.05 are called exactly as expected.  If I bump up the AF of the first SNP to slightly above 0.01 (e.g., 0.011), then it will be called exactly as expected.  So it seems VarDict can only make a call if the AF is above 0.01 even if I set the minimum AF to be below 0.01 (e.g., 0.005).  I attended an IDT webinar today and was told VarDict should be able to make a call when AF is below 0.01.  Here is my VarDict command:

min_af=0.005
VarDict -G $ref -f $min_af -N $sample -b $bam \
        -z -c 1 -S 2 -E 3 -g 4  $bed \
        | teststrandbias.R \
        | var2vcf_valid.pl -N $sample -E -f $min_af > $vcf

Could you please help me figure out what the problem could be?  Is the current version of VarDict able to make a variant call when AF is <= 0.01?  Thanks much.

**Comment by mjafin** [comment]
Hi @gandalfone, sorry about the problem you're seeing. There shouldn't be any hard AF threshold in VarDict. Are you using the Perl or Java version?

**Comment by gandalfone** [comment]
Hi @mjafin, Thanks for your reply.  I am using the Java version.  It does look strange, since if I just increase the AF of the same SNP to slightly above 0.01, it will be called fine.  I'll look more on my side, and also try the Perl version.

**Comment by mjafin** [comment]
If the Perl version sees the variant it could be down to this bug https://github.com/AstraZeneca-NGS/VarDictJava/issues/102 

What AF do other callers call the variant at?

**Comment by gandalfone** [comment]
@mjafin : The perl version worked fine for the same data set.  So it could be due to the issue specific to the Java version.  We have not had a chance to try the other callers yet.  Thanks much for the tip.

**Comment by PolinaBevad** [comment]
@gandalfone, hello!
Are you still facing with the bug? Mentioning issue #102 was resolved, therefore could you try version 1.5.4?
-f option with 0.001 definitely works, we have some variants with low frequency (0.0014 or so) in test cases. 

Filtering of variants bases not only on the frequency, so if the error still appears, could you please provide part of BAM and region where it happens to find the cause?

**Comment by gandalfone** [comment]
@PolinaBevad, @mjafin  :  We have tried some new data sets, and it seems the issue I reported has gone.  Sorry I did not get back to you sooner.  Thanks for your comments.  I will close the issue now.
