### ISSUE TITLE
(dinucleotide) variants not found VardictJava

### ISSUE THREAD

**Issue by kjass001** [AstraZeneca-NGS/VarDictJava#107]
Hi,
We tested our new pipeline with the VardictJava variant caller on ampliseq data. We used a publicly available fastq generated from HD734 (horizon dx; 1.3% tier) with the cancer hotspot v2 panel (Illumina). This control sample harbors multiple variants on the same/adjacent position (eg. KRAS G12V/D/A/C/R/S & BRAF V600E/G/K/M/R).
First, we get only few variants per genetic position (kras G12 two variants of six in sample G12D/R) . Second, it appears that on the BRAF V600 position (7 : 140'453'136) dinucleotide variants are not called (BRAF V600G/**K**/**R**. Third, variant frequencies in bam are significantly lower than in vcf.  I attach the .bam and the output file.
Did someone encounter similar issue? Any suggestions?

command:

AF_THR=0.005

./vardict -G hg19.fa -f $AF_THR -N "HD734-10ng-E02A-E01" -b HD734-10ng-E02A-E01.bam -z -c 1 -S 2 -E 3 -g 4 CancerHotSpot-v2.dna_manifest.20171207_noheaders.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N "HD734-10ng-E02A-E01" -E -f $AF_THR > HD734-10ng-E02A-E01_java.vcf

Thanks.

[HD734-10ng-E02A-E01_java_annotated.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/2017379/HD734-10ng-E02A-E01_java_annotated.zip)

**Comment by mjafin** [comment]
@polinabevad is your team able to look at this one too? I recall we fixed some issues in the past with MNPs but can't find the issue or fix.

**Comment by zhongwulai** [comment]
This is unique situation for synthetic samples, where multiple mutations can happen at the same position. 
 You need to add option "-A" in var2vcf_valid.pl script to generate the VCF file.  By default, only one genotype per genomic position is output to VCF.  -A option will output all high quality variants.

**Comment by mjafin** [comment]
Ah, I was looking for the `-A` option but in the wrong place (VarDict command itself). @kjass001 let us know if this doesn't help you an we'll reopen.

**Comment by kjass001** [comment]
Works perfect!
Thanks a lot

**Comment by zhongwulai** [comment]
@kjass001 Great!  Thanks for getting back!  Maybe we should think about have -A option as the default.
