### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 66S-3M38S

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDictJava#11]
This error occurs on HCC1143 data downloaded from CGHUB. 
The analysis_id or uuid is:
c727c60e-8ddd-1ddc-e040-ad451e414a77 for tumor
c727c60e-95b8-1455-e040-ad451e414a79 for normal

I stored the truncated BAM files that can reproduce the error in Google Drive:
https://drive.google.com/folderview?id=0B9pfRlnkG-Z7fngxOWtXV05FWG52SU5oMEUzcklMdmFtQVk3V3FDWm1ubk05TDJvX3F6N2s

VarDict -G genome.GRCh37.fa -f 0.01 -h -b 'tumor.error.bam|normal.error.bam'  -c 1 -S 2 -E 3 -g 4 error.bed > error.var 2> error.warning.msg

**Comment by jabbarish** [comment]
Thank you.  We will try to figure out what is causing it.
