### ISSUE TITLE
Add utility scripts (teststrandbias.R, var2vcf_valid.pl) to release distributions

### ISSUE THREAD

**Issue by TMiguelT** [AstraZeneca-NGS/VarDictJava#111]
I'm not sure what the release process is, but would it be possible to include the required binaries like:
* var2vcf_valid.pl
* var2vcf_paired.pl
* teststrandbias.R

to the `bin` directory for releases?

**Comment by pcingola** [comment]
We should add it to the Gradle script

**Comment by pcingola** [comment]
Done

**Comment by TMiguelT** [comment]
Great, thanks!
