### ISSUE TITLE
VarDictJava dies silently when bed file has (at least) 9 columns

### ISSUE THREAD

**Issue by mjafin** [AstraZeneca-NGS/VarDictJava#113]
As described, if a bed file has too many columns, no variants are called but there is also no error message

**Comment by PolinaBevad** [comment]
@mjafin , thanks for finding the issue!
In Perl amplicon mode is enabled only if bed consists of exactly 8 columns and columns №7 and №8 contains numbers (it is checked by regexp). Java has another implementation: if columns > 7, then it will suggest that mode is amplicon and try to read columns №7 and №8. If they aren't numbers, Java falls without errors while parsing these values.
We can fix it this way: if there are exactly 8 columns in bed and №7 and №8 columns are numbers, then we will set an amplicon mode. Else, if 7-8 columns aren't numbers (even if there are 8 or more columns in bed file), bed will be processed in simple mode. Does it suit you?

**Comment by mjafin** [comment]
Yes, brilliant, please implement.
