### ISSUE TITLE
Variant frequency options for monomer and non-monomer MSI

### ISSUE THREAD

**Issue by fournst** [AstraZeneca-NGS/VarDictJava#118]
Hello,

I'm currently working on a DNASeq pipeline project containing vardictJava, which is a very powerful tool.

I figured out that some complex variations (from our datasets) are not called by Vardict. Most of time, those variations are located near from repeated regions and some of them are well known to be causal (4 & 5 class), such as the MSH2:c.942+3A>T ([Liu & al., 1994](https://www.ncbi.nlm.nih.gov/pubmed/8062247) ; [Froggatt & al., 1999](https://www.ncbi.nlm.nih.gov/pubmed/10051005) ; [Desaï & al., 2000](https://www.ncbi.nlm.nih.gov/pubmed/10978353) ; and so on) 

By reading the user manual, I saw that vardict uses some filters based on variant frequency for repeated regions (chapter 5.4 - Variant filtering). This frequency seems to be a different parameter from the ones used in options `-f` and `-V`. 

Despite the fact that there are threshlods to filter the variants in/near the monomer and non-monomer MSI, there are no options to control thos ones. I had to change this frequency threshold manually into the code (0.275 --> 0.1) to call the complex variations cited above. 

So my request here is : is it possible to develop one or more options to control those frequency thresholds (filter number 10 in chapter 5.4 of the user manual) ? 

This is really critical for our activity and would be very helpful.

Thanks a lot for your help.

Best regards.

Steeve FOURNEAUX

**Comment by mjafin** [comment]
@zhongwulai care to comment?

**Comment by fournst** [comment]
Hello,

Can I have any news for this point ? 

Regards.

**Comment by PolinaBevad** [comment]
@fournst, hello!

We added options for defining threshold values for the monomer and non-monomer frequencies: `--mfreq` (monomer) and `--nmfreq` (non-monomer).
It is already merged in master, so you can build new version to use this.
