### ISSUE TITLE
Numeric error with var2vcf_valid.pl

### ISSUE THREAD

**Issue by fournst** [AstraZeneca-NGS/VarDictJava#127]
Hello,

I have an issue with values when var2vcf_valid.pl is running. Here are some exemples :
```
Argument "60,0" isn't numeric in numeric lt (<) at VarDictJava/VarDict/var2vcf_valid.pl line 140, <> line 645.
Argument "64,714" isn't numeric in numeric lt (<) at VarDictJava/VarDict/var2vcf_valid.pl line 141, <> line 645.
Argument "1,1" isn't numeric in numeric gt (>) at VarDictJava/VarDict/var2vcf_valid.pl line 143, <> line 645.
Argument "1,000" isn't numeric in numeric gt (>) at VarDictJava/VarDict/var2vcf_valid.pl line 144, <> line 645.
Argument "1,0000" isn't numeric in numeric lt (<) at VarDictJava/VarDict/var2vcf_valid.pl line 147, <> line 645.
Argument "0,0385" isn't numeric in numeric comparison (<=>) at VarDictJava/VarDict/var2vcf_valid.pl line 116, <> line 645.
Argument "0,0128" isn't numeric in numeric comparison (<=>) at VarDictJava/VarDict/var2vcf_valid.pl line 116, <> line 645.
Argument "0,0161" isn't numeric in numeric comparison (<=>) at VarDictJava/VarDict/var2vcf_valid.pl line 116, <> line 645.
```

I have thousands of error like those ones. 
Might the decimal argument (",") be the source of the problem ? Do you have an idea to fix this permanently ? 

Thanks for your help.

**Comment by chapmanb** [comment]
Thanks for the report. I agree with your diagnosis and it sounds like your locale is putting commas instead of decimal points in numbers from Java. We typically fix this by doing:
```
export LC_ALL=C
```
in our scripts running VarDict (and many other tools) to force back to decimal representations. Hope this resolves it for you.

**Comment by fournst** [comment]
Thanks for your quick answer.

This seems to be a good solution, I will put it into my scripts and will let you know if any troubles are persisting.

Thank you for your help.
Best regards.
