### ISSUE TITLE
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 8137, Read name 0801tcm7, MAPQ should be 0 for unmapped read.

### ISSUE THREAD

**Issue by mjafin** [AstraZeneca-NGS/VarDictJava#13]
Hi there,
I'm getting an error from samtools:
```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 8137, Read name 0801tcm7, MAPQ should be 0 for unmapped read.
```
It seems to be related to poor alignments by bwa (aln), see section here http://broadinstitute.github.io/picard/faq.html

Q: Why am I getting errors from Picard like "MAPQ should be 0 for unmapped read" or "CIGAR should have zero elements for unmapped read?"
...

I can't seem to be able to copy the answer, but in Picard it's possible to relax the validation of reads. I wonder if there's a flag in samtools-java to do the same?

**Comment by vkirst** [comment]
Hi Miika,

Htsjdk library reads and validates record from BAM(SAM) files alike Picard Tools. There are 3 ways of error message interpretation: STRICT(by default), LENIENT and SILENT. 
 
STRICT - stops the process by first error message
LENIENT - outputs all error messages to STDERR(does not stop the process)
SILENT - ignores all error messages.

We could  add a command-line option for that.   In this case,  we need to decide how invalid records are handled. Should we consider them as valid or just skip? 
 
If you could  give us BAM-file with such data, we can investigate how perl-vardict handles these cases to reproduce  the same behaviour in java-version.

**Comment by mjafin** [comment]
Good points, thanks. Maybe `LENIENT` would be nicer here. I have the data on our US system and we could probably hand it over to you but I will be out of office until Monday next week. Would it be a massive problem to implement the above optionality? I would imagine VarDict Perl to just ignore any warnings from samtools regarding poor alignments.
