### ISSUE TITLE
Coverage calcualtion

### ISSUE THREAD

**Issue by dattam** [AstraZeneca-NGS/VarDictJava#131]
Hi,

I am trying to use VarDict to call variants from RNASeq data. I got it to work with the default options (in the sense that I am able to see some results), but the reported coverage is very low compared to what we see on IGV. Upon some looking around, it appeared as if VarDict was reporting coverage based on de-duped data (even after specifying "-F 0"). I was wondering if it has something to do with the way the code (i.e. the data structures) were designed. Can you please help.

Thanks!

**Comment by PolinaBevad** [comment]
@dattam, thank you for reporting the issue!
Could you please provide a small part of the BAM file and BED file (or region) where this problem appears with the used command line? 
Also, please, try to run VarDictJava with `-t` option. It is the separate option to delete duplicate reads. Does the coverage decrease on your data with this option?

**Comment by PolinaBevad** [comment]
@dattam, hello!
We did not receive an answer from you, but we checked that on the latest version of VarDictJava (from master branch) duplicates are filtered by default and flag -F 0 works. The test case is in linked PR. Samtools shows that here in the tested region is exactly 1 duplicate read. The DP changed from 12 (with -F 0) to 11 (without flag). 
Can you try the latest version, and if the error still appears, send our data to reproduce it?

**Comment by PolinaBevad** [comment]
@dattam, thank your for answer! 
Good, I will close the issue, please, re-open it if needed.
