### ISSUE TITLE
VarDictJava 1.5.5 and 1.5.6: testsomatic.R (line X did not have 55 elements)

### ISSUE THREAD

**Issue by ahwanpandey** [AstraZeneca-NGS/VarDictJava#151]
Hello,

I have tested both 1.5.5 and 1.5.6 and in both cases I get the error in testsomatic.R. I have attached an example file with the issue which you can try with testsomatic.R

[TumorA.VD.21.VD.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/2462513/TumorA.VD.21.VD.gz)

An example problematic line is the one highlighted below, I have also pasted one line above and below it.

TumorA	21	21	11078275	11078276	TG	CA	2	0	2	0	0	0	T/T	0	0;0	47.5	1	20.0	1	60.0	1.000	1.0000	0	3.5	2	2	0	0	1	1	CAG/CA	1.0000	0;2	43.0	1	30.0	0	60.0	4.000	1.0000	0	4.0	0	1.000	1	AGGCCGACAAAGAGAGACTC	TCTCAAAAAAAAAAAAAAAA	21:10996701-11186054	StrongLOH	Complex	0	0	0	0

**> TumorA	21	21	11078280	11078285	CAAAAA	C	2	0	1	1	0	0	0	A/-6	2	2	0	0	1	1	-5/-5	1.0000	0;2	38.0	1	30.0	0	60.0	4.000	1.0000	0	5.0	11	16.000	1	GACAAAGAGAGACTCTGTCT	AAAAAAAAAAAGTGATTCCT	21:10996701-11186054	StrongLOH	Deletion	0	0	0	0**

TumorA	21	21	11078413	11078413	C	T	3	3	0	0	1	2	T/T	1.0000	0;2	32.3	1	30.0	0	59.0	6.000	1.0000	0	2.7	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	2	1.000	1	AGGAAGTCAAAATATCAACA	GAACAGGTGTTTGGAAGAAG	21:10996701-11186054	SampleSpecific	SNV	0	0	0	0

Looks like these issues happen with lines containing (StrongLOH). I loaded up another output file from VarDictJava into excel and selected for lines missing columns:

![image](https://user-images.githubusercontent.com/8450532/46704076-2774b500-cc75-11e8-930a-cea9b4183db9.png)

Looking forward to hearing your thoughts.

Thanks!

**Comment by ahwanpandey** [comment]
To make debugging easier, I have placed some test files and a run script in dropbox for you to debug

https://www.dropbox.com/sh/q52yksv04szvc6h/AADHOQpTMgSkDbfMJiljtTlia?dl=0

**Comment by Chitanda-Satou** [comment]
Hello, I met this issue too.

The error could occur in situation of WES of IDT panel (xGen® Exome Research Panel), aligned to uscs hg19 fasta.

The lines with less elements are like:
![image](https://user-images.githubusercontent.com/32410912/46709741-9f43df00-cc77-11e8-8cd3-5aa64e461577.png)

and 
![image](https://user-images.githubusercontent.com/32410912/46709753-ad91fb00-cc77-11e8-8e86-50ee70f271c8.png)

They are the same as @ahwanpandey 's errors.

**Comment by PolinaBevad** [comment]
@ahwanpandey, @Chitanda-Satou, thank you for reporting this!
We know about this problem (it appears in some cases for the variants of StrongLOH type). Here we have the PR #139 that must fix this situation. Now the output has the extra field for coverage of variants, it will be corrected, when the PR will be merged.

@ahwanpandey, can we use the test case that you posted here in our test case set? We add such cases to integration tests folder in the repository to check them in automated mode.

Thank you again, I will comment this issue when we merge the changes.

**Comment by ahwanpandey** [comment]
@PolinaBevad, sure, you can use the data I shared. Thanks for looking into this.

**Comment by PolinaBevad** [comment]
@ahwanpandey , @Chitanda-Satou , hello!
We created the new release 1.5.7 (https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.5.7), where this error with StrongLOH type has been fixed.
I will close this issue, but if you will still have the errors like this, feel free to reopen it.
Thank you!

**Comment by ahwanpandey** [comment]
I got another error relating to testsomatic.R in release 1.5.7

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 12460 did not have 55 elements

I have highlighted the problematic line

Sample1	3	3	3506761	3506761	T	G	36	36	0	0	34	2	G/G	1.0000	0;2	26.3	1	28.6	1	59.5	11.000	1.0000	0	4.4	12	12	0	0	12	0	G/G	1.0000	0;0	8.2	1	29.2	1	57.0	11.000	1.0000	0	1.5	1	4.000	1	GGGAAATGAAGGGAGGGGGA	GGGGCAGGTACCAGATGAGA	3:3498951-3998950	Germline	SNV	0	0	0	0
**Sample1	3	3	3506770	3506773	TACC	GAAG	16	14	0	0	14	0	-43061GAACC/GAAG	0.8750	0;1	42.3	1	30.0	0	60.0	28.000	0.4516	0	7.0		0	1.000	1	AGGGAGGGGGATGGGGCAGG	AGATGAGAGAGACATATAGA	3:3498951-3998950	StrongSomatic	Complex	0	18-0-0	0	10-0-0**
Sample1	3	3	3506776	3506777	AT	A	14	14	0	0	14	0	-1/-1	1.0000	0;1	38.3	1	30.0	0	60.0	28.000	1.0000	0	8.0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	5.000	2	GGGGATGGGGCAGGTACCAG	GAGAGAGACATATAGAGAGA	3:3498951-3998950	SampleSpecific	Deletion	0	0	0	0

**Comment by PolinaBevad** [comment]
@ahwanpandey, hello and sorry you still have a problems! 
Do you have a small part of bam with this error for our tests? 
There were small changes for StrongSomatic in this commit: https://github.com/AstraZeneca-NGS/VarDictJava/commit/1365a7a2db60896537fff3ac336f5cd86345db44 
I think the problem appears it the case, when we have no reference variant and variant from second sample, so the appender to the output must be filled with zeros. We will fix it.

**Comment by PolinaBevad** [comment]
@ahwanpandey, hello,
Okay, thank you, I will try to find this case on the public data. And I will also inform you when the fix will be ready.

**Comment by PolinaBevad** [comment]
@ahwanpandey, hello!
We updated output for StrongSomatic variants in VarDictJava 1.5.8. Could you please check it on the part of the data where it was causing the error? We still not found the publicly available test case for it, so it will be great if you can confirm that everything is in order.
Thank you a lot for finding this bug!

**Comment by ahwanpandey** [comment]
@polinabevad I just got back from vacation and I have no idea what sample the issue was in! I'm so sorry. I have had to stick with v1.5.7 for now since most of the samples in the cohort have already been processed by it. And the `awk 'NF>=48' | testsomatic.R` fix works just fine. I am not too concerned of not catching a particular variant because I am also running 3 other callers on this dataset.

A couple of questions I had I thought I'd ask here:

1) Do you think v1.5.8 and v1.5.7 will produce almost identical results? I.e. does v1.5.8 just have some minor bugfixes and not any major changes? If so, I might just switch to v1.5.8 mid-experiment. Just wanted to stray away from the confusion when we publish later and need details about what version of VarDict was used.

2) VarDict seems to be very sensitive. It finds way too many more passing variants than any other caller. Is this a common trend with VarDict? I haven't done a comprehensive analysis using a gold started dataset with TP calls but the sheer amount of variants that are exclusive to VD versus any other callers is quite striking, leading me to believe there might be a lot more FPs in the VarDict calls.  I have applied a couple of extra filters too based on some recommendations by @chapmanb here [https://github.com/AstraZeneca-NGS/VarDict/issues/68] as well as setting an SSF threshold of [<= 0.01]

The attached plot is an UpSet plot of all passing variants found in 48 WGS samples. As you can see the VD (VarDict) only set size is the largest by a huge margin.
[upset_plot.all_variants.pdf](https://github.com/AstraZeneca-NGS/VarDictJava/files/2606323/upset_plot.all_variants.pdf)

If I extracted just the variants that are predicted to have "HIGH|MODERATE|LOW" impact then the results seem more consistent across.
[upset_plot_HML_variants.pdf](https://github.com/AstraZeneca-NGS/VarDictJava/files/2606329/upset_plot_HML_variants.pdf)

I would also appreciate if you could point me to some publicly available gold standard datasets for benchmarking somatic variants. Right now I only have access to https://github.com/hbc/projects/tree/master/giab_somatic

Thanks for all your input!

**Comment by PolinaBevad** [comment]
@ahwanpandey, hello! 
We are no longer faced with the repetition of the original problem of the issue with missing elements, so I will close this issue.
If you have any questions on this topic, you can re-open it or create a new issue.
Thank you!
