### ISSUE TITLE
Filtering insertions in homopolymer regions

### ISSUE THREAD

**Issue by landesfeind** [AstraZeneca-NGS/VarDictJava#16]
Hi,

utilizing VarDictJava v1.3 for calling variants from RNA-seq of tumor cells gives me in an unreasonable amount of called insertions (> 5500 on the whole genome). I had a closer look on some of the suspicious inserts and they seem to be called at positions where a homopolymer of 6 or more equal nucleotides start. At these positions, most reads align perfectly with the reference sequence. However, a few have an additional nucleotide (e.g., AF=7%).

Currently, I am using quite straight forward filter settings (looking at DP, HICNT, etc). Do you have any experience on how to filter these variants for a high-quality prediction? Does VarDict somehow try to fix this during realignment or report some value which allows to filter this (except removing all insertions in homopolymer regions).

Thanks in advance
Manuel

**Comment by landesfeind** [comment]
PS: I had a closer look on some of the suspicious inserts. They seem to be called at positions where a repeat of 6 or more equal nucleotides start, see 
![visualization snapshort](https://cloud.githubusercontent.com/assets/1049501/8277546/363babc4-18c4-11e5-977e-2fa0df9660f5.png) 

At the provided example, all(!) reads align perfectly with the reference sequence. Nonetheless, VarDictJava calls an insertion:
```
chr1    24288070        .       G       GA      186.0   PASS    SAMPLE=...;TYPE=Insertion;DP=429;END=24288071;VD=32;AF=0.0746;BIAS=2:2;REFBIAS=169:228;VARBIAS=16:16;PMEAN=30.2;PSTD=1;QUAL=37.2;QSTD=1;SBF=0.46037;ODDRATIO=1.3481449525453;MQ=50;SN=64;HIAF=0.0766;ADJAF=0.0047;SHIFT3=6;MSI=7;MSILEN=1;NM=0.1;HICNT=32;HICOV=418;LSEQ=CAGATGAAGATTGTTCATAA;RSEQ=AAAAAAGAAAGAGGACATGG;INS;HET;VARTYPE=INS;    GT:DP:VD:AD:AF:RD:ALD   0/1:429:32:397,32:0.0746:169,228:16,16
```

**Comment by mjafin** [comment]
Hi @landesfeind,
Thanks for pointing out the issue. I'm certain Zhongwu will look into this ASAP but he is currently on holiday for a few weeks.

**Comment by landesfeind** [comment]
I filtered for insertions preceding homopolymer regions. But, I am still suspicious about a large number of insertions because ~70% are within a 4bp of an exon start or end. Is it possible to report if an insertion is called from reads which have a long stretch of N's after the insertion? This would probably be analogous to the PMEAN value and of great help for users of VarDict

**Comment by PolinaBevad** [comment]
@landesfeind, hello,
My guess is that we can close this issue because it was a long time ago and a lot of changes were from this moment in VarDictJava (includes last changes for Structural Variants). 
Please, reopen it, if it is still relevant to you, then we will know that we have to work on this.
