### ISSUE TITLE
Discrepancy between -q threshold and reported QMean value

### ISSUE THREAD

**Issue by landesfeind** [AstraZeneca-NGS/VarDictJava#17]
Hi,
VarDict v1.3 does not call an SNV for which there seems to be a pileup due to low base quality, which is fine in general. However, there is a discrepancy between the filtering (`-q 24` or `-q 25`) and the reported QMean value (27.3) which I believe to be the corresponding value in the output:

```
$ VarDict -q 25 -t -G $REF -b $BAM -R chr2:202508105-202508105
$ VarDict -q 24 -h -t -G $REF -b $BAM -R chr2:202508105-202508105
Sample  Gene    Chr     Start   End     Ref     Alt     Depth   AltDepth        RefFwdReads     RefRevReads     AltFwdReads     AltRevReads     Genotype        AF      Bias    PMean   PStd    QMean ...
data    chr2    chr2    202508105   202508105   C   A   62  12  25  25  6   6   C/A 0.1935  2;2 30.1    1   27.3    1   ...
```

I did not calculate the mean quality by my self but you can probably have a look at this nonetheless.

By the way, some cells are skipped in the header (using `-h`) but that's just cosmetics ;-)

Have a nice weekend!

**Comment by grozhnev** [comment]
@landesfeind 

If still relevant, the answer is that :
'-q' param is the phred score rate that is related to estimated probability of an error,
'Qmean' is the value that is related to the sum of mapping qualities (5th column in SAM) for variant.

So, as it is clear from the description of each parameter, this two values are not related and don't depend on each other.

The complete description of these two variables is provided by Zhongvu Lai in the issue [https://github.com/AstraZeneca-NGS/VarDict/issues/12](url)
