### ISSUE TITLE
Why likeySomatic status of variant with Normal AF higher than Tumor

### ISSUE THREAD

**Issue by HeXY0515** [AstraZeneca-NGS/VarDictJava#177]
Hi, 
I got confused about how is the variants status calculated?  I think it is a germline variant if its Tumor-AF less than Normal-AF like this: 

**chr8    128751846       .       C       CT      236     PASS    STATUS=LikelySomatic;SAMPLE=B1701;TYPE=Insertion;DP=4249;VD=82;AF=0.0193;SHIFT3=10;MSI=11.000;MSILEN=1;SSF=0;SOR=0.43;LSEQ=AAATCCTTGCCAAAGTTGGA;RSEQ=TTTTTTTTTTCTTTTATTCC    GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        0/1:4249:82:30,52:1317,2113:3430,82:0.0193:2,2:31.6:1:37.2:1:0.81849:1.08035:60.5:81:0.0248:0:0.2    0/1:1805:79:29,50:545,877:1422,79:0.0438:2,2:28.6:1:35.7:1:0.81292:1.0714:60.3:38.5:0.0554:0.0028:0.3**

But VarDictJava assigned a "LikelySomatic" status. Is it wrong or am I misunderstand? Could anyone explain this? 

Thanks~

**Comment by PolinaBevad** [comment]
@HeXY0515, hello!
We have some additional checks on frequency, so this variant must be determined as "Germline" if it's Normal-AF will be also more than limit that can be set by -V option. -V is the lowest frequency in a normal sample allowed for putative somatic mutations. It is 0.05 by default, so this variant was recognized as "Likely Somatic". 
 
Here you can read more about classification in the paired analysis: https://github.com/AstraZeneca-NGS/VarDict/wiki/Variant-classification-in-paired-analysis  

Please feel free to ask any questions.

**Comment by PolinaBevad** [comment]
@HeXY0515, hello!
I will close the issue, if you have additional questions, please re-open it.
Thank you!
