### ISSUE TITLE
Incorrect columns for variants at first position of a chromosome

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#18]
Victor and Zaal;
We ran into an edge case issue with variants at the first position of a chromosome. In these cases, VarDictJava produces a truncated output file with 33 columns instead of 34, resulting in failures from teststrandbias.R when filtering and converting to VCF. The perl VarDict complains with a number of errors but produces reasonable output and continues.

I put together a reproducible test case here that shows the problem:

https://s3.amazonaws.com/chapmanb/az/first-pos-variant-testcase.tar.gz

If you edit the `run.sh` script to point to a local copy of hg19 it should work for VarDict and fail on VarDictJava. Please let me know if I can provide any other information that would help.

**Comment by mjafin** [comment]
Brad did this get fixed?

**Comment by chapmanb** [comment]
Yes, thanks Miika. Thanks for the issue cleanup and apologies for not closing this earlier.
