### ISSUE TITLE
Extracting read identifiers for reads that fulfill certain search criteria

### ISSUE THREAD

**Issue by Krischan** [AstraZeneca-NGS/VarDictJava#180]
I am interested in a list of reads and their identifiers that fulfill certain criteria, after variant calling. Which class does contain this data?

**Comment by PolinaBevad** [comment]
@Krischan, hello!

We process each read from SAM/BAM file in the region sequentially with htsjdk library and don't keep them in any structure. This logic is located in SamFileParser class. 

If read doesn't fit us by criteria, for example, it is unmapped or it is secondary alignment, we simply skip the read:  https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/modules/SAMFileParser.java#L122
Then we process cigar of the record and create variants for different cases of insertion/deletion/softclip etc: https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/modules/SAMFileParser.java#L315

Soon there will be the refactoring, so the logic will be divided into separate classes, but the basic idea will be the same. You can look at the planned structure in this PR: https://github.com/AstraZeneca-NGS/VarDictJava/pull/179 , classes RecordPreprocessor and Cigar Parser may be of interest to you.

**Comment by PolinaBevad** [comment]
@Krischan, I will close the issue, but you can reopen it if there are any other questions on the topic.
