### ISSUE TITLE
Wrong variants/genotypes with nondeterministic results

### ISSUE THREAD

**Issue by namsyvo** [AstraZeneca-NGS/VarDictJava#181]
Hi,
I have run a test with VarDict paired calling mode in one sample several times, some of them were done successfully but some of them returned problematic results like the following (I guess VarDict results are non-deterministic), which failed Picard SortVcf due to unexpected variants:

* In one run, VarDict produced the following line:
chr22   xxx        .       C       C       243     PASS STATUS=StrongSomatic;SAMPLE=TUMOR;TYPE=SNV;DP=150;VD=125;AF=0.8333;SHIFT3=0;MSI=2.000;MSILEN=2;SSF=0;SOR=Inf;  GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        1/1:150:125:36,89:0,0:0,125:0.8333:0,2:28.5:1:34.9:1:1:0:52.1:61.5:0.8425:0:0.8 0/0:159:0:0,0:41,99:140,0:0:0:0:0:0:0:1:0:0:0:0:0:0

I did a manual review for the above cases and found out REF=C (125 count), ALT=T (38 count) for tumor, but the program printed out a homozygous reference with genotype GT:1/1 for tumor like the above.

* In another run, VarDict didn't produce the above line but the following line:
chr11   yyy       .       C       C       300     PASS    STATUS=StrongSomatic;SAMPLE=TUMOR;TYPE=SNV;DP=364;VD=361;AF=0.9918;SHIFT3=0;MSI=1.000;MSILEN=1;SSF=0;SOR=Inf; GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM 1/1:364:361:227,134:0,0:0,361:0.9918:0,2:29.2:1:35.4:1:1:0:57.6:21.562:1:0:0.5  0/0:362:0:0,0:211,151:362,0:0:2,0:27.9:1:34.4:1:1:0:57.6:13.48:1:0:0.5

I did a manual review for the above cases and found out REF=C (361 count), ALT=G (3 count) for tumor, but the program printed out a homozygous reference with genotype GT:1/1 for tumor like the above.

Do you have any idea why those cases happened? Do you have access to TCGA data? If yes I can show you which sample caused the above problems. If no I'll makeup data and send it to you to debug.

* Also I saw many variants like this:
chr11   zzz       .       C       T       38      v3      STATUS=StrongSomatic;SAMPLE=TUMOR;TYPE=SNV;DP=181;VD=2;AF=0.011;SHIFT3=0;MSI=5.000;MSILEN=1;SSF=0.2348;SOR=Inf

I did a manual review and saw that both REF and ALT bases have good quality (REF=C(179), ALT=T(2). What (statistical) method did you use to infer that variant with StrongSomatic status even if the DP is 181 and VD is just 2?

**Comment by PolinaBevad** [comment]
@namsyvo, hello!
Sorry that you have a problems with VarDict.

Are you using Java or Perl version of VarDict? We are currently working on some issues with non-deterministic behavior in the Perl version, but we did not find this in Java version. Also, please specify the version (1.5...) where the problem occurs. On 1.5.4 we had some cases when REF=ALT, but we didn't reproduce them in later versions.

It would be great if you could send me the data for reproducing this by email polina_bevad@epam.com. The command line to run VarDict with parameters will also be useful.

The logic of determining statuses in the paired analysis is described here: https://github.com/AstraZeneca-NGS/VarDict/wiki/Variant-classification-in-paired-analysis 

This is not a statistical method, so I will describe it a bit. If the position has coverage in both samples but the good variant is found only in the tumor sample, it will be recognized as StrongSomatic. 
The criteria for a variant to determined it as a "good" can be found here: https://github.com/AstraZeneca-NGS/VarDictJava#variant-filtering 
You can change the frequency of variants that you need by `-f` option and number of reads by `-r` option. In your case the variant meets criteria for -f 0.01 and -r 2 by default, so it was determined as good.

Thank you!

**Comment by namsyvo** [comment]
Hi,
I'm using VarDictJava version 1.5.8. I'll prepare the data for you. However it's TCGA data so I need to makeup them in some ways. Do you have permission to access TCGA data? If yes so it's great, I just send you the sample ID so you can reproduce it easily.

**Comment by PolinaBevad** [comment]
@namsyvo, I have an access to the open projects and cases in TCGA, but I'm not sure if I have an access to your sample. Send the ID, please, and I will check.

**Comment by PolinaBevad** [comment]
Nam, hello!

In the current master branch, we also added a fix to avoid REF==ALT variants in any case of somatic mode. It is not released, but you can update your version of VarDict. As I recall, you also confirmed by e-mail that non-deterministic behavior was not repeated in the latest versions that you used, so I will close the issue.

Many thanks for pointing out the problem!
