### ISSUE TITLE
ERROR:Argument "AAA" isn't numeric in numeric lt (<) at VarDict-1.5.5/bin/var2vcf_valid.pl line 133, <> line 1.

### ISSUE THREAD

**Issue by GorgonVZ** [AstraZeneca-NGS/VarDictJava#183]
Hi,
I get an errormessage when running following command (Vardict v1.5.5):

### COMMAND
VarDict-1.5.5/bin/VarDict -G hg19.fa -f 0.25 -b sorted.primerclipped.bam -R chrX:31165500-31165800:DMD -z -N sample_name | var2vcf_valid.pl

### ERROR MESSAGE
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT sample_name
Argument "AAAAAAGTAAAAAAGAAAAA" isn't numeric in numeric lt (<) at VarDict-1.5.5/bin/var2vcf_valid.pl line 133, <> line 1.

Obviously VarDict tries to interprete the nucleotide string as a numeric value. By having a look into the var2vcf_valid.pl script I regognize that within this string:

###STRING
my ($sample, $gene, $chrt, $start, $end, $ref, $alt, $dp, $vd, $rfwd, $rrev, $vfwd, $vrev, $genotype, $af, $bias, $pmean, $pstd, $qual, $qstd, $sbf, $oddratio, $mapq, $sn, $hiaf, $adjaf, $shift3, $msi, $msilen, $nm, **$hicnt,
 $hicov, $lseq, $rseq, $seg**, $type, $gamp, $tamp, $ncamp, $ampflag) = @{ $tmp[$i] };

variables **$hcint and $hicov** are at postitions 31-32 and variables $lseq and $rseq are at positions 33 and 34 of the array. 

###In contrast at the output of Vardict:
sample_name DMD chrX 31165667 31165671 AAAAG A 13878   11482 543 0 11482 0 -4/-4 0.8274 1;1 63.6   1   37.9 1 42.0   22964.000 0.9543 0.0044 7  9.000   1   -0.0      **11482    12032**    **AAAAAAGTAAAAAAGAAAAA    AAAGAAAAAGAAAAAGAAG**    chrX:31165501-31165800 Deletion 0 0
these are at positions 28-31. Could this explain the Errormessage I get?

Thanks for your Help and best regards,
Gorgon

**Comment by PolinaBevad** [comment]
@GorgonVZ, hello!
Sorry that you have the issue!

As I see in the command line, you didn't use `teststrandbias.R` script before `var2vcf_valid.pl`. This R script calculates and adds two fields in the middle of the output line (`$sbf` and `$oddratio`). 

Could you please try to run VarDict with R script and see if error disappear? You can find the example of the full command here: https://github.com/AstraZeneca-NGS/VarDictJava#single-sample-mode.

**Comment by GorgonVZ** [comment]
Stupid me...
Thanks that worked for me!

**Comment by PolinaBevad** [comment]
Great, now it is clear what the problem was. 
I do not think that there will be problems with this combination.
We use the strandbias info for one of the filters in the var2vcf_valid.pl (https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L153). So if the variant won't fit these criteria, it will be filtered out when you use `-S` option of var2vcf_valid.pl. If you don't use `-S`, there will be just additional information about strandbias for the variant.

**Comment by GorgonVZ** [comment]
Great thanks!
