### ISSUE TITLE
pSTD = 0 error

### ISSUE THREAD

**Issue by sluke123** [AstraZeneca-NGS/VarDictJava#185]
We have 2 duplicate samples and 2 variants were not called by vardict due to a pSTD=0 error.
SampleA had mut1 called correctly, mut2 called incorrectly, SampleB had mut1 called incorrectly, mut2 correctly. Checking our database we have 2% of variants called with pSTD = 0 which seems very high considering the comment below.

pSTD = 0 means all reads are supposed to derived from a single physical fragment, thus are filtered in the downstream.  The chance for a true variant to have pSTD = 0 should be really slim, though not impossible.

**Comment by PolinaBevad** [comment]
Sally, hello!
Could you send me the parts of these BAM files and positions of the variants that are called with pSTD=0 to my email: polina_bevad@epam.com?
I will check these samples for the reasons for such behavior. Perhaps this is a bug and pSTD does not increase correctly for the variant when it is found in at least 2 different reads. Another reason can be that there are other filters that variants can't pass.

**Comment by PolinaBevad** [comment]
Sally, hello,
I will close the issue because these samples must be run in amplicon mode, then pSTD will be correct. 
Thank you!
