### ISSUE TITLE
Invalid CIGAR string produced during local realignment

### ISSUE THREAD

**Issue by cbrueffer** [AstraZeneca-NGS/VarDictJava#192]
Hi,

I can reproducibly trigger the following CIGAR string problem in VarDict-Java 1.5.8:

```
vardict-java -G /genomes/Hsapiens/hg38/seq/hg38.fa -c 1 -S 2 -E 3 -g 4 -b test-cigar.bam --nosv -t -R chr9:107331700-107331701
Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 27M-3D0M21S
 at htsjdk.samtools.TextCigarCodec.decode(TextCigarCodec.java:69)
 at com.astrazeneca.vardict.modules.SAMFileParser.parseSAM(SAMFileParser.java:267)
 at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:69)
 at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:372)
 at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:317)
 at com.astrazeneca.vardict.VarDict.start(VarDict.java:61)
 at com.astrazeneca.vardict.Main.main(Main.java:35)
```

Disabling realignment using `-k 0`prevents the problem.

A minimal bam file showing the problem can be found at https://lu.box.com/s/hjzz7nk3jzhy6h7uk2dz47uq4gnkc18b

**Comment by PolinaBevad** [comment]
Christian, hello!
Thank you for finding this bug!

It occurs when there are three insertions in CIGAR, here the initial CIGAR was `15M1I1M1I2M1I27M`, but because of bug the total number of insertions was not considered correctly. We will fix this in both Java and Perl version of Vardict.

**Comment by cbrueffer** [comment]
Thanks for looking into this Polina! I have a few more examples that trigger this bug if that's interesting.

**Comment by PolinaBevad** [comment]
Yes, it would be great if you could share these examples, I’ll check if the fix will work for all of them.

**Comment by cbrueffer** [comment]
Here are two BAMs for a start:

https://lu.box.com/s/q0dqllmvjqpcho3tzggctr907xobmvuk
https://lu.box.com/s/r2ggmxpgvp0di0f1xc6dfwwas7ld93gv

If you can provide a fixed version as a jar file I'm happy to test it.

**Comment by PolinaBevad** [comment]
Great, I prepared jar with this fix: https://drive.google.com/open?id=1x4GWHw8iSOfersS_aEwCbC8iy1yEmoxG 
As I can see variants are now determined on these regions correctly.

**Comment by cbrueffer** [comment]
Thanks Polina; looks promising so far, however when converting to VCF using an up to date `var2vcf_valid.pl` script I get many errors of the following kind: 

```
Argument "CAGCTACTCAGGAGGCTGAG" isn't numeric in numeric lt (<) at /scratch/chris/rnaseq-varcall-snakemake/.snakemake/conda/3bf85289/bin/var2vcf_valid.pl line 139, <> line 1.
```

The original VarDict output for the above is as follows:

```
S006493.l.r.m.c.lib.g   chr9    chr9    551960  551960  T       G       3       3       0       0       1       2       G/G     1.0000  0;2     20.0    1       37.3    1       60.0    6.000   1.0000  0       0       2.000   1       0       3       3       CAGCTACTCAGGAGGCTGAG   TGGGAGGATCACTTGAGCTC    chr9:100-999999 SNV     0       0
```

**Comment by PolinaBevad** [comment]
Christian, did you add the step with `teststranbias.R` script before `var2vcf_valid.pl`? The error looks very similar to this problem. This R script makes Fisher test and adds two columns in the raw output, they are important for the further filtering.

**Comment by cbrueffer** [comment]
Good hunch, I had mixed the two up during a workflow restructuring. Your fix seems to work fine, thanks!

FYI, https://github.com/AstraZeneca-NGS/VarDictJava/issues/195 still happens with the new jar.

**Comment by PolinaBevad** [comment]
The fix is merged.
