### ISSUE TITLE
Error: Incorrect input detected in teststrandbias.R

### ISSUE THREAD

**Issue by BastienNguyen** [AstraZeneca-NGS/VarDictJava#196]
Hi

I am trying to run the following command:
`java -jar /home/nguyenb/my.prog/VarDictJava/build/libs/VarDict-1.6.0.jar -G ${ref_gene} -f ${AF_THR} -N ${tumor%.*} -th 12 -b "${out_path}/${tumor%.*}.FINAL.bam|${out_path}/${normal%.*}.FINAL.bam" -R ${REGION} | /home/nguyenb/my.prog/VarDictJava/VarDict/teststrandbias.R | /home/nguyenb/my.prog/VarDictJava/VarDict/var2vcf_valid.pl -E -f 0.001 > vars2.vcf`

And the error is:
`Error: Incorrect input detected in teststrandbias.R
Execution halted`

I also tried in two steps like this:
`java -jar /home/nguyenb/my.prog/VarDictJava/build/libs/VarDict-1.6.0.jar -G ${ref_gene} -f ${AF_THR} -N ${tumor%.*} -th 12 -b "${out_path}/${tumor%.*}.FINAL.bam|${out_path}/${normal%.*}.FINAL.bam" -R ${REGION} > VarDict.vcf
cat VarDict.vcf | /home/nguyenb/my.prog/VarDictJava/VarDict/teststrandbias.R`

But get the same error.

Here is attached the first VarDict.vcf file.
[VarDict.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/2916919/VarDict.txt)

Thanks for your help!

Bastien

**Comment by PolinaBevad** [comment]
Bastien, hello,
For the somatic (paired) mode with tumor and normal samples, you need to use the `testsomatic.R` and` var2vcf_paired.pl` scripts.
You can see an example of such a command here: https://github.com/AstraZeneca-NGS/VarDictJava#paired-variant-calling
Please try using these scripts and let me know if something goes wrong.

**Comment by PolinaBevad** [comment]
Bastien, I will close this issue because the solution was proposed, but if you have any other questions on this topic, please, re-open the issue. 
Thank you.
