### ISSUE TITLE
VarDictJava misses a somatic SNV that is adjacent, downstream, and in phase with SNP

### ISSUE THREAD

**Issue by tinyheero** [AstraZeneca-NGS/VarDictJava#198]
The latest version of VarDictJava (v1.5.8) misses a somatic SNV that is adjacent, downstream, and in phase with SNP. For instance, chr5:665281 has a somatic SNV which is directly adjacent, downstream, and in phase with an SNP.

![chr5_665281](https://user-images.githubusercontent.com/3268173/54048317-5f0a6d80-41d1-11e9-8be6-492a43e9e629.png)

Instead of classifying the position as a somatic SNV, it predicts the upstream SNP position (chr5:665280) as germline and then does not classify the downstream somatic mutation. The truth should be chr5:665280 is classified as a germline, while chr5:665281 is classified as a somatic SNV.

I've put the data for reproducibility at https://drive.google.com/drive/folders/1qL2qxoGSgBz8nzuoro8wTjF0JweVIExW. The files are as follows:

* Tumour BAM and BAI: `tumour_chr5_665281.{bam,bai}`
* Normal BAM and BAI: `normal_chr5_665281.{bam,bai}`

I installed VarDictJava using conda (`conda install vardict-java=1.5.8`), and ran the following:

```bash
vardict-java \
        -b "tumour_chr5_665281.bam|normal_chr5_665281.bam" \
        -f 0.01 \
        -G ucsc.hg19-GATKBundle.fa \
        -N tumour \
        -c 1 -S 2 -E 3 \
        -m 50 \
        -th 1 \
        -R "chr5:664000-666000" \
    2> chr5_665281.stderr \
    > chr5_665281.vardictjava.var

testsomatic.R \
    < chr5_665281.vardictjava.var \
    > chr5_665281.vardictjava.testsomatic.var

cat chr5_665281.vardictjava.testsomatic.var \
    | var2vcf_paired.pl \
        -N "tumour|normal" \
        -f 0.01 \
    > chr5_665281.vardictjava.testsomatic.vcf
```

In the raw VarDictJava results, the somatic SNV gets grouped together with the upstream to form a somatic complex variant. The SNP is also reported as germline:

```
> grep "665280\|665281" chr5_665281.vardictjava.var
tumour  chr5    chr5    665280  665281  TG      CA      389     187     0       0       89      98      CAG/CA  0.4807  0;2     38.8    1       36.5    1       60.0    186.000 0.4987  0.0283  3.7     127     0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       1.000   1       TTGTAGCCGGACACATAGCC    ACTCGTCCACCAGATCCACG    chr5:664000-666000      StrongSomatic   Complex 0       0       0       0
tumour  chr5    chr5    665280  665280  T       C       389     190     0       0       89      101     CAG/C   0.4884  0;2     40.4    1       35.7    1       60.0    26.143  0.4906  0       2.5     127     123     0       0       59      64      C/C     0.9685  0;2    37.5     1       36.6    1       60.0    122.000 0.9760  0       2.3     0       1.000   1       TTGTAGCCGGACACATAGCC    GACTCGTCCACCAGATCCAC    chr5:664000-666000      Germline        SNV     0       0       0       0
```

However, following `testsomatic.R` and then conversion to VCF (via the `var2vcf_paired.pl` script), the only position that gets reported is the germline SNP. The somatic mutation is missing from the final VCF output.

```
$> grep "665280\|665281" chr5_665281.vardictjava.testsomatic.vcf
chr5    665280  .       T       C       270     PASS    STATUS=Germline;SAMPLE=tumour;TYPE=SNV;DP=389;VD=190;AF=0.4884;SHIFT3=0;MSI=1.000;MSILEN=1;SSF=0;SOR=0.0312;LSEQ=TTGTAGCCGGACACATAGCC;RSEQ=GACTCGTCCACCAGATCCAC GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        0/1:389:190:89,101:0,0:0,190:0.4884:0,2:40.4:1:35.7:1:1:0:60:26.143:0.4906:0:2.5        1/1:127:123:59,64:0,0:0,123:0.9685:0,2:37.5:1:36.6:1:1:0:60:122:0.976:0:2.3
```

**Comment by PolinaBevad** [comment]
Fong Chun Chan, hello,

This complex somatic mutation is filtered because its AF is smaller than AF of germline SNV and they are both on the one position. 

You can fix this by running `var2vcf_paired.pl` with `-A` option, like this:
`chr5_665281.vardictjava.var | testsomatic.R | var2vcf_paired.pl -A > chr5_665281.vardictjava.testsomatic.vcf`
This option will output all variants on the position, not just the one that has the highest AF.

Could you please try this and let me know if this is not the result you wanted?

**Comment by tinyheero** [comment]
Hi Polina,

Thanks for the tip on the `-A` flag. I see the following results now with this flag added:

```bash
cat chr5_665281.vardictjava.testsomatic.var \
    | var2vcf_paired.pl \
        -N "tumour|normal" \
        -f 0.01 \
        -A \
    > chr5_665281.vardictjava.testsomatic.vcf
grep "665280" chr5_665281.vardictjava.testsomatic.vcf
```
```
chr5    665280  .       T       C       270     PASS    STATUS=Germline;SAMPLE=tumour;TYPE=SNV;DP=389;VD=190;AF=0.4884;SHIFT3=0;MSI=1.000;MSILEN=1;SSF=0;SOR=0.0312;LSEQ=TTGTAGCCGGACACATAGCC;RSEQ=GACTCGTCCACCAGATCCAC GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        0/1:389:190:89,101:0,0:0,190:0.4884:0,2:40.4:1:35.7:1:1:0:60:26.143:0.4906:0:2.5        1/1:127:123:59,64:0,0:0,123:0.9685:0,2:37.5:1:36.6:1:1:0:60:122:0.976:0:2.3
chr5    665280  .       TG      CA      275     PASS    STATUS=StrongSomatic;SAMPLE=tumour;TYPE=Complex;DP=389;VD=187;AF=0.4807;SHIFT3=0;MSI=1.000;MSILEN=1;SSF=0;SOR=Inf;LSEQ=TTGTAGCCGGACACATAGCC;RSEQ=ACTCGTCCACCAGATCCACG   GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM        0/1:389:187:89,98:0,0:0,187:0.4807:0,2:38.8:1:36.5:1:1:0:60:186:0.4987:0.0283:3.7       0/0:127:0:0,0:0,0:0,0:0:0:0:0:0:0:1:0:0:0:0:0:0
```

This is super helpful, but I believe this is a misclassification of the variant. The dataset was simulated and designed to construct a scenario with a somatic SNV adjacent to a germline SNP. So I was hoping the result from VarDictJava would be a somatic SNV at chr5:665281 and a germline SNP at chr5:665280. I recognize that VarDictJava attempts to phase the variants and group multiple variants together to return a complex variant. 

However, the classification of chr5:665280 as a "StrongSomatic" complex variant is misleading because it includes the SNP in the allele call. Is there any way to get VarDIctJava to return the variants as a somatic SNV at chr5:665281 and a germline SNP at chr5:665280?

Many thanks for your help in advance.

**Comment by PolinaBevad** [comment]
Fong Chun Chan, hello,

the determining of MNVs is the core of VarDict and it can't be simply turned off, but there is one trick that can be used. 

To gather SNVs in MNV we suppose that the quality of each base in the read that supports the variant will be more than the typical threshold for SNV by 5 units. This threshold can be set with `-q` option of VarDict (default is 22.5), and in your case, it is enough  to set `-q 33` to "separate" the variants. Of course, this will influence on other variants (some of them will be skipped due to lack of quality and also counts of coverage will change), but if you run this only on small region only for these variants, I think it is a way to solve the problem. 

The question of classification for such variants as somatic SNVs may take some time, because we have to analyze whether it should be changed by default or not.

**Comment by tinyheero** [comment]
Thanks Polina for the `-q` tip. I think the issue will be that genuine MNVs that I have spiked in will be lost using this approach.

If you could keep me updated on the question of classification, that would be super useful. Many thank in advance.

**Comment by tinyheero** [comment]
One thought I had was maybe classifying these mutations as a different category (e.g. GermlineSomatic). As it currently stands, these adjacent SNP/SNV mutations get called as somatic MNVs and this causes an inflation in the number of these mutations as I believe these are not somatic MNVs. Having them as a separate class would give the user an ability to easily distinguish them from real MNVs, and then decide how to process them downstream (e.g. splitting them apart or keeping them as one event for phasing).

**Comment by PolinaBevad** [comment]
Fong Chun Chan, hello, 

I sent a question about the classification of this variant Zhongwu Lai (he is the creator of VarDict and he makes the final decisions on scientific questions). He believes that this variant should be classified as somatic MNV, and not any other, so we will not change the classification.
I think you can add some additional classification for such variants in downstream, like when Germline and Complex Somatic start at one position then you can reclassify the second variant.

**Comment by tinyheero** [comment]
Thanks Polina for updating me. That's most unfortunate. I respectfully disagree with classifying any variants that contain a germline event in it as being somatic, but accept your decision on the issue. Many thanks for following up on this.
