### ISSUE TITLE
Option -K is not working?

### ISSUE THREAD

**Issue by FrankFeng** [AstraZeneca-NGS/VarDictJava#203]
Hi,

I am using VarDictJava for calling variants on RNAseq data. It is very common that "N" is in the CIGAR string in RNAseq alignment records (e.g. **112M640N38M** ). I tried it with and without option -K (**"Include Ns in the total depth calculation"**) to call variants, but there was no difference in the DP values at all called variants. With option -K, what I expected is that the DP value would be increased and the AF value is decreased. Is that option not working or did I do something wrong?  

VarDictJava version is 1.5.8, with the command below:

```
VarDict -K -th 4 -G $ref -f $AF_THR -N $sm --nosv -c 1 -S 2 -E 3 -F 0x700 \
    -r 4 -b $bam $bed \
    | teststrandbias.R | var2vcf_valid.pl -A -N $sm -E -f $AF_THR > out.vcf

```
Regards,
Frank

**Comment by PolinaBevad** [comment]
Hi, Frank,
The option -K is made to include depths not from CIGAR N (so these bases are "not matched" or "skipped"), but for N bases in segment sequences (like ACGNNNCGT), that are located in the M ("matched") part of CIGAR. 
Not matched regions of CIGAR are skipped by VarDict.

**Comment by FrankFeng** [comment]
Thank you very much, Polina!
