### ISSUE TITLE
MQ calculated wrong for insertions?

### ISSUE THREAD

**Issue by FrankFeng** [AstraZeneca-NGS/VarDictJava#204]
Hi,

Looking at the variant calls, I see many insertions with MQ (Mean Mapping Quality) greater than the maximum value that the aligner can assign to an alignment. For example, the max mapping quality with BWA-MEM is 60, but I see many of insertions with MQ greater than 60. Is that a bug or not? 

I am using VarDictJava version 1.5.8. As an example, three insertions with MQ>60 are shown below. Thanks.

```text
1       28218773        .       G       GA      133     PASS    SAMPLE=varDict_HHAEM11812_Dx;TYPE=Insertion;DP=473;VD=14;AF=0.0296;BIAS=2:2;REFBIAS=151:230;VARBIAS=8:6;PMEAN=47.2;PSTD=1;QUAL=35;QSTD=1;SBF=0.26667;ODDRATIO=2.02716;MQ=63.6;SN=28;HIAF=0.0551;ADJAF=0.0021;SHIFT3=10;MSI=11;MSILEN=1;NM=0.8;HICNT=14;HICOV=254;LSEQ=GCTTGCCTAGAAAGAAAGAA;RSEQ=AAAAAAAAAAGGTCATTTTC;DUPRATE=0;SPLITREAD=0;SPANPAIR=0   GT:DP:VD:AD:AF:RD:ALD   0/1:473:14:381,14:0.0296:151,230:8,6
1       28233572        .       G       GA      157     MSI12;LongMSI   SAMPLE=varDict_HHAEM11812_Dx;TYPE=Insertion;DP=605;VD=30;AF=0.0496;BIAS=2:2;REFBIAS=264:125;VARBIAS=26:3;PMEAN=42.6;PSTD=1;QUAL=32;QSTD=1;SBF=0.01207;ODDRATIO=4.09333;MQ=60.1;SN=13.5;HIAF=0.0871;ADJAF=0;SHIFT3=12;MSI=13;MSILEN=1;NM=1.9;HICNT=27;HICOV=310;LSEQ=CCTAGGTTAGAAGAAACAAA;RSEQ=AAAAAAAAAAAAGGTCTGGT;DUPRATE=0;SPLITREAD=0;SPANPAIR=0     GT:DP:VD:AD:AF:RD:ALD   0/1:605:30:389,30:0.0496:264,125:26,3
4       57356470        .       C       CT      116     PASS    SAMPLE=varDict_HHAEM11812_Dx;TYPE=Insertion;DP=523;VD=9;AF=0.0172;BIAS=2:2;REFBIAS=313:172;VARBIAS=7:2;PMEAN=49.6;PSTD=1;QUAL=36.9;QSTD=0;SBF=0.50361;ODDRATIO=1.92105;MQ=63.2;SN=18;HIAF=0.0199;ADJAF=0;SHIFT3=9;MSI=10;MSILEN=1;NM=0.5;HICNT=9;HICOV=452;LSEQ=GCTAGATATTTAACTTGAAA;RSEQ=TTTTTTTTTCTTTTTATTGA;DUPRATE=0;SPLITREAD=0;SPANPAIR=0 GT:DP:VD:AD:AF:RD:ALD   0/1:523:9:485,9:0.0172:313,172:7,2
```

Regards,

Frank

**Comment by PolinaBevad** [comment]
Frank, hello!

Perhaps this is a bug. Can you provide a part of the BAM file that contains any of these insertions so that we can verify this?
You can send it by email polina_bevad@epam.com if you don't want to share the files here.

**Comment by FrankFeng** [comment]
Hi Polina,

I have emailed you the BAM for test. The BAM was mapped to human ref genome b37, which can be downloaded at ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz

I used VarDictJava 1.5.8, with the command below on the testing BAM, and I saw some of the insertion calls with MQ > 60:

```bash
VarDict -G $b37 -f 0.01 -N my_sample --nosv -c 1 -S 2 -E 3 -F 0x700 \
    -r 4 -R 1:28216773-28234572 -b $bam  \
    | teststrandbias.R | var2vcf_valid.pl -A -N my_sample -E -f 0.01 > test_out.vcf
```

Regards,

Frank

**Comment by PolinaBevad** [comment]
Hello Frank,
I received your BAM files and found the place where this problem occurs (it appears when adjusting the counts for insertions in the case of softclips). We need a little time to decide how best to fix this.

**Comment by PolinaBevad** [comment]
Hello Frank,

The changes for MAPQ field in the case of insertions were merged and now are in the master branch. Now MAPQ will not become more than limit while adjusting insertions values. You can build the new version of VarDictJava to use it right now or you can wait for the release version. 

Thank you for finding this!
I will close the issue but feel free to re-open it if you will have additional questions.
