### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#207]
Hi, I've finally got VarDictJava to run without error, but now it's running but no output is being made at all, the output file stays empty. I'm triple checked the command, and everything looks fine:

VarDictJava/bin/VarDict -U -N NA12877 -c 1 -S 2 -E 3 -g 4 -O 10 -f 0.01 -b NA12877.cram -G Homo_sapiens_assembly38.fasta -th 8 hg38-gatk.1mb.windows > NA12877.out

Not sure what's wrong...

**Comment by gevro** [comment]
I've tried smaller BAM, CRAM files, other BED intervals, not multi-threaded -- all are not producing output files. 

Stderr output looks fine:
INFO	2019-03-28 15:36:02	Defaults	Found file for property samjdk.reference_fasta: Homo_sapiens_assembly38.fasta 
INFO	2019-03-28 15:36:02	ReferenceSource	Default reference file /gpfs/home/evrong01Homo_sapiens_assembly38.fasta exists, so going to use that.
...
...

Must be some bug in VarDictJava, because I can't think of anything else that is wrong.

**Comment by PolinaBevad** [comment]
@gevro, hello!
Sorry that you have the issue. Your command line looks fine, but I don't like this INFO messages, maybe there were some changes in Htsjdk library, that provide such behavior now.
I can check what's wrong if you send me the small BAM or CRAM you tried to use and this BED file (or part of it). My email is polina_bevad@epam.com

You can also run VarDictJava with -y option (it will output some helpful debug info).

**Comment by PolinaBevad** [comment]
Gilad, hello!
If I understand correctly, the problem was solved and now everything works as it should.
Just to keep it for history: this was fixed by skipping the bad mapping reads (there were a lot of them with MQ < 10) to shorten the time of processing.
I will close the issue, but you can re-open it or create a new one if other questions appear.
Thank you!
