### ISSUE TITLE
Is it possible add a LICENSE file to this repository.

### ISSUE THREAD

**Issue by illusional** [AstraZeneca-NGS/VarDictJava#208]
Hey, just wondering if it's possible to add a LICENSE file to this repository. Both this and the original repository are Licensed under the MIT license per the [README.md](https://github.com/AstraZeneca-NGS/VarDictJava#license), but there's not one in the code base.

My thoughts are it makes the license clearer, and I believe some programs might index repositories based on this license.

**Comment by PolinaBevad** [comment]
Michael, hello!
Thanks for pointing this out! PR with MIT license file created: #215

**Comment by PolinaBevad** [comment]
Thank you again, Michael, the license was added so I will close the issue.
