### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#209]
Hi,
I followed the instructions to clone the repo and then build by when I run the gradlew script I get the following message

-bash-4.2$ ./gradlew --gradle-user-home=/home/rcf-proj2/st5/tkitapci clean installDist
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

BUILD SUCCESSFUL in 1m 11s
5 actionable tasks: 5 executed

It seems to be successful but when I look at the build folder I am seeing the following folders

classes  distributions  libs  scripts  tmp

in the instructions it says I should have build/install/VarDict/bin and build/install/VarDict/lib

I don't have these folders. I do have a jar file inside the distributions/ folder but if I try to run it I get 

(base) -bash-4.2$ java -jar VarDict-1.6.0.tar
Error: Invalid or corrupt jarfile VarDict-1.6.0.tar
 
Can you please help me with this installation step ?

Thanks
Best Regards
T. Hamdi Kitapci

**Comment by thkitapci** [comment]
Hi,
I actually found the bin/ and /lib now it was under the folder

VarDictJava/dist/

which has many versions

I unzipped all of them new versions 1.5.5 and 1.4.8 (giving the following errors)

If I run the 1.4.7 then I get the expected help page.

Is there a problem with the way I did the build or is there a problem with the newest versions ?

(base) -bash-4.2$ $HOME/VarDictJava/dist/VarDict-1.5.5/bin/VarDict
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

(base) -bash-4.2$ $HOME/VarDictJava/dist/VarDict-1.4.8/bin/VarDict
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by PolinaBevad** [comment]
@thkitapci, hello!
I cloned VarDictJava repository right now and after `./gradlew installDist` the build\install folder was created. The unzipped distribution for 1.5.5 also run successfully and displayed help for VarDict with the command you used.
What are your OS and Java versions? VarDict works for Java >=8.0.

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
(base) -bash-4.2$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
(base) -bash-4.2$ uname -r
3.10.0-862.14.4.el7.x86_64

(base) -bash-4.2$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Let me know if I can provide any other information.

After ./gradlew installDist I don't have a build/install folder under the build/ I have the following

(base) -bash-4.2$ ls VarDictJava/build
classes  distributions  libs  scripts  tmp

**Comment by PolinaBevad** [comment]
Here the error "Unsupported major.minor version 52.0" means that you have the version mismatch (i.e. you have java version less then program was compiled). 45 version is quite old, can you please install one of the last JDKs 1.8 versions? Then please try to rerun `./gradlew installDist` command. I guess you have no build folder because gradle 4.2. also doesn't fully support 45 version of JDK.

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I think I figured out the problem build/install folder gets removed when I run the second command

I started from scratch and cloned the repo again. When I run the 
./gradlew installDist 

it looks fine and I have the build/install directory with the bin/ and /lib inside

Then if I run the javadoc command as following I get a bunch or warnings 
-bash-4.2$ ./gradlew clean javadoc

> Task :javadoc
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/data/scopedata/Scope.java:12: warning: no description for @param
 * @param <T>
   ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for duprate
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for position
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for totalPosCoverage
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for var
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for debugLines
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @param for hicov
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:287: warning: no @return
    int createInsertion(double duprate, int position, int totalPosCoverage,
        ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for duprate
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for alignedVars
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for position
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for nonInsertionVariations
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for tcov
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for var
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for debugLines
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for keys
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/modules/ToVarsBuilder.java:371: warning: no @param for hicov
    void createVariant(double duprate, Map<Integer, Vars> alignedVars, int position, VariationMap<String, Variation> nonInsertionVariations,
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/postprocessmodules/SomaticPostProcessModule.java:101: warning: no @param for region
    void callingForOneSample(Vars variants, boolean isFirstCover, String varLabel, Region region, Set<String> splice) {
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/postprocessmodules/SomaticPostProcessModule.java:101: warning: no @param for splice
    void callingForOneSample(Vars variants, boolean isFirstCover, String varLabel, Region region, Set<String> splice) {
         ^
/auto/rcf-proj/st5/tkitapci/software/VarDictJava/src/main/java/com/astrazeneca/vardict/postprocessmodules/SomaticPostProcessModule.java:315: warning: no @param for splice
     String determinateType(Vars variants, Variant standardVariant, Variant variantToCompare, Set<String> splice) {
            ^
20 warnings


and then build/install gets removed and there are only 

-bash-4.2$ ls VarDictJava/build
classes  docs  tmp

Do you have the same problem with javadoc ?

**Comment by PolinaBevad** [comment]
@thkitapci, please, run javadoc without clean command. 
So run first `./gradlew clean installDist` and then simple `./gradlew javadoc` 
Clean will "clear" build directory to remove all old files. I think I will add this clarification in documentation.
I guess after build Vardict still will not run on 45 version, so if the similar error "Unsupported major.minor version 52.0" appears, try it with newer JDK, please.

**Comment by thkitapci** [comment]
@PolinaBevad 
Thanks for your help. I did 

./gradlew javadoc (without clean) I still get the same warning as posted above (not sure if that will cause any problem downstream) but now I have the install folder still in the build/ 

When I run VarDictJava/build/install/VarDict/bin/VarDict I get the help message as expected. 

I have the JDK 1.8.0_45 so I should be fine 

(base) -bash-4.2$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

I think the "clean" from the javadoc as it is now in the instructions should be removed. 

One more question how can I check the version for VarDict ? In the command line I don't see a "--version" parameter to check the version of the executable

Thanks
Best Regards
T. Hamdi Kitapci

**Comment by PolinaBevad** [comment]
These warnings won't be a problem. They mean that for few method parameters there are no description in javadoc.
Yes, we don't have --version parameter, but it is mentioned in `build.gradle` file in the root folder of repository or in jar name that created when you build VarDict. Current master version that you built is 1.6.0, it isn't released yet. We have a lot of refactoring and changes in this version. 
The last released version is 1.5.8 (here you can find releases: https://github.com/AstraZeneca-NGS/VarDictJava/releases).

**Comment by thkitapci** [comment]
Thanks @PolinaBevad 

I tried to do a test run with a bam file and I am getting a java error here is my java version and the command I run

(base) bash-4.2$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
(base) bash-4.2$ VarDict -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file
Exception in thread "main" java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at com.astrazeneca.vardict.VarDictLauncher.readBedFile(VarDictLauncher.java:133)
        at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:90)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:48)
        at com.astrazeneca.vardict.Main.main(Main.java:15)


I did not provide a bed file here. Is this a bed file related problem or something else related to my build ? 

Thanks!
Hamdi

**Comment by thkitapci** [comment]
Hi @PolinaBevad 
I think this was a bed file error. It would have been nice to have a more specific error message like "BED file missing" 

I added a bed file and now I am getting another error which seems like a samtools related error

(base) bash-4.2$ VarDict -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file -z -c 1 -S 2 -E 3 -g 4 $bed_file
Exception in thread "main" htsjdk.samtools.SAMException: Unable to find entry for contig: 1
        at htsjdk.samtools.reference.FastaSequenceIndex.getIndexEntry(FastaSequenceIndex.java:178)
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:217)
        at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:47)
        at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:79)
        at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:59)
        at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:98)
        at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:64)
        at com.astrazeneca.vardict.Main.main(Main.java:15)


I thought VarDict based on Java was supposed to be independent of samtools. Is this related to samtools itself or my reference fasta sequence ?

My fasta file is this one:  https://s3.amazonaws.com/PartekLibraryFiles/sequence_files/mm10.fa.gz

and it is indexed with samtools faidx (samtools version 1.9) 

Thanks!

**Comment by PolinaBevad** [comment]
@thkitapci, hello,
We use htsjdk library to parse SAM/BAM and fasta files and it is automatically downloaded when you build VarDict.
This error means that you have inconsistency between names of chromosomes in Fasta and BED file. I guess that mm10.fa contains name of chromosome like "chr1" but the BED file contains simple "1". 
Could you please attach the BED file?
We are thinking about automatic changing of the chromosome names in such situation but it is not implemented yet.

**Comment by PolinaBevad** [comment]
The other problem can be if you use not the same reference that BAM file was aligned to. Can you please check it in BAM header?

**Comment by thkitapci** [comment]
Hi @PolinaBevad 

This is my fasta file https://s3.amazonaws.com/PartekLibraryFiles/sequence_files/mm10.fa.gz

Here is a link to my BED file (it is too big to attach here) 
https://we.tl/t-YtLPsqOdIX

I downloaded GTF file from GENCODE M19 (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M19/gencode.vM19.annotation.gtf.gz) then used gtf2bed to convert into a bed file. 

I checked the names and fasta file and BED file seems to have the same format for chr names. 

Do you think I have a problem in my BED file ?

Thanks!
Hamdi

**Comment by PolinaBevad** [comment]
Can you please share the header from your BAM file? I checked the BED and it looks ok. But if BAM has another names in chromosomes it means that it was aligned on another fasta.

**Comment by PolinaBevad** [comment]
Hamdi, I guess that your BAM was aligned on some kind of Mus_musculus.grcm38.fa, because it contains chromosome names without "chr" part. 
If it so, then you have to use this fasta and the BED for it (or generate if from GTF). In comparison with human genome, I know that there maybe a difference between fastas in coordinates and chromosome lengths, so fasta must be exactly the same your BAM was aligned for. 
I think you can download them here: http://www.ensembl.org/Mus_musculus/Info/Index

**Comment by thkitapci** [comment]
@PolinaBevad 
you are correct I checked the header of my bam which shows as:
@HD     VN:1.4  SO:coordinate
@SQ     SN:1    LN:195471971
@SQ     SN:10   LN:130694993
@SQ     SN:11   LN:122082543
@SQ     SN:12   LN:120129022
@SQ     SN:13   LN:120421639
@SQ     SN:14   LN:124902244
@SQ     SN:15   LN:104043685
@SQ     SN:16   LN:98207768
@SQ     SN:17   LN:94987271
@SQ     SN:18   LN:90702639
@SQ     SN:19   LN:61431566
@SQ     SN:2    LN:182113224
@SQ     SN:3    LN:160039680
@SQ     SN:4    LN:156508116
@SQ     SN:5    LN:151834684
@SQ     SN:6    LN:149736546
@SQ     SN:7    LN:145441459
@SQ     SN:8    LN:129401213
@SQ     SN:9    LN:124595110
@SQ     SN:M    LN:16299
@SQ     SN:X    LN:171031299
@SQ     SN:Y    LN:91744698

The lengths are the same in the fasta file but naming is different. I will make sure to find the exact fasta file used for STAR mapper to use it. 

Thanks a lot for your help!
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi hello,
Did you manage to run VarDiсt with another fasta and Bed file?
If yes, can I close this issue?
Thanks.

**Comment by thkitapci** [comment]
Hi @PolinaBevad Yes I am able to run Vardict after fixing my fasta file. Thanks for your help You can close this issue 

Hamdi

**Comment by PolinaBevad** [comment]
Thank you for the reply!
