### ISSUE TITLE
Rscript and Perl executable locations

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#210]
Hi,
My R, Rscript and Perl are installed in a custom directory (not in the default /usr/bin/env) Is there a way to set for all R and Perl scripts my custom location ?  

I know I can do that my changing the first line in each R and Perl script which is by default

#!/usr/bin/env perl

#!/usr/bin/env Rscript

I can write a script to iterate on each .R and .pl file and change this line to my custom directory. Is there an easier/more convenient way to do this during the installation/build of this software or by setting an environmental variable on my .profile/.bashrc files ?

Thanks
Best Regards
T. Hamdi Kitapci

**Comment by PolinaBevad** [comment]
@thkitapci, hello!
Yes, you can add the folder with all this scripts on PATH by adding in your .bashrc such line:
`export PATH=/path/to/VarDict/scripts:$PATH`
Then reload it with `source .bashrc`
It is enough to set the path to the folder, not the path to every script.

**Comment by clintval** [comment]
Because VarDict scripts use the shebang `#!/usr/bin/env <cmd>` you can easily reference the location of your executables by prepending those locations to your `PATH` variable.

Just prefix your `PATH` variable with the locations to your custom install executables:


```bash
❯ CUSTOM_INSTALL_DIR=~/opt/bin
❯ PATH=$CUSTOM_INSTALL_DIR:$PATH
```

Here's an article with more information: https://opensource.com/article/17/6/set-path-linux

**Comment by clintval** [comment]
Oops sorry @PolinaBevad saw this one on my radar and thought I'd take the time.

**Comment by PolinaBevad** [comment]
Clint, thank you. It is better to have few opinions and options. :)

**Comment by PolinaBevad** [comment]
Hamdi, hello,
I will close this issue, but I added Clint answer to wiki: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Add-R-and-pl-scripts-on-your-PATH
