### ISSUE TITLE
GTF to Bed file conversion

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#212]
Hi,
I am working on a RNA-seq data for Mouse. I am trying to obtain the BED file for gene annotations.

I am using the Gencode M19 annotation file here is the link for the gff and gtf files

https://www.gencodegenes.org/mouse/release_M19.html

Since vardict requires a BED file I tried to use gtf2bed program installed from conda as part of bedops 

https://anaconda.org/bioconda/bedops

I am unable to convert to gtf file to bed I am getting the following error

(base) bash-4.2$ gtf2bed <gencode.vM19.annotation.gtf >gencode.vM19.annotation.gtf.bed
Error: Potentially missing gene or transcript ID from GTF attributes (malformed GTF at line [1]?)

Do you know how to fix this or do you have an alternative method to obtain a BED file ? Also is a BED file required to run vardict ? I want to get variants from the whole RNA-seq data. 

Thanks
Best Regards
Hamdi

**Comment by thkitapci** [comment]
I found a solution for this on biostar: https://www.biostars.org/p/206342/

using a simple awk script 

awk '{ if ($0 ~ "transcript_id") print $0; else print $0" transcript_id \"\";"; }' gencode.vM19.annotation.gtf | gtf2bed - > gencode.vM19.annotation.gtf.bed

You can keep this post here if you think it would be helpful to people or delete it 

Thanks
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,
Thank you for posting this! I will close the issue because we keep open only unsolved issues, but I will add this to git wiki of our repository with the link to the issue.
