### ISSUE TITLE
Calling variants from multiple bam files and merging

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#213]
Hi,
I have 10 samples that I want to call variants. Should I run independent runs for every bam and then merge the VCF files with vcftools vcf-merge ? Otherwise is there a way to run vardict with multiple bam inputs ? 

Thanks

**Comment by PolinaBevad** [comment]
Hi, Hamdi,
Yes, you have to run independent run on each sample that you need. We do not support multi-sample VCFs, so you can merge output VCF files with vcf-merge to get it. The only one mode that works with 2 bams at the moment is the paired (somatic) analysis, when you provide tumor and normal BAMs.

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
Thanks for your reply! I have one more question regarding the paired analysis. I do have normal vs treated samples. I have 5 samples from each group (they are from an inbred mice strain). If I want to compare these two groups, should I merge the bam files first in each group to get a single representative bam file for normal and treated samples respectively, and then run the paired analysis ? Otherwise does your paired sample analysis support biological replicates (such as comparing 5 normal vs 5 tumor samples) ?

Thanks!
Hamdi

**Comment by PolinaBevad** [comment]
Hi, Hamdi, 
We don't have the functionality to compare several samples with each other, so I think that yes, you need to first merge them by groups into two BAM files: tumor and normal. Then you can run them as usual, but in option `-b` set both of them with `path_to_tumor_BAM|path_to_normal_BAM` to run paired analysis.

**Comment by thkitapci** [comment]
Thanks for your reply @PolinaBevad  

Best Regards
Hamdi
