### ISSUE TITLE
Confused variant calling result

### ISSUE THREAD

**Issue by Gerde89** [AstraZeneca-NGS/VarDictJava#217]
Hi, 
I found a variant with 0.3% frequency was called, but a 2bp downstream position with 10% frequency was not called, a bam of this region was attached.  This is my code:
`VarDict -G hg19.fa -N sample_name -f 0.001 -b my.bam -z -c 1 -S 2 -E 3 -g 4 -th 4 region.bed | teststrandbias.R | var2vcf_valid.pl -N sample_name -E -f 0.001 | awk '{if ($1 ~ /^#/) print; else if ($4 != $5) print}' >out.vcf`
chr19:44057849 was called:
`sample_name  19  19    44057849      44057849  G       T      597      2       464     131     0       2       G/T     0.0034  2;0     13.5    1       29.5    1       60.0    4.000   0.0035  0       0       4.000   1       1.0     2       574 GGGAGTCCTGGGAAAGGAGG     GTGGGAGTCAGGGAGTCTGG    19:44057652-44058051    SNV     0       0`
chr19:44057851 was no called:
![not_called](https://user-images.githubusercontent.com/34473278/56343341-0f19c000-61ed-11e9-996f-cd3156d577f2.png)
the bam file with index:
[bamfiles.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/3093173/bamfiles.zip)

Best,
Gerde

**Comment by PolinaBevad** [comment]
Gerde, hello!
Thank you for preparing the part of BAM and providing the command!

This variant 44057851 (T->G) has a small mean base quality to be recognized as a good variant. 
If you run VarDict with `-p` option, then all the variants before filtering will be outputted and here I see that mean quality for this variant is 14.1, and we have a minimum quality 22.5 to consider variant as good. 

These filters are described in the section:  https://github.com/AstraZeneca-NGS/VarDictJava#variant-filtering 
In IGV you can also re-check it, and many reads supporting base G have quality 14 (phred-score). If you want to recognize variants with lower quality, you can run VarDict with `-q` option and set another limit.

**Comment by Gerde89** [comment]
@PolinaBevad  Hi, Polina,

Thank you for the response! 
Yes, the QMean of chr19:44057851:T->G is 15.1, it should be filtered. 
And I got a new problem, #219 ,looking forward to your reply !
Thanks a lot!

Best,
Gerde

**Comment by PolinaBevad** [comment]
Thank you! I will close this issue. 
I plan to look at issue 219 ASAP after some urgent tasks in another repository.
