### ISSUE TITLE
VarDict Java Paired sample analysis

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#221]
Hi,
I have run a paired sample analysis as described in the manual using the syntax 

`<path_to_vardict_folder>/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f $AF_THR -N tumor_sample_name -b "/path/to/tumor.bam|/path/to/normal.bam" -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | VarDict/testsomatic.R | VarDict/var2vcf_paired.pl -N "tumor_sample_name|normal_sample_name" -f $AF_THR
`

I am having trouble interpreting the resulting VCF file. I have over ~100K markers in the VCF file. I think I need to do a filtering based on the fisher test results. Are the results of the fisher exact tests for each market included in the VCF file ? Are the results multiple testing corrected ? 

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello!
We make fisher exact test on the R script step (include alternative hypothesis) and on the var2vcf_paired.pl step we have filters that use p-value (SSF field in VCF) and oddratio (SOR field) from fisher test. You can change the default value for p-value filter by using `-P` filter for pl script, default is 0.05.
Also if you want to output only variants that pass all the filters, you have to use `-S` option in pl script. Otherwise, variants will be not be filtered, but information about filters that were triggered will be printed in FILTER column.

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
Filter column looks like this

FILTER
d5;v3
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3;pSTD
d5;v3;f0.01;pSTD
d5;v3;f0.01;pSTD
d5;v3;f0.01;pSTD
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3;f0.01;p8;pSTD;q22.5;Q0;SN1.5
d5;v3
d5;v3;f0.01;p8;pSTD
d5;v3;p8;pSTD
d5;v3;f0.01
PASS
d5;v3;f0.01
d5;v3;f0.01

Where can I find the definition of what each field means ? Also I think if it passes the filter it simply says "PASS" is there any way to get the P-value associated with the "PASS" fields ? I think p_values should be corrected for multiple testing as far as I understand the p_values are from individual fisher tests without any multiple testing correction is that correct? 

I might be also missing something here and maybe multiple testing correction is not needed and I can simply use the positions marked as "PASS" can you please clarify this for me ?

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,

You can find the definition of filters in VCF header, here we have section with all Filters and their default values. 
The P-value for variant can be found in SSF field in INFO column of VCF file, so you can make other filtering based on them. 
You right that we make only individual Fisher tests. As far as I understand you have to adjust P-value in multiple comparison if you need it: there are a lot of discussion when do it and when not. For example these: 
https://www.researchgate.net/post/Do_we_need_to_adjust_p-value_Multiple_comparison
or https://www.researchgate.net/post/Fisher_and_correction_for_multiple_testing2
So I think it completely depends on what you want to get.

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I have generated my VCF file using paired samples with the following commands

`VarDict -th 24 -G $reference_fasta -f $AF_THR -N $sample_name -b "$bam_file_exp1|$bam_file_control" -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError.FirstStep >$sample_name.vardictOut.FirstStep`

`cat $sample_name.vardictOut.FirstStep | testsomatic.R | var2vcf_paired.pl -N "$bam_file_exp1|$bam_file_control" -f $AF_THR 2>$sample_name.vcf.Error >$sample_name.vcf`

Since I did not use the `-S` option in the pl script I should have all variants regardless of Filters in the output file. I was expecting to have the same number of lines in `$sample_name.vardictOut.FirstStep` and  `$sample_name.vcf` but I have the following number of lines in the 2 files

```
(base) -bash-4.2$ wc -l $sample_name.vardictOut.FirstStep
7941116 myPaired_exp1_vs_control.vardictOut.FirstStep
(base) -bash-4.2$ wc -l $sample_name.vcf
1345713 myPaired_exp1_vs_control.vcf
```

Can you please explain why there are less lines in the VCF file ? Is this due to some filtering ? 

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello,
Yes, we have filtering in VCF file. By default if few variants are in the same position, only one with the biggest AF will be outputted (this can be disabled by -A option). Also in WGS you can get some variants on the overlapping part of the regions that were doubled up because VarDict works on regions separately, so in the step of VCF file the doubled variants will be filtered out.

**Comment by PolinaBevad** [comment]
Hamdi, hello!
I will close this issue, but let me know if you will have any other questions on this topic.
