### ISSUE TITLE
VCF merge fail 

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#225]
Hi,
I run vardict on my samples using the command

`VarDict -th 4 -G $reference_fasta -f $AF_THR -N $sample_name -b $bam_file -z -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError | teststrandbias.R 2>$sample_name.RError | var2vcf_valid.pl -N $sample_name -E -f $AF_THR 2>$sample_name.vcfError >$sample_name.vcf
`

Then I am trying to use vcf-merge (https://anaconda.org/bioconda/vcftools) or bcftools (https://anaconda.org/bioconda/bcftools)

`vcf-merge T7-1.vcf.gz T7-67.vcf.gz | bgzip -c > merged.vcf.gz
`
I get the following error:

```
The reference prefixes do not agree: T vs GTGAGAA
Failed on line 9:69460472
 at /home/rcf-proj/st5/tkitapci/software/anaconda2/bin/vcf-merge line 21, <__ANONIO__> line 7475.
        main::error("Failed on line 9:69460472\x{a}") called at /home/rcf-proj/st5/tkitapci/software/anaconda2/bin/vcf-merge line 355
        main::merge_vcf_files(HASH(0x55f51b99e248)) called at /home/rcf-proj/st5/tkitapci/software/anaconda2/bin/vcf-merge line 12


```

Then I used bcftools 

`bcftools merge T7-1.vcf.gz T7-67.vcf.gz >merged.vcf
`
and I get error on the same location

```
The REF prefixes differ: T vs GTGAGAA (1,7)
Failed to merge alleles at 9:69460472 in T7-67.vcf.gz

```

Here are the 2 VCF files (they are "bgzip"ed and "tabix"ed) used in the above examples

https://drive.google.com/drive/folders/1lEe7ZMYh7hqYsEPpF4OsKNM9Vf0rKpbY?usp=sharing

I realized that this is due to a  "DEL" in the VCF file. Can there be a bug in the VCF file generation of vardict that violates the VCF rules which causes this error ? The error seems to be due to a VCF file format error.

When I try to merge other VCFs generated by vardict I am getting also similar errors and each time it is a location with a DEL

Thanks
Best Regards
Hamdi

**Comment by thkitapci** [comment]
Hi,
I have a follow up on my original question. I used bcftools to check the reference alleles and there are many mismatches in the 2 VCF files generated by vardict (links to VCF files are given in the above post) including 9:69460472 as shown in the previous post. Here are the result of the bcftools norm
```

bcftools norm --check-ref w --fasta-ref $reference_fasta T7-1.vcf.gz >temp
REF_MISMATCH    1       37154046        G
REF_MISMATCH    1       88270301        A
REF_MISMATCH    1       89665861        T
REF_MISMATCH    4       116612084       G
REF_MISMATCH    4       137329134       C
REF_MISMATCH    8       40494128        G
REF_MISMATCH    9       111219804       A
REF_MISMATCH    10      80381674        T
REF_MISMATCH    12      3442557 T
REF_MISMATCH    12      32967743        G
REF_MISMATCH    12      79166411        G
REF_MISMATCH    12      113143613       A
REF_MISMATCH    17      39845030        T
Lines   total/split/realigned/skipped:  256854/0/37/0

```

```
bcftools norm --check-ref w --fasta-ref $reference_fasta T7-67.vcf.gz >temp
REF_MISMATCH    1       88270301        A
REF_MISMATCH    1       97469978        G
REF_MISMATCH    3       158012017       A
REF_MISMATCH    4       103039343       G
REF_MISMATCH    9       49523649        C
REF_MISMATCH    9       69460472        T
REF_MISMATCH    9       79603373        C
REF_MISMATCH    11      23593486        A
REF_MISMATCH    11      29494094        A
REF_MISMATCH    11      113677407       T
REF_MISMATCH    15      76710831        A
REF_MISMATCH    15      99283992        C
REF_MISMATCH    17      23720108        A
REF_MISMATCH    18      42143166        T
REF_MISMATCH    19      6374852 T
Lines   total/split/realigned/skipped:  238276/0/40/0
```

What is the reason for this discrepancy between the reference in the reference fasta file and the reference allele reported in the VCF file generated by vardict. (Note: In the vardict run the same reference fasta file was used)

**Comment by PolinaBevad** [comment]
Hamdi, hello,
Sorry that you have the issue! At the first glance I don't remember such errors with REF base (except cases when -3 option was used). 
Could you please provide part of BAM file that covers any of these variants for debugging? 
Thank you!

**Comment by PolinaBevad** [comment]
Hamdi, hello!

I've found the case when this error appears on public data. The problem was that the REF allele base was derived from the very last symbol of the deletion sequence in SV DEL, and not from the first. The change was merged in master, so you can update the version and check if the error disappears.
Thank you for pointing on this!

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
Can you please let me know how I can update the version ? I got a couple of scripts from the other repo manually based on your suggestion from https://github.com/AstraZeneca-NGS/VarDictJava/issues/227#issuecomment-494125134. 

Can you please suggest the best way to update ? 

Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello!

You can download and compile the new version of VarDictJava as written here: https://github.com/AstraZeneca-NGS/VarDictJava#getting-source-code 
Then you have to update two scripts from https://github.com/AstraZeneca-NGS/VarDictJava/issues/227#issuecomment-494125134 as you did it before. 

We are planning to release both versions (Java and Perl) soon and then you will not need to update the scripts from Perl repository.

**Comment by PolinaBevad** [comment]
Hamdi, hello!

Java and Perl updated releases are now available (https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.6). You can download the last VarDictJava release, it contains all fixes and updated scripts.
I will close this issue. Let me know if you will have any questions!
