### ISSUE TITLE
using more CPU than given by -th 4

### ISSUE THREAD

**Issue by inti** [AstraZeneca-NGS/VarDictJava#23]
Hi,
with the following command line 

```
vardict-java \
-G /home/shared/ref_genome/Poplar/Ptrichocarpa_210_v3.0.fa -N DENA \
-b mapping/samples/hisat/DENA.sorted.bam \
-f 0.0 -c 1 -S 2 -E 3 -g 4 **-th 4** \
regions.bed |   teststrandbias.R 
```
I am getting vardict-java using more than 4 CPUs. 

I have come across similar issue with GATK before and I seem to remember the solution was to set the JVM option -XX:ParallelGCThreads=, http://gatkforums.broadinstitute.org/discussion/1975/how-can-i-use-parallelism-to-make-gatk-tools-run-faster

Is there any chance verdict-java would set the number threads used on this way? I tried it by first getting the command that was being executed, adding the -XX:ParallelGCThreads= option and it definitively restricts the number of threads used. 

Thanks in advance

from http://broadinstitute.github.io/picard/faq.html

Q: Why does a Picard program use so many threads?
A: This can be caused by the GC method of Java when used on 64 bit Java. By default the JVM switches to 'server' settings when on 64 bit, this automatically implements parallel GC and will use as many cores as it can get it's hands on. The approach we decided on to get round this was to define the number of threads we would allow Java for GC.

-XX:ParallelGCThreads=
An alternative approach is to turn off Parallel Gc (boolean option so note the '-' to indicate it is turned off):

-XX:+UseSerialGC
. We found this to be sub-optimal as the process has to stop completely when GC occurs and takes much longer as (from what I can tell) a full GC sweep is the only type performed which in many cases is not required (parallel GC employs ~7 different types of GC). See here for further details of the tuneable parameters.

**Comment by mjafin** [comment]
@jabbarish do you have any comments for this issue? I think we want to avoid intrinsically setting these Java settings and enable pipeline folks to make their minds up like in bcbio I think

**Comment by jabbarish** [comment]
@mjafin we will check it tomorrow and I will write back.

**Comment by malperovich** [comment]
Hi @inti ,
Could you please share (a part of) your regions.bed file?
We need it to find out the reason of using more CPUs.

**Comment by inti** [comment]
Hi,
yes I can but it for a non-human genome, Populus trichocarpa. So if you need to run anything you will also need the ref genome and so on. attached is an example.

thanks a lot

**Comment by inti** [comment]
Sorry. bed file is here https://gist.github.com/inti/5c45d924a37611a6ebc9

**Comment by malperovich** [comment]
@inti , we have explored all the possible solutions and have to say, that we can't limit the number of GC threads within Java code. 
The option "th" sets the number of threads for parallel calculation but this option is not applied to the GC process. To limit the number of GC threads you only can use -XX:ParallelGCThreads=<number>. By default, the number of threads is some subset of the number of processors; this numver might change depending on the version of Java.
