### ISSUE TITLE
about bed file input + running VarDictJava

### ISSUE THREAD

**Issue by mortunco** [AstraZeneca-NGS/VarDictJava#25]
Hi again,

Thank you for your previous fast response. It helped me a lot. I believe there is a problem with my mutation calling process. 

I started running with this command. 

```
~/VarDict-1.4.4/bin/VarDict -G reference/Homo_sapiens_assembly19.fasta -f $AF_THR -N tumor_sample -b "tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam|normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam" -z -c 1 -S 2 -E 3 -g 4 are_high_normal_tumor_sample.bed.txt | ~/VarDict-1.4.4/VarDict/testsomatic.R | ~/VarDict-1.4.4/VarDict/var2vcf_somatic.pl -N "tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam|normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam" -f $AF_THR > vardict.vcf 
```
My bed input is a typical bed format. However, I am calling my mutations based on a chip-seq bed file therefore I have peak names instead of gene names. 

chr6	51217257	51217593	tumor_high_1802	523.998413
chr7	66969316	66969642	tumor_high_1803	422.902191
chr6	51567727	51568019	tumor_high_1804	618.637512
chr6	51602453	51602721	tumor_high_1805	717.315308
chr6	51877947	51878195	tumor_high_1806	656.460632
chr7	68195932	68196279	tumor_high_1807	247.741989
chr11	117046945	117047229	tumor_high_1808	340.127594
chr6	52590531	52590912	tumor_high_1809	275.999542
chr6	52610638	52610983	tumor_high_1810	290.982056
chr10	29565502	29565809	tumor_high_1812	284.837311
chr7	69061173	69061526	tumor_high_1813	757.335510

1. My first question is, is it have to be gene name all the time ?
2. During the process, I am getting an error about bam index file is older than the bam file. I dont think this is an important warning but does it change anything?
3. During this process, my verdict.vcf output size does not change? This is the actual reason that I am writing this post. I think file size should increase?

Thank you very much for your patience and help.

Best,

Tunc.

**Comment by mortunco** [comment]
Still no idea about my problem ?

**Comment by mjafin** [comment]
Hi @mortunco, apologies, this escaped our attention. The fourth column isn't really used much in variant calling so doesn't matter what's in there. The warning about the bam index is probably fine. You could regenerate a new one using `tabix` if you don't want to see the warning. 

As for the vcf yes it should be growing as variants are found. However, please use `var2vcf_paired.pl` instead of `var2vcf_somatic.pl` as the latter is out of date and replaced by the former.

**Comment by mortunco** [comment]
Hi @mjafin  Thank you for your response. I would like to ask you that, can I get around this bed input? I have called mutation with different callers without any bed input and for the consistency, I would like to call mutations with VarDict like I called mutations with others. Is this possible ?
Thanks

**Comment by mjafin** [comment]
Hi @mortunco unfortunately for VarDict we do currently require a bed file. What you could do is take the full chromosome regions from your `my_genome.fa.fai` file and drop them into bed file(s) (bearing in mind bed is 0-based, end-exclusive). Do you reckon this would be an OK solution for you?
