### ISSUE TITLE
Difference between -O and -Q

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#250]
What is the difference between?
-O <MapQ>                           The reads should have at least mean MapQ to be considered a valid variant.  Default: no filtering

and

-Q <INT>                            If set, reads with mapping quality less than INT will be filtered and ignored

**Comment by PolinaBevad** [comment]
Hi @gevro,
Yes, I see the discrepancy.
`-O` relates to variants, and `-Q` to reads.
So first while we parsing the region, if we met the read with mapping quality less then `-Q`, we skip this read. If after processing all reads in the region we calculate mapping quality for variant and it is less then `-O` we will skip such variant. 
I'll fix Readme for `-O` option.

**Comment by gevro** [comment]
Hi Paulina, do you mean base quality? For bases, I think the term is base quality, not mapping quality.

**Comment by PolinaBevad** [comment]
Hi @gevro, 
No, it will be mapping quality in both cases (-Q and -O). We check MAPQ field from BAM file (column 5) and we skip the whole read if its mapping quality less than the threshold value of '-Q`. Then we calculate the mean mapping quality of variant (from mapping quality of reads that cover this variant) and skip variant if it is less than the value of '-O' option.

Base quality can be changed by `-q` option, we use QUAL field from BAM to check it. Base quality filter is used for both cases: quality of bases in reads and for calculation of the mean base quality of variant.

**Comment by gevro** [comment]
Hi Polina, I think I understand now.
However, what is the default for -Q? The help in the program does not state this.

**Comment by PolinaBevad** [comment]
Hi @gevro, this option is not set by default, so reads aren't skipped. 

If you have a sample with a large number of reads with low mapping value, it is a good practice that you set this parameter to some value to skip such reads and decrease the time of processing.

**Comment by PolinaBevad** [comment]
Hi @gevro, I'll close the issue. Feel free to open it if necessary.
