### ISSUE TITLE
Difference between -f and -V

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#251]
What is the difference between?

 -f <double>                         The threshold for allele frequency, default: 0.01 or 1%

and

 -V <freq>                           The lowest frequency in the normal sample allowed for a putative somatic mutation.  Defaults to 0.05

If only one sample is supplied (with the -b option), these two parameters would seem to conflict.

**Comment by PolinaBevad** [comment]
Hi @gevro,

`-f` option relates to all variants (in normal and tumor samples in both single and paired modes). 
`-V` relates only to a frequency of the variant in the normal sample and it is used only in somatic (paired) mode to determine if the variant type is StrongSomatic, so these options wouldn't conflict.

**Comment by PolinaBevad** [comment]
Hi @gevro, I'll close the issue. Please, open it if you have additional questions.
