### ISSUE TITLE
question about -P for the read position filter

### ISSUE THREAD

**Issue by dauss75** [AstraZeneca-NGS/VarDictJava#258]
Hello,

I am trying to understand better for -P parameter to hopefully reduce strand bias issues.
Could you kindly let me know whether it will filter out the variants within the bps of both ends or one end?

Thank you,
Segun

**Comment by PolinaBevad** [comment]
Hello Segun,

It will filter out the variants only from the one end by value in PMEAN field. 

More accurately, we calculate the mean position of variant in the read (`sum of positions in the read where the variant was found`/`variant coverage`). Also, we calculate it in one direction, iterate over positions sequentially from the start of a region to the end (i.e. we don't distinct the read direction for this field).

**Comment by PolinaBevad** [comment]
Hi Segun, 
I'll close the issue. Let me know if you need anything else.
