### ISSUE TITLE
Questions about the internal filters

### ISSUE THREAD

**Issue by FrankFeng** [AstraZeneca-NGS/VarDictJava#260]
Hi,

When reading the **Variant Filtering** section in Readme.md, I have two questions. Could you please help to address these:

1. Variant frequency is used in filter No. 1 (set by the -f option) and No. 8 (30%). It this an error of documentation or not?

2. What is "2;1" bias, as mentioned in filter No. 11? 

Thanks!

Frank

**Comment by PolinaBevad** [comment]
Hi Frank, 

1. This list of filters is applied in order, so if the variant has passed all steps up to 8-th and it has frequency 30%, then next conditions (9-12) won't be checked and variant is considered as "good". If it's frequency less then 30%, then next conditions would be also checked. And if it has frequency less than in `-f` option, then it will be filtered out as "bad" variant at the first step. 

2. Bias "2;1" means that the reads that support reference allele has no strand bias ('2'), but reads that support variant has strand bias ('1'). This will be checked together with the next step (SNV and refallele/varallele lengths), so I'll fix it and combine them in one step in the documentation.

**Comment by PolinaBevad** [comment]
Frank, here is the fix in the documentation: https://github.com/AstraZeneca-NGS/VarDictJava/pull/261, I hope that now it becomes clearer.

**Comment by FrankFeng** [comment]
Thanks Polina. Can I ask you one more question about filter number 7 which is "**The ratio of high-quality reads to low-quality reads is larger than the threshold specified by -o option (default=1.5).**"

How do you define high-quality and low-quality reads? Thanks!

**Comment by PolinaBevad** [comment]
They defined by base quality (phred score), so bases with quality less than specified by -q `option` will be low quality, otherwise - high quality.
