### ISSUE TITLE
vcf file empty

### ISSUE THREAD

**Issue by SukanyaPanja** [AstraZeneca-NGS/VarDictJava#262]
Hi,

I am getting an empty vcf file when I use teststrandbias.R, var2vcf_valid.pl, -N, _E and -f options. 
however when I tried without these options, I get the raw vcf file.

Below is my code 

~/VarDictJava/build/install/VarDict/bin/VarDict -G genome.fa -f 0.01 -N sample_name -b mybamfile..bam -c 1 -S 2 -E 3 -g 3 -th 6 hg19_5k_150bpOL_seg.bed | ~/VarDictJava/VarDict/teststrandbias.R | ~/VarDictJava/VarDict/var2vcf_valid.pl -N sample_name-E -f 0.01 > test.vcf

Can someone please help me to resolve this issue

Thanks
Sukanya

**Comment by PolinaBevad** [comment]
Hello Sukanya,
Sorry that you have the issue!

Does this command line is exactly the same you try to run? 
This one contains small error:  `-N sample_name-E`, there must be space between `name` and `-E`. I guess this is the problem, but if it doesn't help, please let me know.

Also, small remark: there can be an error in `-g 3` option, typically gene name is in the 4th column of BED file. Also, `-E` and `-g` options are both set to the same column, so I think it can lead to other errors.

**Comment by SukanyaPanja** [comment]
Hi Polina,
Sorry about the typo. I had put a space between sample name and -E also I ran it with -g 4.

My actual command is as below

 /projectsp/VarDictJava/build/install/VarDict/bin/VarDict -G genome.fa -f 0.01 -N samp1 -b /projectsp/samples/samp1.sorted.bam -c 1 -S 2 -E 3 -g 4 -th 6  hg19_5k_150bpOL_seg.bed | /projectsp/VarDictJava/VarDict/teststrandbias.R | /projectsp/VarDictJava/VarDict/var2vcf_valid.pl -N samp1 -E -f 0.01 > samp1.vcf


But I am still getting empty vcf file.

Thanks
Sukanya
________________________________

**Comment by PolinaBevad** [comment]
Hi Sukanya,

It is strange, because now I don't see any errors in your command line. Is it possible that you can share raw vardict file (before .R and .pl) scripts so I can test it? If you don't want to share it here, you can send it to me by email polina_bevad@epam.com . 

Thank you!

**Comment by SukanyaPanja** [comment]
Hi Polina,
I have emailed you the raw vcf file.

Thanks
Sukanya
________________________________

**Comment by PolinaBevad** [comment]
Sukanya, hello!

Just have checked your file and get the correct output with .R, .pl and options. 

Do you have R and perl installed in your environment (here are requirements:  https://github.com/AstraZeneca-NGS/VarDictJava#requirements)? And are there any errors in the log when you run these downstream scripts?

Please, try to run .R script first and then .pl script to determine where is the problem, for the file you sent me, like this:
`cat samp1.vcf | teststrandbias.R > samp1.R.vcf`
`cat samp1.R.vcf | var2vcf_valid.pl -N samp1 -E -f 0.01 > samp1.var2vcf.vcf`

If the first step will not create output, then there is problem with R, if second - then the problem with Perl environment. Perhaps you have them in the other directories than described in "Requirements" section.

**Comment by SukanyaPanja** [comment]
Hi Polina,
I checked with the samp1 file and it worked. However when I use the entire code it does not work

Can I please you my entire code?

Thanks
Sukanya
________________________________

**Comment by SukanyaPanja** [comment]
Hi Polina,
I also generated the entire raw vcf file and then followed your commands to execute the .R and pl scripts. However I dont get any output from .R file. Also R is loaded in my environment.

I am not sure if the raw vcf output is correct. Can I please send you my complete raw vcf file for testing purpose.

Thanks
Sukanya

________________________________

**Comment by PolinaBevad** [comment]
Hi Sukanya,
I sent you the VCF file and links to last versions of R and pl script that I used to create this VCF file from your raw vardict file.
Please let me know if there is still the empty output after using new versions.
Thank you!

**Comment by PolinaBevad** [comment]
Hi, Sukanya,
Is everything okay with VCF file now? Do you have any errors on new version?

**Comment by PolinaBevad** [comment]
Hi Sukanya,
I'll close the issue because I suggest that you managed to get the output. 
Please, re-open the issue if you still have any problems.
Thank you!
