### ISSUE TITLE
Vardict finds variants for REF 'M' and 'R'

### ISSUE THREAD

**Issue by DavyCats** [AstraZeneca-NGS/VarDictJava#267]
Vardict reports variants with REF 'M' and REF 'R', eg:
```
NA12878	chr1	chr1	248752514	248752514	M	A	2	1	0	0	1	0	A/A	0.5000	0;0	5.0	0	30.0	0	60.0	2.000	0.5000	0	1.0	3	2	0	0	1	1	A/A	0.6667	0;2	59.0	1	30.0	0	60.0	4.000	0.6667	0	3.5	0	3.000	1	CCCCCCACACACACCAAACA	CCCACACAACACACACACAC	chr1:247999850-248956422	Germline	SNV	0	0	0	0
NA12878	chr1	chr1	248755122	248755122	R	G	1	0	0	0	0	0	A/A	0	0	0	0	0	0	0	0	0	0	0	5	4	0	0	4	0	G/G	0.8000	0;0	36.0	1	30.0	0	60.0	8.000	0.8000	0	1.0	0	1.000	1	GGTCAGGACTTGACCCAGGG	CACCTAGCAGAGAAACAGAG	chr1:247999850-248956422	StrongLOH	SNV	0	0	0	0
```

The reference sequences (GRCh38) do actually contain these notations on those positions:
```
⟫ faidx reference.fa chr1:248752514-248752514
>chr1:248752514-248752514
M
⟫ faidx reference.fa chr1:248755122-248755122                                                                                                                
>chr1:248755122-248755122
R
```

These variants cause issues with downstream proccessing of the produced VCF file. Picard, for example, refuses to parse these lines which makes sense since the VCF specs only allow for `A`, `C`, `G`, `T` and `N` to be used in the REF field. The VCF specs actually mention how such reference alleles should be handled: 
>"If the reference sequence contains IUPAC ambiguity codes not allowed by this specification (such as R = A/G), the ambiguous reference base must be reduced to a concrete base by using the one that is first alphabetically (thus R as a reference base is converted to A in VCF.)"
-- https://samtools.github.io/hts-specs/VCFv4.3.pdf, section 1.6.1, item 4

**Comment by PolinaBevad** [comment]
Hi @DavyCats,
Thank you for finding this! 
Yes, we should definitely support the specification requirements for this field. I will add this to the next release.

**Comment by PolinaBevad** [comment]
Hi @DavyCats, 
The change for the ambiguity ref allele was merged.
