### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Liripo** [AstraZeneca-NGS/VarDictJava#274]
Hi :
I would like to ask what is wrong in the picture below.
![image](https://user-images.githubusercontent.com/54770415/68279891-61e69680-00af-11ea-8788-76a82fe88015.png)
My script is:
java -jar /data3/liaorp/software/VarDictJava-master/build/libs/VarDict-1.7.0.jar \
        -G /data3/liaorp/hg/bwa_index_hg38/hg38 -N NL190218 -f 0.01 \
        -b AMP_allele.bam \
                beds/correct_5columns.bed
The bam file is: VarDictJava/src/test/resources/com/astrazeneca/vardict/integrationtests/AMP_allele.bam
The bed is :
VarDictJava/src/test/resources/com/astrazeneca/vardict/integrationtests/beds/correct_5columns.bed

**Comment by PolinaBevad** [comment]
Hi, @Liripo ,
Sorry that you have the problem!
Please, try to add to you command line these parameters to set number of columns for chromosome, start, end of the region and gene, like:
`-c 1 -S 2 -E 3 -g 4`
I guess it will help.

**Comment by Liripo** [comment]
Thank you for your help。

**Comment by PolinaBevad** [comment]
Thank you, Liripo!
I'll close the issue, please, create a new one if there will be any other problems.

**Comment by markw3lsh** [comment]
This solved a similar issue I was having, but it took me quite a while to find this thread when searching through the repo issues. Please consider renaming the title here so others can find it more easily, thanks!
