### ISSUE TITLE
Handling multiallelic positions

### ISSUE THREAD

**Issue by andurill** [AstraZeneca-NGS/VarDictJava#275]
Hi,

At multiallelic positions, vardict (tested with VarDictJava_1.5.8) seems to only report the variant with the highest VAF and ignore other ALT alleles. I think the ideal behaviour should be the reporting of all ALT alleles, above specified VAF threshold, in comma-separated format in a single variant entry or report each ALT allele as a new entry/row. I have attached an example below.

![Complex_and_multiallelic](https://user-images.githubusercontent.com/12943340/69921026-86d6eb00-145c-11ea-84f1-d8758622cfd1.png)

Currently, vardict reports this as (only first 5 columns are shown):
1.) SNV
`16	11349287	.	C	A`
`16	11349290	.	C	T`
or as 2.) Complex MNV
`16	11349287	.	CTGC	ATGT`

The C>T alteration at 11349287 is ignored, even though its at a VAF > 5%.

Ideally, these variants should be reported like this:
1.) SNV
`16	11349287	.	C	A`
`16	11349287	.	C	T`
`16	11349290	.	C	T`
or as 2.) Complex MNV
`16	11349287	.	CTGC	ATGT`
`16	11349287	.	CTGC	TTGT`

**Comment by PolinaBevad** [comment]
Hi @andurill ,

Can you please try to run this also with `-A` option in var2vcf_valid.pl/var2vcf_paired.pl step (not VarDict step)? It should output all variants, not just the one that has the highest VAF. 

I think this should help. If some of the variants do not appear, please, just send me the BAM file and I will take a look.

Thank you!

**Comment by andurill** [comment]
@PolinaBevad , thank you. Adding the `-A` option to var2vcf_paired.pl works.
