### ISSUE TITLE
-th in multiprocess and Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1204, <SAM> line 548. Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 3935. Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 3938

### ISSUE THREAD

**Issue by 2236529177** [AstraZeneca-NGS/VarDictJava#276]
hi,when i run my command like following(use parallel, and I just have the tumor bam), it gives some stout

```
for i in `ls | xargs -I {} echo {}|cut -d . -f 1 | sort|uniq`
do
(/data/ngs/softs/VarDictJava/VarDict/vardict -G /data/ngs/database/GATK_Resource_Bundle/hg19/ucsc.hg19.fasta -f 0.01 -N ${i} -b ${i}.sorted.bam -z -c 1 -S 2 -E 3 -g 4 /data/ngs/database/bed/DU.bed | /data/ngs/softs/VarDictJava/VarDict/teststrandbias.R | /data/ngs/softs/VarDictJava/VarDict//var2vcf_valid.pl -N ${i} -E -f 0.01 > ${i}.vcf)&
done
```
**stdout like following, and increase with the process going on** 
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1204, <SAM> line 548.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 3935.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 3938.
Use of uninitialized value in string ne at /data/ngs/softs/VarDictJava/VarDict/vardict line 3648.
Use of uninitialized value in string ne at /data/ngs/softs/VarDictJava/VarDict/vardict line 3648.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 4168.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1116, <SAM> line 4175.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1204, <SAM> line 1573.
Use of uninitialized value in hash element at /data/ngs/softs/VarDictJava/VarDict/vardict line 1204, <SAM> line 1576.

2 vardcit will dedup in inner, so I just give the sorted.bam is ok, am i right?

3 -th [threads]
If this parameter is missing, then the mode is one-thread. If you add the -th parameter, the number of threads equals to the number of processor cores. The parameter -th threads sets the number of threads explicitly.

if i set -th 8, it will use 8 each. but not all the cores in my server?

**Comment by 2236529177** [comment]
after 3 hours, the content in the vcf seems unuseful.
![image](https://user-images.githubusercontent.com/25199946/70119597-9b59f400-16a5-11ea-8836-e6909997b381.png)

**Comment by 2236529177** [comment]
the example code in the https://github.com/AstraZeneca-NGS/VarDictJava in Single sample mode

```
AF_THR="0.01" # minimum allele frequency
<path_to_vardict_folder>/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -z -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N sample_name -E -f $AF_THR
```

give the -z，but no value, so i delete the -z, and run the code like following, but meet another error
![image](https://user-images.githubusercontent.com/25199946/70130159-019d4180-16bb-11ea-9da0-deeb2a88d22c.png)

**Comment by PolinaBevad** [comment]
Hi @2236529177 ,
Sorry that you have the issue!

You are trying to use -th option with VarDict Perl version, but Perl version doesn't support multithreading. Please, try to run Java version to avoid these hash errors (we have better error handling in Java) and run it in multithreading mode.

VardictJava will use amount of cores that you set in -th option, regions from BED file will be added to a queue and each core will take a region to process from this queue.

We have dedup in VarDict, and it can be enabled by option -t. 
Let me know if you have any questions!

**Comment by 2236529177** [comment]
I think I am using vardict java version, because I downloaded it by git clone --recursive https://github.com/AstraZeneca-NGS/VarDictJava.git

and about the code , the argument -z, is the example wrong?

thanks a lot

**Comment by PolinaBevad** [comment]
No, you run Perl version from VarDict subfolder where Perl scripts are located. To run Java version you have to use the example command, where path must be "<path_to_vardict_folder>/build/install/VarDict/bin/VarDict". 
Argument -z can be used if your BED file is 1-based, if not you can delete it. I will test it to be sure if it works correctly and fix documentation if not.

**Comment by 2236529177** [comment]
thanks  a lot. another question is about the bam input
1 . the dedup and recall bam by gatk
2 the sorted.bam and use -t in vardict

which choice is better, thanks a lot

**Comment by PolinaBevad** [comment]
I recommend to use sorted BAM and -t option, because recalibration can significantly changer result. I remember some issues when results were lost in recalibrated data. VarDict makes local realignment, and this function can be broken if data was already processed in GATK tools. 

There were some fixes regards pileup option and SV analysis for softclips when determining chimeric, so it is better to use last version from master branch, I think!

**Comment by 2236529177** [comment]
thanks a lot, your answer is always so in time and helpful, what a good researcher you are.

**Comment by PolinaBevad** [comment]
Glad to help you!
You are right about -t option: it will skip such reads, as they are deleted. This will also output information column DUPRATE = duplicate reads/total reads for the fraction.

**Comment by PolinaBevad** [comment]
Hi @2236529177 , 
Can we close this issue or do you have other open questions?

**Comment by PolinaBevad** [comment]
Hi @2236529177, I'll close the issue, but please open another one if you will have any other questions!
Thank you!
