### ISSUE TITLE
Problem with output

### ISSUE THREAD

**Issue by SuhanC** [AstraZeneca-NGS/VarDictJava#277]
HI, I'm using Vardict Java for variant calling for targeted sequenced bam files.
But after running the program, it keeps giving me output comprised only of chr1.
I didn't put any of the options regarding chromosome specification.

os.system('/home/sysbioinfo1/VarDictJava/build/install/VarDict/bin/VarDict -G /home/sysbioinfo1/data/refg/hg19.fa -f 0.3 -N '+s.split('.')[0]+' -b /home/sysbioinfo1/data/NSCLC_DATA/'+s+' -z -Q 15 -I 100 -c 1 -S 2 -E 3 -g 4 /home/sysbioinfo1/data/bed/'+s.split('.')[0]+'.printrecal.bed | /home/sysbioinfo1/VarDictJava/build/install/VarDict/bin/teststrandbias.R | /home/sysbioinfo1/VarDictJava/build/install/VarDict/bin/var2vcf_valid.pl -N '+s.split('.')[0]+' -E -f 0.3 > /home/sysbioinfo1/data/Vardict_vcf2/'+s.split('.')[0]+'.vardict'+'.vcf')

I'm running it through python.
Here's my code.
Thank you !

**Comment by SuhanC** [comment]
And i found outcome is not properly coming.
It gives me 'Killed' message, and it proceeds to next file. 
I think it's the problem of specifying the whole chromosome.
Is there any options i can do with it ?

Thank you.

**Comment by PolinaBevad** [comment]
Hi @SuhanC , 
Could you show what your BED file looks like? VarDict works on regions (i.e. lines) in BED file separately, so when it processes one region, it will output it to the downstream script. So there shouldn't be any problems with the whole chromosome. 
I think you need to add redirection of errors to some file, like `2> error.log` and share what errors have appeared.

**Comment by SuhanC** [comment]
Hi, 

Here's how my bed file looks like.
It keeps giving me error messages like bam index file is older than bam file ,
and the error 'Killed' at the same time.

chrM                          13768                         13865                         SN840:1145:H7N57BCX2:1:2103:15498:51680/1                   60                            -
chrM                          13768                         13869                         SN840:1145:H7N57BCX2:2:1211:14634:43197/1                   60                            -
chrM                          13771                         13872                         SN840:1145:H7N57BCX2:1:2214:10228:42690/1                   60                            +
chrM                          13782                         13883                         SN840:1145:H7N57BCX2:1:2104:1266:15117/1                    60                            +
chrM                          13782                         13883                         SN840:1145:H7N57BCX2:2:1211:7077:87577/1                    60                            -
chrM                          13783                         13884                         SN840:1145:H7N57BCX2:1:1111:4085:81678/2                    60                            -
chrM                          13784                         13885                         SN840:1145:H7N57BCX2:2:2213:19198:67049/1                   60                            -
chrM                          13785                         13886                         SN840:1145:H7N57BCX2:1:2104:1266:15117/2                    60                            -
chrM                          13785                         13886                         SN840:1145:H7N57BCX2:1:2214:10228:42690/2                   60                            -
chrM                          13791                         13892                         SN840:1145:H7N57BCX2:2:1215:8385:43408/2                    60                            +
chrM                          13794                         13895                         SN840:1145:H7N57BCX2:1:2107:14073:83798/1                   60                            -
chrM                          13802                         13903                         SN840:1145:H7N57BCX2:1:1105:16053:4374/2                    60                            +
chrM                          13803                         13904                         SN840:1145:H7N57BCX2:2:2204:17344:71558/2                   60                            +
chrM                          13818                         13919                         SN840:1145:H7N57BCX2:1:2102:18996:12086/1                   60                            -
chrM                          13821                         13922                         SN840:1145:H7N57BCX2:1:1107:12518:53019/1                   60                            +
chrM                          13822                         13923                         SN840:1145:H7N57BCX2:2:2103:11755:87526/2                   60                            +
chrM                          13829                         13930                         SN840:1145:H7N57BCX2:2:1215:8385:43408/1                    60                            -
chrM                          13833                         13934                         SN840:1145:H7N57BCX2:1:1105:16053:4374/1                    60                            -
chrM                          13835                         13936                         SN840:1145:H7N57BCX2:1:2107:8877:86322/2                    60                            +
chrM                          13846                         13947                         SN840:1145:H7N57BCX2:1:1114:8100:37032/1                    60                            +
chrM                          13852                         13953                         SN840:1145:H7N57BCX2:2:2208:18382:56660/1                   60                            +
chrM                          13867                         13968                         SN840:1145:H7N57BCX2:1:1105:16232:60906/1                   60                            +

**Comment by PolinaBevad** [comment]
I think you have to check how the program works outside python. BAM index file warning will not stop processing, so there must be other errors. Perhaps they appear due to network problems and it is better to debug this locally first. Can you share the whole error.log file that you get?
BED file looks okay, except one thing: do you really need so small regions? chrM is small and can be processed in once, but here I see a lot of overlapping and duplicated regions.

**Comment by PolinaBevad** [comment]
Hi @SuhanC ,
Did you manage to run the program successfully? Can I help you somehow?

**Comment by PolinaBevad** [comment]
Hi @SuhanC , I'll close the issue as I think it is not relevant already. Thank you!
