### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by ALFLAG** [AstraZeneca-NGS/VarDictJava#279]
Hello every one.
I have a question about the -k option, which perform local realignment when set to 1.

I was reading my code this afternoon, and I read a comment about this option:
```# -k option: set to 1 for Illumina data, set to 0 for Ion-torrent and PacBio data.```

The problem is I have absolutely no idea why I wrote this, and where I found such intel.
Is there any reasons to perform a local realignment when using Illumina over Ion-torrent datasets ?

Thanks for your answer.

**Comment by PolinaBevad** [comment]
Hi @ALFLAG ,

I guess it is a copy of the line from the VarDict Perl documentation. The reason to disable local realignment (it is enabled by default) is that Ion has lower base quality scores compared to Illumina so local realignment may not give the best result, it can find too many indels. And the same for PacBio. 

Here was a small discussion on this topic: https://github.com/AstraZeneca-NGS/VarDict/issues/12#issuecomment-127227453.

**Comment by ALFLAG** [comment]
Thank you for your answer @PolinaBevad.
I will put a link to this discussion in my code.
