### ISSUE TITLE
simple , somatic ,amplicon mode 

### ISSUE THREAD

**Issue by kkamii** [AstraZeneca-NGS/VarDictJava#286]
hello!

I read your guideline and followed it using my bam file.
But, I don't understand the difference among simple mode, somatic mode, amplicon mode.

Could you explain the difference briefly??

thank you  :)

**Comment by jasteen** [comment]
Whilst i'm not a dev, I have used vardict a lot.

simple mode is single sample mode.  ie, not somatic pairs.  Single germline or unmatched tumor samples.

somatic mode is exactly as it suggests.  matched germline/tumor pairs for calling somatic variants.

amplicon mode is for amplicon based panel sequencing.  Where there are a lot of reads that share the same start and stop coordinates.

**Comment by kkamii** [comment]
Thank you !!

**Comment by PolinaBevad** [comment]
Thanks a lot Jason (@jasteen) for answering this! @kkamii thank you for using VarDict!
I'll close the issue!
