### ISSUE TITLE
fix IUPAC ambiguity codes in reference ? 

### ISSUE THREAD

**Issue by cagaser** [AstraZeneca-NGS/VarDictJava#287]
Hello VardDic developers, 

I was wondering if there will be a new release soon, including the fix for IUPAC ambiguity codes in the reference( #270 ) ? I'm having the same issue as #267.

**Comment by PolinaBevad** [comment]
Hi Cedrik,
Yes, I think we plan a new release soon. There are few issues that I want to check before release, so I guess it will be May release.

**Comment by PolinaBevad** [comment]
You can also build VarDict from master to fix the issue, if it is critical for your pipeline! Let me know if you need help with this.

**Comment by PolinaBevad** [comment]
Hi Cedrik, we released 1.8. Vardict and it contains IUPAC fixes! I will close this issue.
