### ISSUE TITLE
Version 1.4.5.beta  - fix for issues #7 and #26

### ISSUE THREAD

**Issue by jabbarish** [AstraZeneca-NGS/VarDictJava#29]
Applied changes from 'ccb858dbcc4d279b6cdfa5983eba4f135fc63d04' revision of perl version (fixed issues 7, 26)

Due to discovered diffs in results of perl and java version on some data files, we are placing here binaries for tests.
[VarDict-1.4.5.beta.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/147038/VarDict-1.4.5.beta.zip)

**Comment by chapmanb** [comment]
Thanks for adding the new versions. I did whole genome validations of 1.4.5.beta against the DREAM synthetic 4 dataset and the results look good and are in line with previous versions. I'd suggest rolling a new official release with these fixes as long as @mjafin and @zhongwulai agree. Thanks again for all the work.

**Comment by mjafin** [comment]
+1 for that
