### ISSUE TITLE
Decompose complex variants into SNV

### ISSUE THREAD

**Issue by fmarinn** [AstraZeneca-NGS/VarDictJava#290]
Hi,

I am using VarDictJava v1.7 for variant calling in single sample mode.
Some of the variants are classified as complex but I am interested only in individual SNV (one variant per position). Is there an option to decompose these “complex” or MNP variants to single ones?
I have tried to set –X option to 0 (no extension to look for mismatches after insertion and deletions) and  I have been able to decompose some of the complex variants but few of them (that not include indels) remain in the output.

Thank you.

**Comment by PolinaBevad** [comment]
Hi @fmarinn,

Sorry but we really don't have the option to turn combining of complex variants. It is not easy to add such option as we have many places in code where complex variants are creating and combining from SNV. 
Maybe you can try something like `vt decompose_blocksub`? I know that it can split the significant amount of MNVs.

**Comment by fmarinn** [comment]
Hi @PolinaBevad ,

I have tried the tool and it worked perfectly. 
My only concern is that the info (e.g DP,AD) is the same for all variants deriving from the same MNV, as expected. However, it is the best solution I could find.

Thank you!

**Comment by PolinaBevad** [comment]
Hi, @fmarinn,
That's great, glad to help you!
I will close the question then.
