### ISSUE TITLE
No locations given "REF" in amplicon mode with -p

### ISSUE THREAD

**Issue by jasteen** [AstraZeneca-NGS/VarDictJava#294]
When running vardict with amplicon mode, no bases get assigned as "REF".  They all get assigned as SNV with identical ref and alt bases.  However, vardict seems to randomly decide whether its 100% ref or 100% alt.  I'm currently running Polinas PR that addressed #285 .

using the data that i've previously provided (#285), with

`VarDict -G human_g1k_v37_decoy.fasta -f 0.1 -N mre11_test -p --nosv -b MRE11a.bam -c 1 -S 2 -E 3 -g 4 test.amplicon.MRE11A.8col.bed > "test3.tsv"`

and taking a small subset of test3.tsv, we see that two bases return ~840 variant bases, and the third returns the same number of ref bases.  These are on the same amplicon.

`mre11_test	MRE11A_1_F1	11	94153262	94153262	T	T	0	844	0	0	421	423	0	0.9976	2	29.5	1	34.5	60.0	24.576	1.0000	0	0	0	0	0.2	811	811	0	0	11:94153262-94153262	SNV	0	1	0	0
mre11_test	MRE11A_1_F1	11	94153263	94153263	T	T	0	845	0	0	422	423	0	0.9988	2	30.5	1	32.9	60.0	10.901	1.0000	0	0	0	0	0.2	774	774	0	0	11:94153263-94153263	SNV	0	1	0	0
mre11_test	MRE11A_1_F1	11	94153264	94153264	G	G	846	0	422	424	0	0	G/G	0	2;0	31.5	1	34.6	60.0	27.200	1.0000	0	0	0	0	0.2	816	816	0	0	11:94153264-94153264	SNV	0	1	0	0`

if we count the number of variant types for this gene, we see
       4 Complex
     30 Deletion
      4 Insertion
   3328 SNV

there is also a small problem where a very low amount of noise results in variants with an AF of 0.002 or similar being called SNV's with a ref and alt, when these should clearly be called REF (probably anything under -f should be considered REF for this purpose).

I cant find where in the Java code the variants are assigned to a category, so i'm not even sure where to start looking for how to fix this.

cheers

Jason

**Comment by PolinaBevad** [comment]
Hi Jason, 

Thank you for pointing on this. 
I'll add the note to add separate status for ALT==REF cases, as we don't have it at the moment. 

For low frequency variants: I think we have to leave it as is because pileup option skips frequency filter and we can't rely on -f here. Pileup mode has two scopes of application: 1) debugging of variants if they are filtered and you want to find out why and 2) generating format similar to gVCF.
Do you use it for the second option?

**Comment by jasteen** [comment]
Thanks @PolinaBevad 
yes, the hope is to use it to generate the equivalent of gVCFs across our study.

**Comment by PolinaBevad** [comment]
Good, I've added fix here: https://github.com/AstraZeneca-NGS/VarDictJava/pull/297 
The one more change that were listed in PR - REF variants will not be counted in amplicons counters (like good and bad amplicons).

**Comment by jasteen** [comment]
i still dont think its behaving quite as expected. 

```
[jste0021@m3a006 data_to_share]$ VarDict -G human_g1k_v37_decoy.fasta -f 0.1 -N mre11_test -p --nosv -b MRE11a.bam -c 1 -S 2 -E 3 -g 4 test.amplicon.MRE11A.8col.bed > "test5.tsv"                                                                                                                                                                                                              
[jste0021@m3a006 data_to_share]$ cut -f1-15,34 test5.tsv | head
mre11_test      MRE11A_1_F1     11      94153262        94153262        T       T       0       844     0       0       421     423     0       0.9976
mre11_test      MRE11A_1_F1     11      94153263        94153263        T       T       0       845     0       0       422     423     0       0.9988
mre11_test      MRE11A_1_F1     11      94153264        94153264        G       G       846     0       422     424     0       0       G/G     0
mre11_test      MRE11A_1_F1     11      94153265        94153265        C       C       0       845     0       0       422     423     0       0.9988
mre11_test      MRE11A_1_F1     11      94153266        94153266        A       T       846     2       421     423     1       1       A/T     0.0024  SNV
mre11_test      MRE11A_1_F1     11      94153267        94153267        T       T       846     0       422     424     0       0       T/T     0
mre11_test      MRE11A_1_F1     11      94153268        94153268        G       G       0       845     0       0       421     424     0       0.9988
mre11_test      MRE11A_1_F1     11      94153269        94153269        T       T       0       842     0       0       420     422     0       0.9953
mre11_test      MRE11A_1_F1     11      94153270        94153270        T       T       0       844     0       0       422     422     0       0.9976
mre11_test      MRE11A_1_F1     11      94153271        94153271        T       T       0       844     0       0       421     423     0       0.9976
```

base 94153264, 66 and 67 appear as I would expect for this data, however the other 7 bases erroneously ascribe all of the depth to alternate alleles, when they are clearly 100% reference.  am I missing something obvious?

**Comment by PolinaBevad** [comment]
Hi Jason, 
Yes, you are right, it is a bug in amplicon calling for ref coverage (and it appears only in pileup mode) - we didn't test amplicons with pileup a lot before. Sorry that you have the issue with this!

I added a fix to a previous PR - total coverage and counters for reverse/forward are good now, and AF is also updated. Please, take a look at it!

**Comment by jasteen** [comment]
an initial run on the test data looks perfect.

thanks very much for all your help.  we have already put more than 25k samples though vardict amplicon mode in previous pipelines. so far we havent found a variant caller that is even close to the speed or sensitivity of VarDict Java. This will make life a lot easier in the future when we are trying to get call rates across the study.

**Comment by PolinaBevad** [comment]
Hi Jason, I'll close this issue!
Thank you a lot for finding this!
