### ISSUE TITLE
VCF records with missing REF field are output in gVCF

### ISSUE THREAD

**Issue by mjhipp** [AstraZeneca-NGS/VarDictJava#299]
First, I apologize, as I was not able to create a minimal BAM file to reproduce this issue, because I can not figure out what is causing it. Since I cannot provide the input data, I will try to outline the issue as best I can.

I am using VarDictJava to produce gVCF files (with a record at each position, even if there is no variant). After updating VarDictJava to the `master` branch, I had a pipeline produce VCF files that caused both Picard `SortVcf` and IGV to fail with the error, "The provided VCF file is malformed at approximately line number 62: empty alleles are not permitted in VCF records". This happened in about half of the samples in my run, and I could not pinpoint what the difference between samples was that could cause this.

Line 62 was the first record of the file. The record is at position 0 (which is odd, and does not overlap with my input BED file), and `REF` is blank. Also, `QUAL/DP=0`. It also looks like everything except `SPANPAIR` is 0.

```bat
  61   │ #CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  Sample1
  62   │ chr10   0   .       .   0   d3;v2;pSTD;q22.5;Q10;SN1.5  SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0
       │ ;BIAS=0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3
       │ =0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=19    GT:DP:VD:AD:AF:RD:A
       │ LD   0/0:0:0:0:0:0,0:0,0
```

There were more entries in that file with an empty `REF`, each with `QUAL/DP=0` (among other `0` fields). In fact, the records with an empty `REF` were the only records in the VCF where `QUAL=0` OR `DP=0`. _This is a very small percentage of the total records in the "malformed" gVCF file._

```
❯ cat malformed.vcf | awk '$4 == "."'
chr10   0       .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=19    GT:DP:VD:AD:AF:RD:ALD0/0:0:0:0:0:0,0:0,0
chr10   65272063        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=19    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65272090        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=43    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65272097        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=32    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65285904        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=47    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65285971        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=46    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65294932        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=29    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
chr10   65296395        .               .       0       d3;v2;pSTD;q22.5;Q10;SN1.5      SAMPLE=Sample1;TYPE=REF;DP=0;VD=0;AF=0;BIAS=0:0;REFBIAS=0:0;VARBIAS=0:0;PMEAN=0;PSTD=0;QUAL=0;QSTD=0;SBF=1;ODDRATIO=0;MQ=0;SN=0;HIAF=0;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=0;HICOV=0;LSEQ=;RSEQ=;DUPRATE=0;SPLITREAD=0;SPANPAIR=29    GT:DP:VD:AD:AF:RD:ALD 0/0:0:0:0:0:0,0:0,0
```

All but one of the above VCF records did not overlap my input BED file. 
- The records that did not overlap the BED file are the only records in the VCF that do not overlap the BED file. 
- The one that did also had a valid entry for that position. Meaning removing these empty allele records would result in a valid gVCF file. 
- Most of these records also do not overlap an input BAM record.

I checked for this issue on multiple versions of VarDictJava:

| VarDictJava version | VarDict version | Malformed VCF? |
|:-- |:-- |:--:|
| v1.7.0       | v1.6 | NO |
| 6618039 | v1.6 | NO |
| 7b86e6d | v1.6 | NO |
| 6ed76a0 | v1.6 | NO |
| db17547 | v1.6 | YES |
| b772179 | v1.6 | YES |
| 03eb543 | f0e0da0 | YES |

This leads me to believe whatever causes this issue came from https://github.com/AstraZeneca-NGS/VarDictJava/pull/271

Here is the command that produced the malformed VCF (again, sorry I cannot provide input data):

```bash
❯ VarDictJava/build/install/VarDict/bin/VarDict -N Sample1 -b sample1_paired_end.bam -G hs38DH/hs38DH.fa -p -z 1 -c 1 -S 2 -E 3 -g 4 -F 0x700 -f 0.0 -r 1 -q 2 -m 1024 -K -th 15 sample1_intervals.bed \
  | VarDictJava/VarDict/teststrandbias.R \
  | VarDictJava/VarDict/var2vcf_valid.pl -N Sample1 -A -m 8.0 -p 0.0 -d 0 -v 0 -f 0.0 -E \
  > malformed.vcf
```

**Comment by PolinaBevad** [comment]
Hi Michael,

Sorry that you have the issue and thank you for testing with different branches! Yes, we are working now on changing pileup (as it didn't work in amplicon mode as it must), perhaps there is a bug.

Could you please tell, do you have SVs in output (i.e. INV/DEL/DUP) for the samples where you have a problem? And if you run VarDict with `--nosv` option, will the problem still appear? And are these malformed variants always in position 0? 
Thank you a lot in advance!

**Comment by mjhipp** [comment]
Hi Polina,
Thanks for your reply. Yes, there are likely several DELs in the input BAMs. When the issue occurs, it seems there is always a record at position 0, as well as other positions that may be different between samples. 
I will try running with `--nosv` and let you know what happens, but it may be a little while before I can try that test. 
Thanks!

**Comment by PolinaBevad** [comment]
Hi Michael,

I've added PR in VarDict perl repository to skip such empty references:
https://github.com/AstraZeneca-NGS/VarDict/pull/145
These are artifacts of pileup mode when SV calling occur (otherwise such positions won't appear in output). 
Thank you for finding this!

**Comment by mjhipp** [comment]
Hi Polina, 
Thank you! I tried my data with your VarDict branch, and with that change, we no longer get the records with empty REF!

**Comment by mjhipp** [comment]
Closing since https://github.com/AstraZeneca-NGS/VarDict/pull/145 was merged. Thanks!
