### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rhshah** [AstraZeneca-NGS/VarDictJava#30]
Thanks again for being so responsive, It will be great if you guys could add the ability to genotype other samples from the vcf output of VarDict, especially for the merged variants.

**Comment by mjafin** [comment]
Hi @rhshah do you mean like taking a vcf and genotyping another sample in the same loci? Kind of squaring off? Or are you trying to restrict calling to variants in vcf to perform fingerprinting or similar?

**Comment by rhshah** [comment]
Thanks @mjafin  for your response, yes i meant taking the a vcf and genotyping another sample in the same loci.

**Comment by mjafin** [comment]
@rhshah I think what you describe can be implemented in a few ways. You could always convert your vcf to a bed file and use that in calling in another sample. There is also an extra option in VarDict for reporting depth at all loci regardless of variant support, see https://github.com/AstraZeneca-NGS/VarDict/blob/master/vardict.pl#L2762. If this helps (or doesn't) let us know
