### ISSUE TITLE
Running on WGS data

### ISSUE THREAD

**Issue by vymao** [AstraZeneca-NGS/VarDictJava#300]
Hi, 

How should we run this on WGS data? What should we put for the BED file field?

**Comment by PolinaBevad** [comment]
Hi Victor,

You can generate BED file as described in this wiki page: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Best-practics-for-WGS-and-multithreading
There are recommendations about windows sizes and overlapping regions as well.

**Comment by vymao** [comment]
Will the hg19 bed file listed here (https://github.com/AstraZeneca-NGS/VarDict/blob/master/hg19_5k_150bpOL_seg.txt.gz) work?

**Comment by PolinaBevad** [comment]
If you liftover it, then yes. 
Unfortunately, b17 and hg37 aren't exactly the same (please, take a look here about difference and chain files for liftover: https://www.biostars.org/p/101543/), so I recommend liftover it or generate new one with bedtools.

**Comment by vymao** [comment]
Ok thank you. Just to make sure, we can parallelize this with multithreading via `-th` correct?

**Comment by PolinaBevad** [comment]
Yes, you are right, VarDictJava version has multithreading option `-th` (unlike VarDict Perl version). 
You have to set number of cores as option for it (`-th 8` for example) then each core will process BED region separately.

**Comment by vymao** [comment]
Ok. How many cores would you say is necessary to run on a WGS sample in under a day?

**Comment by PolinaBevad** [comment]
That's fully based on coverage, but I think 16 cores will be enough for 200 Gb sample.
Also I recommend to use `--fisher` option with WGS samples (not panel/exome), as R script (teststrandbias.R) is very slow with big dataframes, and it can be run for hours after processing in VarDictJava was ended. 
We added option `--fisher` recently to avoid this. It is merged in master, so you need to build VarDictJava from master to use it. You have to skip `teststrandbias.R` or `testsomatic.R` step then, so your command line will look like:

    vardict-java -G $genome --fisher -f $AF_THR -N ${tumor_sample_name} -b "${tumor_bam}|${normal_bam}"  ${bed_file}| var2vcf_paired.pl -N "${tumor_sample_name}|${normal_sample_name}" -f $AF_THR > result.vcf

**Comment by PolinaBevad** [comment]
Hi Victor,
I'll close the issue as I guess it was resolved! Please open it again if you need other help on calling variants on WGS.
