### ISSUE TITLE
Uninitialized value in join or string, line 2230-2231

### ISSUE THREAD

**Issue by luisacusick** [AstraZeneca-NGS/VarDictJava#302]
Hi! I am testing vardict on a small data set and am getting an error about uninitialized values. Looking at the source code, I think it is a result of $p not being correctly assigned, but I'm not sure what the cause of that is. 
I am also confused about what the -d option means, can you clarify? 

Here is my command: 

 `vardict -U -G /pylon5/eb5phrp/luc32/Data/toyData/vardictResults -f .05 -N HM038 -b /pylon5/eb5phrp/luc32/Data/toyData/aln/toyAlnRGSort.bam -d '\t' -c 1 -S 2 -E 3 -g 4 /pylon5/eb5phrp/luc32/Data/toyData/toy.bed | teststrandbias.R | var2vcf_valid.pl -N HM038 -E > /pylon5/eb5phrp/luc32/Data/toyData/vardictResults`

Here is what my bed file looks like: 
chr1    1       11940   TEST

Thank you!

Luisa

**Comment by PolinaBevad** [comment]
Hi Luisa,
I see that perhaps `-G` option is wrong: there must be a full path to reference file (indexed), like `/pylon5/eb5phrp/luc32/Data/toyData/vardictResults\hgxx.fa` . Please, check it and try to rerun! Also, you have the same in path to output file (`/pylon5/eb5phrp/luc32/Data/toyData/vardictResults`), it must also contain name of file to output results.
`-d` option is used for delimiter of columns in BED file. By default it is `\t` so you can omit this option if your BED file contains tabs between columns.

**Comment by luisacusick** [comment]
Thank you!
