### ISSUE TITLE
Only one variant identified

### ISSUE THREAD

**Issue by luisacusick** [AstraZeneca-NGS/VarDictJava#305]
Hi, 

I simulated a set of reads from a 12,000 bp sequence. The reads have 1,200 variants. When I run vardict on this sample data set, there is only one variant identified. I have tried lowering -f to "0" to see if that changes the outcome, but it does not. 

Do you know what could be causing this limited output? I attached the vcf output file.

Here is the command: 
```
vardict-java -G aln/toyMedTrunRef.fasta -f "0.01" -N hm038 -b aln/toyAlnRGSort.bam -c 1 -S 2 -E 3
-g 4 -U toy.bed | teststrandbias.R | var2vcf_valid.pl -N hm038 -E -f "0.01" > vardictToy.vcf
```
Thank you very much!

Luisa 
[vardictToy.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/4776721/vardictToy.txt)

**Comment by PolinaBevad** [comment]
Hi @luisacusick, 
Sorry that you have the issue!
Could you please show your BED file? Does it overlap all 12000 bp?

**Comment by luisacusick** [comment]
This is what my bed file looks like: 
chr1    1       12000   chr1.1

Thank you!

Luisa

**Comment by PolinaBevad** [comment]
Hi Luisa, Thanks, BED file looks ok.
What happens if you try to rerun VarDict on this set with option `-r 1`? How many reads are supported the variants? By default we output only variants with more then 2 high quality reads.

**Comment by luisacusick** [comment]
Thanks Polina!

I think that the error is actually related to memory allocation on the cluster I'm working on. This is the error I get when I run that command with -r 1: 
slurmstepd: error: Detected 1 oom-kill event(s) in step 9757403.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

Do you know how much memory VarDict normally requires? 

Thank you!

Luisa

**Comment by PolinaBevad** [comment]
Hi Luisa,

Sorry for the late answer!

VarDict works lineary to the length of segments and 12000 bp is quite a small region to fail with out-of-memory. But if you have a very big coverage this may happen. You can try to increase Java memory heap as described here: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Error-java.lang.OutOfMemoryError:-GC-overhead-limit-exceeded 
Default is -Xms8G so you can try to increase it. If it doesn't help I guess you have to deal with memory settings on cluster - perhaps there are memory limitations on jobs. 

Hope this helps!

**Comment by PolinaBevad** [comment]
Hi Luisa, 
I think the issue has been resolved since the issue has not been active for a month. I'll close it, but let us know if you still run into an issue!
Thank you!
