### ISSUE TITLE
-k 0 to turn off local realignment and speed up 

### ISSUE THREAD

**Issue by hongenxu** [AstraZeneca-NGS/VarDictJava#31]
I am working with chicken genomes and there are many contigs cannot placed on the chromosomes. When I used vardict to call SNVs and indels in those contigs, vardict need more time (at least 5 times more than other chromosomes). I have followed GATK best practice to map reads to genome and done indel realignment. My questions are since I already did indel realignment, can I turn off local realignment of vardict (and still have reliable indel calles)? And can turning off local realignment speed up vardict ?

Best, 
Hongen

**Comment by mjafin** [comment]
Hi @hongenxu, thanks for your interest in VarDict. I'd rely on @zhongwulai chiming in here as he wrote VarDict but I would imagine switching off local realignment would speed VarDict up. You could test this with one of your samples yourself obviously. 

Gatk InDel realignment is largely unnecessary and also not recommended to be used with VarDict as it can sometimes produce improper alignments that VarDict chokes on. 

VarDict is primarily aimed at cancer variant calling and if your primary interest is on germline variants, you might want to give e.g. FreeBayes a go. It's one of the best, free germline variant callers out there.

**Comment by zhongwulai** [comment]
Hi @hongenxu, the local realignment shouldn't have significant impact on speed (<10%).  VarDict's local realignment algorithm is different from GATK and is typically still recommended for Illumina.  I would only turn it off for Ion or PacBio.  So I would be surprised if turning off (-k 0) makes 5 times difference.  The running speed is linear to chromosome size and depth of coverage.  Can you check any characteristic of those contigs, e.g. local complexity with abnormal depth?

**Comment by hongenxu** [comment]
@mjafin and @zhongwulai, many  thanks for your help.
@zhongwulai, those contigs are contigs cannot placed on chicken chromosomes, and have much higher repeat content (45% repeat content vs 16% genome-wide average). Can it explain the 5 time difference between turning on and turning off local realignment for those contigs? There seems no big difference when I turn on or off local realignment for other chromosomes (chr1, chr2....).   I'd like to take your suggestion and not disable local realignment.

**Comment by mjafin** [comment]
If they are very high repeat content regions would you consider not calling variants in them? You're likely just getting a lot of noise out

**Comment by hongenxu** [comment]
@mjafin, Thanks for your reply. We just keep calling variants in those contigs the same as we did using other softwares, such as mutect, muse, varscan2. We next use somaticseq to remove false positives.
