### ISSUE TITLE
test and p-value for step iv of vardict workflow

### ISSUE THREAD

**Issue by ALFLAG** [AstraZeneca-NGS/VarDictJava#318]
Hello,

I was not able to find what statistical test and what p-value threshold were used by vardict-java at the "iv Calculate statistics for the variant, filter out some bad ones, if any." part of the vardict workflow.

Could you tell me please ?

Alexandre

**Comment by PolinaBevad** [comment]
Hi Alexandre,

This point not about statistic tests, but about filtering with specific hard filters that are described here: https://github.com/AstraZeneca-NGS/VarDictJava#variant-filtering. It is more related to quality of reads/bases. You can see thresholds as well.

We use Fisher test after these hard filters also, in both simple and paired mode, there are specific R scripts to calculate it based on ref/alt forward and reverse counts (SBF - Strand Bias Fisher) in simple: https://github.com/AstraZeneca-NGS/VarDict/blob/master/teststrandbias.R.  and compare the same for tumor/normal sample in paired mode:  https://github.com/AstraZeneca-NGS/VarDict/blob/master/testsomatic.R
Thresholds are different:
* In simple and paired mode it will set filter "Bias" for sbf >= 0.01: https://github.com/AstraZeneca-NGS/VarDict/blob/master/var2vcf_valid.pl#L170
* In paired mode it will also have few additional thresholds that will add filters for not Strong Somatic variants:
        * "MSI" - in MSI regions pvalue >= 0.0005
        * "MinDepth" or "VarDepth" with value >=0.15
        * "P0.05" or 'P0.01Likely" - this will be listed only with option '-M'
But we won't hard filter any variants here, we only add filters in FILTER field.

**Comment by ALFLAG** [comment]
Hi Polina,

thanks for your reply. That was the conclusion I made after reading and reading the process and the original article.
May I suggest to modify the "iv Calculate statistics for the variant, filter out some bad ones, if any." sentence in the README file by removing the words " calculate statistics" and replacing by something like, "applying define rules in the variant filtering section"?

Because when I read "calculate statistics" I was confused not knowing what test and treshold was used.

Have a nice day!

**Comment by PolinaBevad** [comment]
Of course, fixed! 

I'll close the issue. Let me know if you will have other questions!
