### ISSUE TITLE
Ignoring SAM validation error + memory error 

### ISSUE THREAD

**Issue by mortunco** [AstraZeneca-NGS/VarDictJava#32]
Hi,

I ran VarDictJava with the following code. Since I aimed to call mutations across the genome, I used the hg19_15k_150bpOL_.seg.txt file which I believe contained a regions across the genome with 5k bp intervals. Program had been running almost more than a day( I know that this depends on the hardware) I got an error says about I got out of memory. 

When I got checked the last couple lines, I have seen two error such as MAPQ and that traceback error. 

My questions;

1. Was my command entry right ?
2. How can I tackle this memory problem?
3. Is this about storage or ram ? because I keep all of the information in harddisk and even though I checked its storage it confuses me?
4. My output vcf was only comprised of a vcf header and nothing more.? Is this something expected?

Please help me.

Best,

Tunc

```
Ignoring SAM validation error: ERROR: Record 622, Read name HWI-ST1120:209:D1KP6ACXX:1:2307:10614:18487, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 623, Read name HWI-ST1120:209:D1KP6ACXX:1:1101:13014:47142, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 2, Read name HWI-ST1120:209:D1KP6ACXX:2:1209:16879:99921, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 622, Read name HWI-ST1120:209:D1KP6ACXX:1:2307:10614:18487, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 623, Read name HWI-ST1120:209:D1KP6ACXX:1:1101:13014:47142, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 2, Read name HWI-ST1120:209:D1KP6ACXX:2:1209:16879:99921, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 622, Read name HWI-ST1120:209:D1KP6ACXX:1:2307:10614:18487, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 623, Read name HWI-ST1120:209:D1KP6ACXX:1:1101:13014:47142, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 2, Read name HWI-ST1120:209:D1KP6ACXX:2:1209:16879:99921, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 622, Read name HWI-ST1120:209:D1KP6ACXX:1:2307:10614:18487, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 623, Read name HWI-ST1120:209:D1KP6ACXX:1:1101:13014:47142, MAPQ should be 0 for unmapped read.
WARNING: BAM index file /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam.bai is older than BAM /media/morova/blackhole/normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam
Ignoring SAM validation error: ERROR: Record 2, Read name HWI-ST1120:209:D1KP6ACXX:2:1209:16879:99921, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 3, Read name HWI-ST1120:209:D1KP6ACXX:2:1104:8070:91549, MAPQ should be 0 for unmapped read.

 *** caught illegal operation ***
address 0x7fed45e162fa, cause 'illegal operand'

Traceback:
 1: fisher.test(matrix(c(tref, d[i, 9], rref, d[i, 27]), nrow = 2))
aborting ...
Use of uninitialized value $sample in concatenation (.) or string at /home/morova/VarDict-1.4.4/VarDict/var2vcf_paired.pl line 35.
```

My command line entry.
```
sudo ~/VarDict-1.4.4/bin/VarDict -G reference/Homo_sapiens_assembly19.fasta -f $AF_THR -N tumor_sample -b "tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam|normal/TCGA-CH-5741-10A-01D-1572_130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam" -z 1 -c 1 -S 2 -E 3 -g 4 /home/morova/VarDict-1.4.4/VarDict/human_hg19_5k_150bpOL_seg.txt | /home/morova/VarDict-1.4.4/VarDict/testsomatic.R | /home/morova/VarDict-1.4.4/VarDict/var2vcf_paired.pl -N "tumor/TCGA-CH-5741-01A-11D-1572_130104_SN1120_0209_BD1KP6ACXX_s_1_rg.sorted.bam|normal/TCGA-CH-5741-10A-01D-1572_/home/morova/VarDict-1.4.4/VarDict130104_SN1120_0209_BD1KP6ACXX_s_2_rg.sorted.bam" > vardict_asil.vcf.txt
```

**Comment by mortunco** [comment]
My Specs are
Memory= 7.7 gb ram
Processor= Intel Core i7-5600U CPU@ 2.60 GHz x 4 
Os type 64 bit
Disk 487.3 Gb

**Comment by mjafin** [comment]
Hi @mortunco,
I don't know the exact reason for the failure, but running VarDict in single thread for the whole genome on what I presume to be a desktop computer will take a very, very long time. 

Do you have access to a compute cluster by any chance? VarDict has been incorporated in bcbio (https://github.com/chapmanb/bcbio-nextgen) in a smartly parallel manner, where bcbio takes care of all the parallelisation and can utilise queuing systems like SGE, SLURM and others

**Comment by mortunco** [comment]
@mjafin , I tried to ran the command with an bed file that contains only single interval of 5k bp. It worked fine. 

I will try to run this command with separating my whole genome data to chromosomes. Also referring to that bed file which is located in the verdict, i will perform the same process to the chromosomes of that bed file.

Is there anything That I can do ? 

Vardict output is very important for me.

Thank you very much.

Best.
T.

**Comment by mjafin** [comment]
Parallelisation is very important and you will want to split the regions to multiple vardict runs. As I mentioned, this is easiest done by resorting to a pipeline like bcbio.

**Comment by mortunco** [comment]
Okay. I will try to set up bcbio. Would you please help me out with error at below while I am dealing with bcbio?

Thanks in advance!

Tunc

```
 *** caught illegal operation ***
address 0x7fed45e162fa, cause 'illegal operand'

Traceback:
 1: fisher.test(matrix(c(tref, d[i, 9], rref, d[i, 27]), nrow = 2))
aborting ...
Use of uninitialized value $sample in concatenation (.) or string at /home/morova/VarDict-1.4.4/VarDict/var2vcf_paired.pl line 35.
```

**Comment by mjafin** [comment]
I have never seen this error before but I suspect it has something to do with your machine running out of memory. I would urge you to perform the variant calling on a compute cluster with sufficient memory on the nodes.

**Comment by mortunco** [comment]
Hi,@mjafin;

Thank you for suggesting me bcbio it really illuminated my in terms of its capabilities. I have a question related with using verdict in bcbio. As it is required in vardict, should I specify a bed file? Because I would to call mutations genome wide. I could not find any specific information related regions. There is only a single point which I can define regions with a bed file. [here](https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-configuration). Is this information related to vardict ?

If it is related with verdict. May I use 'hg19_5k_150bpOL_seg.txt.gz'. Also could you guide me to create this type of genome wide bed for GRCHh37 genome. 

Thank you again for helping me out.

Best,

Tunc.

**Comment by mortunco** [comment]
Dear @mjafin;

I would like to know if there is an update in this topic.

Thanks in advance,

Tunc.

**Comment by mjafin** [comment]
Hi @mortunco, apologies for the delay. If you specify no `variant_regions` in bcbio then it estimates callable regions based on depth and uses those as the bed file (of sorts). This works for whole genomes.

**Comment by mortunco** [comment]
Dear @mjafin;
THIS GAVE ME A BIG RELIEF. As you may know these regions were the biggest problems while running it locally. 

Thank you very much for your response.

Best,

Tunc.
