### ISSUE TITLE
A question about the -I option

### ISSUE THREAD

**Issue by FrankFeng** [AstraZeneca-NGS/VarDictJava#327]
According to the documentation:

**-I INT** `The indel size. Default: 50bp.`

If I want to call INDEL larger than 50bp, with setting `--nosv` (no structural variant calling), do I have to set the `-I` parameter to a larger value (e.g. 1000)?

**Comment by PolinaBevad** [comment]
Hi @FrankFeng,
You need to increase `-I` option threshold, and also `-L` option threshold, as otherwise long Indels (>500bp) will be recognized as SVs and can be filtered out.

**Comment by FrankFeng** [comment]
Thanks @PolinaBevad  !
