### ISSUE TITLE
AF vs HIAF

### ISSUE THREAD

**Issue by jsha129** [AstraZeneca-NGS/VarDictJava#339]
Dear VarDict Team,
Thanks for developing the algorithm. VarDictJava is my 'go-to' variant caller now :) 
This is a question, not an issue. We saw differences in AF versus HIAF for some variants. The help option in the tool says HIAF is AF using high-quality bases. Could you please explain what it means by 'high quality bases' and calculations that go in determining HIAF?
Thanks!
Jay

**Comment by PolinaBevad** [comment]
Hi Jay,

Thank you for using VarDict!

HIAF depends on threshold of good quality, the one that can be set with option `-q` (base quality shred score, default 22.5). So if the base has good quality (more than this threshold) and has variant - this will be counted as high quality read, i.e. `hicnt`. We also collect high coverage (just all reads cover the position, but using the same threshold) as `hicov` and then calculate `hiaf` as `hicnt`/`hicov`. 
Hope this helps!

**Comment by jsha129** [comment]
Dear Polina,
Thanks for providing further explanation and a quick response! It definitely helps.
Jay
