### ISSUE TITLE
Reference forward count column in variant on position: 53242123 A->AC was negative, adjusted to zero.

### ISSUE THREAD

**Issue by ds21uab** [AstraZeneca-NGS/VarDictJava#351]
Hi @PolinaBevad 
I have recently encountered this error while running the variant calling on one of the BAM files by VarDictJava. What does it mean? Should I ignore the warning and move ahead with the analysis?

**Comment by PolinaBevad** [comment]
Hi @ds21uab ,
Sorry that didn't answer before - yes, this is a technical warning in realignment step, you can ignore it!
Thank you!
