### ISSUE TITLE
Variant with quality only gets called when decreasing the minimum phred score

### ISSUE THREAD

**Issue by rollf** [AstraZeneca-NGS/VarDictJava#357]
Hi,

I'm having an issue calling a specific variant with VarDict 1.8.2. Please find the attached [rs2819561-not-called.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/8402035/rs2819561-not-called.tar.gz) archive that can be used to reproduce the issue (given a path to your `GRCh37.fa` as well as the `VarDict` command available). The sample bam file contains the variant [rs2819561](https://www.ncbi.nlm.nih.gov/snp/rs2819561#variant_details) (NC_000003.11:g.4403767A>G in GRCh37.p13).

![image](https://user-images.githubusercontent.com/58295931/161372247-17e8816f-185e-4875-88b5-986a9d4539a3.png)

It does not get called by default. The read quality is good, the mapping quality at the given base is good, too. For me, there is no obvious reason why this should not get called.

```bash
cat run.sh
...
VarDict -G "$REF_GENOME" -N rs2819561 -b $BAM $BED -c 1 -S 2 -E 3 -g 4 --header "$@" | cut -f 1,3-7,19-23
...

./run.sh
Sample  Chr     Start   End     Ref     Alt     QMean   QStd    MQ      Sig_Noise       HiAF # no variant gets called
```

Decreasing the minimum phred score base quality to 14 yields the variant

```bash
./run.sh -q 14
Sample  Chr     Start   End     Ref     Alt     QMean   QStd    MQ      Sig_Noise       HiAF
rs2819561       3       4403767 4403767 A       G       26.4    1       59.8    364.000 0.5215 # <-- that's the one I'm waiting for
rs2819561       3       4403767 4403767 A       C       14.0    0       56.0    10.000  0.0143
rs2819561       3       4403767 4403767 A       T       14.0    0       59.4    10.000  0.0143
rs2819561       3       4403766 4403766 G       C       14.0    0       60.0    10.000  0.0143
```

Unfortunately, it also calls 3 other (false positive) variants. Also, the first variant gets QMean = 26.4 so I would have assumed it should get called by default (given `-q` = 22.5 by default). Do you see any way for me to call this variant but not the others?

Thanks in advance!

**Comment by rollf** [comment]
Hi,

would you have time to have a look into this?

Thanks.

**Comment by tegent-gift** [comment]
I have the same problem. Have you solved it?

**Comment by rollf** [comment]
Thanks @PolinaBevad for your reply including the hints. Your are right, running with `-o 1.3` (in my particular case) yields the variant without the FP ones.
