### ISSUE TITLE
Is it possible to filter orientation bias?

### ISSUE THREAD

**Issue by kimjr89** [AstraZeneca-NGS/VarDictJava#361]
![image](https://user-images.githubusercontent.com/42312259/165868581-b8695ef4-b9fc-48ee-a3e5-1dd87b6a7796.png)

VCF files generated by VarDict don't seem to have an orientation bias(different from strand bias) filter which is supported by Mutect2.

Since I'm working on a project dealing with very low-frequency alleles, false-positive from oxoG should be filtered. 

Does VarDict support an orientation bias filter?
Or are there any other methods like piping other tools to enable the filtering?

Thanks.

**Comment by PolinaBevad** [comment]
Hi @kimjr89, Sorry, we do not support orientation bias filtering at the moment. 
I know that GATK has some additional tools on filtering Orientation Bias on top of Mutect2 calls, maybe you can check if this will work for VarDict results as well?
