### ISSUE TITLE
Allele frequency parameter in VarDictJava

### ISSUE THREAD

**Issue by ds21uab** [AstraZeneca-NGS/VarDictJava#366]
Hi,

I am trying to understand the -f parameter in VarDictJava. As it states it is the allele frequency (AF). So I was wondering which population database for example GnomAD VarDict is using to get the AF values? Or -f is the variant allele fraction?

**Comment by PolinaBevad** [comment]
Hi @ds21uab,
It is variant allele fraction threshold (calculated as VD/DP), you can see the options here: https://github.com/AstraZeneca-NGS/VarDictJava#vardictjava-options . So if the variant AF exceeds this threshold, we will keep it in the filtered results in VCF.
We do not use gnomAD in VarDict, but you can annotate VCF using SnpEff/vcfanno to get gnomAD AF.
