### ISSUE TITLE
Avoid duplicated `-Xmx` options for shell wrapper

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#4]
When running with the VarDict shell script and passing in options via `VAR_DICT_OPTS` the Java memory specification ends up on the commandline twice since it is initially set in `DEFAULT_JVM_OPTS`. Apparently the behavior of this is that the later specification will take precedence, although it's not explicitly defined so is the potential source of hard to debug issues later:

http://stackoverflow.com/questions/2740725/duplicated-java-runtime-options-what-is-the-order-of-preference

I couldn't find the shell script in the distribution to submit a proper patch but a quick fix is to skip the default arguments if `VAR_DICT_OPTS` gets passed:

```
if [ -n "$VAR_DICT_OPTS" ] ; then
	DEFAULT_JVM_OPTS=''
else
	DEFAULT_JVM_OPTS='"-Xmx512m"'
fi
```
Would it be possible to include this in the shell script? Thanks much.

**Comment by chapmanb** [comment]
Thanks so much for all the fixes in 1.2.2. It looks great.

**Comment by clintval** [comment]
If anyone else hit this, the behavior definitely still occurs when setting `$JAVA_OPTS` in the environment that calls the helper script:

```bash
❯ JAVA_OPTS=-Xmx2g VarDictJava/build/install/VarDict/bin/VarDict
```

Calls:

```bash
exec java -Xms768m -Xmx8g -Xmx2g -classpath /pipeline/packages/VarDictJava/build/install/VarDict/lib/VarDict-1.5.1.jar:/pipeline/packages/VarDictJava/build/install/VarDict/lib/commons-cli-1.2.jar:/pipeline/packages/VarDictJava/build/install/VarDict/lib/jregex-1.2_01.jar:/pipeline/packages/VarDictJava/build/install/VarDict/lib/htsjdk-2.8.0.jar com.astrazeneca.vardict.Main
```

**Comment by clintval** [comment]
@pcingola or @PolinaBevad, do you know how the helper script is created?

I am willing to submit a patch to guard against duplication of any of the default arguments when using `JAVA_OPTS`.

Currently the default options are one of `-Xms` and another for `-Xmx`.

**Comment by PolinaBevad** [comment]
@clintval, hello!

These options are set through build gradle script: https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/build.gradle#L20

The helper script is also updated with additional check on `VAR_DICT_OPTS` (what Brad wrote about): https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/build.gradle#L41 . 
I guess something like `|| [ -n "\$JAVA_OPTS" ]` can be added in condition here and it will be work. 
If you check this and create a PR, it will be great!
