### ISSUE TITLE
build folder not showing up after running ./gradlew installApp clean

### ISSUE THREAD

**Issue by alexanderwhatley** [AstraZeneca-NGS/VarDictJava#41]
After running the "./gradlew installApp clean" command, I do not see the build folder anywhere. Gradle reports a successful build however. I suspected the problem could be due to permissions, so I ran chmod 760 * in the directory the vardict folder is in to no avail. This problem occurs on both my Windows PC and in a server running Centos 6.5. Do you know what the problem could be? Thanks.

**Comment by mjafin** [comment]
@alexanderwhatley if you want to build VarDictJava yourself @jabbarish might be able to give you pointers to the right direction. May I ask if you have found bugs in the code you are trying to fix? We appreciate pull requests if you want to contribute your changes back.

However we also ship binary releases, which you can find here https://github.com/AstraZeneca-NGS/VarDictJava/releases

**Comment by aewhatley** [comment]
I found the issue - if the necessary packages have already been installed in the system by gradle, the correct command to run is actually ./gradlew installApp (wthout the clean). Perhaps you should make a note of that in the documentation?

**Comment by jabbarish** [comment]
@alexanderwhatley actually, the documentation contains the following instruction:

> To build the project, in the root folder of the project, run the following command:
./gradlew clean installApp

Note that you have placed 'clean' after 'installApp', intstead of before it.  That's why you couldn't see the build folder: it was cleaned right after creation.

**Comment by ndaniel** [comment]
For me 
```
./gradlew clean installApp
```
does not work.

But this works:
```
./gradlew installApp
```

**Comment by mjafin** [comment]
Thanks for chiming in @ndaniel. @jabbarish if you think this would be good to be added to the docs please do.

@aewhatley I'll close the ticket, let us know and reopen if you see further issues.
