### ISSUE TITLE
Issues with DNP, MNP and Complex events

### ISSUE THREAD

**Issue by rhshah** [AstraZeneca-NGS/VarDictJava#44]
Hello VarDict Team,

In our testing of VarDict we noticed some issues when an event is called as a DNP, MNP or a complex event that are germline 

For mock example in DNP:
if there is germline:
chr1:10 = A
chr1:11 = T
The variant called is 
AT > CG 
VarDict properly assign DP,VD to DNP for both case and control as well as tagging it as germline.

But then VarDict also call's
chr1:11 = T
The variant called is
T>G 
VarDict assigns this variant with very little read support in VD in case and no support in control. It is also tagged as somatic. Any reason why this event is still called separately. 

This happens in multiple cases of DNP, MNP and complex events that are germline.

Let me know if I am not clear.

Attached is the real example for DNP:

![image](https://cloud.githubusercontent.com/assets/1289674/16088244/3c04278e-32f4-11e6-95ed-3ac73c03a32f.png)

![image](https://cloud.githubusercontent.com/assets/1289674/16088257/4888d6c6-32f4-11e6-921f-5eb7b8074439.png)

Best,
Ronak

**Comment by mjafin** [comment]
@zhongwulai do you have any comments around this?

**Comment by zhongwulai** [comment]
Speaking from my experience, it's likely T>G is due to the end of reads and should be typically filtered out.  My later implementation would rescue them as MNV.  So would be interesting to know what's the PMEAN value for this variant.  Lower than 5 is a sign of false positive.

**Comment by microtsiu** [comment]
I has a similar question, see the picture below,
![image](https://cloud.githubusercontent.com/assets/3345798/20593399/336bf20c-b26d-11e6-9ff3-f940cfc6cad8.png)

my expected result is G>A, but VarDict called is TG>CA,  and frequence is 2e-04. 

@zhongwulai Could you tell me how to solve it?

best,
mico

**Comment by mjafin** [comment]
Sorry about not addressing this sooner, but could you try the `-A` option and see if you get the alternative alleles?

**Comment by PolinaBevad** [comment]
@rhshah, hello!
We will close this issue because there were a lot of changes in VarDict since 2016. Realignment processing and MNV finding were also changed. If you still facing the same problem, please re-open this issue.
Thank you for the participation!
