### ISSUE TITLE
Vardict detecting no somatic mutations in DNA panel using proxy normal

### ISSUE THREAD

**Issue by smboyle** [AstraZeneca-NGS/VarDictJava#45]
Hello, I am intersted in applying Vardict to identify somatic indels using a broad panel with a  proxy normal sample.  We know this sample has true somatic indels, however, when we run the suggested pipeline porting in a proxy normal sample no indels are listed as "strongly somatic" or "likely somatic".  Before we look into this deeper on our end, I wanted to ask whether this is expected behavior when using a proxy normal with your pipeline.  There may be issues with having a higher density of idels detected when using a proxy normal as private mutations may come up as somatic and I was wondering whether you expect something like this to cause true somatic indels to loose statistical significance.  We are currently using your tool for exome paired tumor-normal analysis and wanted to apply it to tumor-only panel applications as well.  Thanks in advance, Sean

**Comment by mjafin** [comment]
Hi @smboyle, thanks for bringing this up. Regarding statistical significance, the p-values for variants are not corrected using Bonferroni/Benjamini-Hochberg or any other multiple correction practice. In other words, the statistical significance of one indel isn't affected by that of another. @zhongwulai can correct me if I'm wrong. 

Just to make sure I'm getting this right, your proxy normal sample is a bam file that you've combined from (relatively) normal samples? Or are you talking about the panel-of-normals vcf file that The Broad published with MuTect? With original MuTect it was SNPs only and I haven't been following the development of MuTect2 closely enough to know if they have a panel-of-normal for indels too.

**Comment by smboyle** [comment]
Hello @mjafin: Yes, the proxy normal samples is a single normal sample which is unrelated to the tumor sample we are analyzing.  We are currently working today to convert this single normal sample into a combined set of proxy normal samples to see if the significance improves with depth.  We used this proxy bam in your pipeline, inputting it as if it was a paired normal bam sample.   I will let you know if this improves accuracy.  Vardict is currently giving the following classification to what we feel are the tumor only panel variants "SampleSpecific: detected in tumor sample, but no coverage in germline sample (it’s more technical than biological, as it’s unlikely a tumor sample can gain a piece of sequence in reference that germline sample lacks)."  We need to look into the examples, but I believe we have some however insufficient, coverage at these sites in the normal.
Thanks,
Sean

**Comment by smboyle** [comment]
@mjafin : This issue was caused from the bam missing flags which were required for Vardict to function correctly.  We realigned the proxy reads using BWA and the analysis worked correctly.  You can close this ticket!

Thanks,
Sean

**Comment by mjafin** [comment]
I like tickets that fix themselves!
