### ISSUE TITLE
Internal sentinel '^' character included with alternative allele in output

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#5]
Viktor and Zaal;
Thanks again for all the fixes in the latest release. I've been testing on a larger whole genome dataset and ran into an additional problem where alternative alleles remain prefixed with a `^`. Here is a minimal example with a shell script and subset BAM files:

https://s3.amazonaws.com/chapmanb/az/vardict_altallele_debug.tar.gz

The call at 103577362 has the extra carrot when called with VarDictJava but not in VarDict:

```
test-vardict-java.tsv:
syn3-tumor        1       1       103577362       103577364       GAT     ^NTTATAGATAG    14      22      10      0       2       G/-3iNTTATAGATAG        0.143   2;0     16.5    1       29.6    1       54.5    4.0000.154      0.071   0.5     8       0       3       5       0       0       G/G     0       2;0     20.0    1       34.1    158.0   16.000  1.000   0       0.5     0       5.000   1       TGTTTCATCCCCCTATTTTT    ATAGATAGATAGATAGATAG    1:103571062-103580719   StrongSomatic   Complex
test-vardict.tsv:
syn3-tumor     1       1       103577362       103577364       GAT     NTTATAGATAG     14      2       210     0       2       G/-3iNTTATAGATAG        0.143   2;0     16.5    1       29.6    1       54.5    4.000   0.1540.071      0.5     8       0       3       5       0       0       G/G     0       2;0     20.0    1       34.1    1       58.0    16.000  1.000   0       0.5     0       5.000   1       TGTTTCATCCCCCTATTTTT    ATAGATAGATAGATAGATAG    1:103571062-103580719   StrongSomatic   Complex
```
This will cause downstream tools to fail on the output since it's not a valid character. I dug into the code a bit and it looks like it's used as a sentinel internally but does not get removed in this case.

Please let me know if any other information would be helpful to debug this.

**Comment by chapmanb** [comment]
If this helps debugging, I found a couple of additional cases with this problem and all had an N following the carrot: '^N'. This happened for Ns both at the start and the middle of alternative alleles. Hope this helps narrow things down.

**Comment by jabbarish** [comment]
thank you

**Comment by zhongwulai** [comment]
Given Brad's description, the problem should be VarDict.java, line 2973, where it should be:

mtch = CARET_ATGNC.match(vn);

CARET_ATGNC should be used, not CARET_ATGC.

**Comment by chapmanb** [comment]
Thanks much for the fix. I re-ran a whole genome validation of VarDictJava with the latest release (1.2.4) and all looks great. It runs without any problems, the accuracy is comparable to VarDict and it's much faster:

http://imgur.com/a/cCxcQ

Thanks for all the work on this.
