### ISSUE TITLE
RNA-seq Variant Indel/SNV calling

### ISSUE THREAD

**Issue by davidroberson** [AstraZeneca-NGS/VarDictJava#53]
Hello we would like to use your tool on a large set of RNA WTx samples (deep coverage) that have been aligned via STAR.  Are there any notes on best practices for parameters to tweak for RNA-Seq data?  So far we are thinking of "turning off" strand bias filter and reducing allele freq to 1%. 

Thank you

Dave

**Comment by davidroberson** [comment]
How can we effectively turn strand bias off.  Is it simply setting strand bias minimum read number very high?

Thanks,
Dave

**Comment by mjafin** [comment]
Hi Dave,
I'd refer to @zhongwulai about switching off strand bias filtering. 

What sort of data is it that you have? Cancer? At 1% you'll get a lot of noise but if you're happy filtering downstream there's nothing stopping you from using 1%. 

We've been toying with all sorts of ideas around how to dynamically downsample regions of super high expression, how to filter or mark RNA-editing sites etc. but have nothing formal in place at the moment unfortunately.

**Comment by jasper1918** [comment]
I found this thread while searching for an optimal parameter set for RNA-Seq variant calling with polyA capture.  @davidroberson - Were you able to find a good set of working  parameters? or did turning off strand-bias help?

**Comment by PolinaBevad** [comment]
@davidroberson, hello!
Is this issue is relevant to you? Do you still need the option to switch strand-bias filtering off?

**Comment by PolinaBevad** [comment]
@davidroberson, hello!
Because there was no answer from you since the last comment, I will close the issue. Please, re-open it, if needed.
