### ISSUE TITLE
3 Column Bed file

### ISSUE THREAD

**Issue by kbthomas59** [AstraZeneca-NGS/VarDictJava#54]
Java VarDict gives an immediate java.lang.ArrayIndexOutOfBoundsException when I try a 3-column bed file. The bed file looks like (tab delimited)
chr1 65509 65625
chr1 65831 65973
chr1 69481 69600
chr1 721381 721519
chr1 721530 721806
...

Information from an individual line works with the -R option.
An 8-column bed file does work with columns 4,5 and 6 empty like
chr1 65509 65625 65509 65625
...

Does this suggest that "amplicon mode" is always on? I have tried the -z option and that hasn't changed this behavior. Where have I gone wrong?

**Comment by mjafin** [comment]
Hi @kbthomas59,
Thanks for your interest in VarDict and sorry about the problems you're seeing. Amplicon mode is triggered when VarDict detects the seventh and eighth columns in a bed file but care needs to be taken not to enable amplicon awareness in non-PCR-amplicon data. 

Have you checked that there are no empty lines in the bed file? If you send a small example of where you see the failure that'd be helpful. 

You could also try the following: for each line in the bed file add a dummy fourth (tab delimited) column with random characters in it (gene names or such) and let me know if you still get the error.

**Comment by kbthomas59** [comment]
[chr1Test.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/522187/chr1Test.txt)

[Uploading errorOut.txt…]()
[Uploading errorOut.txt…]()
[Uploading errorOut.txt…]()

**Comment by kbthomas59** [comment]
[Uploading errorOut.txt…]()

**Comment by kbthomas59** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at com.astrazeneca.vardict.VarDict.toRegions(VarDict.java:118)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:64)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)

That's the entire error output  from running with the attached bedfile.

[chr1Test.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/522455/chr1Test.txt)

**Comment by mjafin** [comment]
Hi @kbthomas59,
The bed file looks OK to me but can you still try adding a fourth column and see if you get the same error?

**Comment by kbthomas59** [comment]
Adding a fourth column, as in the attached bed file, gives a different
error:

Exception in thread "main" java.lang.NumberFormatException: For input
string: "ABC"
        at
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at com.astrazeneca.vardict.Utils.toInt(Utils.java:75)
        at com.astrazeneca.vardict.VarDict.toRegions(VarDict.java:126)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:64)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)

The objection here seems to be to non-numeric data in the fourth column.


Brad Thomas

**Comment by mjafin** [comment]
Could be there is an issue somewhere else. Could you paste the complete vardict-call here and possibly a slice of the bam file? Are you using bwa for alignment?

**Comment by kbthomas59** [comment]
BWA is used here.  Are there problems with it?

Brad Thomas

**Comment by mjafin** [comment]
Absolutely no problem using bwa-mem, that's our preferred aligner.

**Comment by kbthomas59** [comment]
Hello,

Can you recommend a tool for making small bam slices?

Also, today as I was trying various things, I found that if I use bamtools
split to divide my bam file into smaller bam files by chromosome, my exome
bed file does work now with VarDictJava, but only if I set that bed file up
as an 8-column bed file (I keep columns 4 - 6 empty and give 7 and 8 the
same entries as 1 and 2).

Brad Thomas

**Comment by mjafin** [comment]
@kbthomas59 
1. Could you send us the command line you used to call vardict on the bam and bed file first so I can check it's OK?
2. You can slice the bam using `samtools view -b -U my.bed my.bam > my_sub.bam` where `my.bed` has a few of the above bed lines
3. It's a very bad idea to use VarDict in amplicon mode if your data is from exome or other hybrid capture (or any non-PCR-amplicon panel in fact)

**Comment by kbthomas59** [comment]
Along with a bam file slice (and its index) I've attached an 8-column bed
file that works with that slice and a 3 column bed file that does not.

Here is the command line I've used:
/home/VarDictMaster/VarDictJava-master/build/install/VarDict/bin/VarDict -b
bamSlice.bam -G ../hg19-Reference.fa headTest.bed

The error with the attached 3-column bed file is:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
at com.astrazeneca.vardict.VarDict.toRegions(VarDict.java:118)
at com.astrazeneca.vardict.VarDict.start(VarDict.java:64)
at com.astrazeneca.vardict.Main.run(Main.java:134)
at com.astrazeneca.vardict.Main.main(Main.java:25)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
at com.astrazeneca.vardict.VarDict.toRegions(VarDict.java:118)
at com.astrazeneca.vardict.VarDict.start(VarDict.java:64)
at com.astrazeneca.vardict.Main.run(Main.java:134)
at com.astrazeneca.vardict.Main.main(Main.java:25)


java is (Oracle) jdk1.7.0_79

Thanks for your help,
Brad Thomas

**Comment by mjafin** [comment]
Hi Brad,
Unfortunately the attachment did not reach Github but could you try amending your vardict call to look like this:
```
/home/VarDictMaster/VarDictJava-master/build/install/VarDict/bin/VarDict -f 0.05 -N "my_sample" -b bamSlice.bam -c 1 -S 2 -E 3 -g 4 -G ../hg19-Reference.fa headTest.bed
```

**Comment by kbthomas59** [comment]
OK, seems to work with 3-column bed files now.  What are the important
flags I omitted?


Brad Thomas

**Comment by mjafin** [comment]
Excellent, glad to hear that. The flags for using bed files would be
```
-c 1 -S 2 -E 3 -g 4
```
The `-f` option further controls the allele frequency cutoff and for tumour FFPE you may want to set it to 5% - 10%, lower for ctDNA. 

Have you considered using bcbio for all of the parallelisation, alignment, variant calling, annotation and QC? VarDict is implemented therein https://github.com/chapmanb/bcbio-nextgen

**Comment by kbthomas59** [comment]
Yes, we do use bcbio.  I needed an isolated instance of VarDictJava running
for another purpose.

Thank you for all of your help.

Brad Thomas

**Comment by mjafin** [comment]
Sounds great. You can also extract bcbio's vardict calls from the `bcbio-nextgen-commands.log` and use those as a starting point.
