### ISSUE TITLE
Amplicon mode output too many columns

### ISSUE THREAD

**Issue by reddpoint** [AstraZeneca-NGS/VarDictJava#55]
Hello

I am trying to use VarDictJava in amplicon mode but when I pipe the results into TestStrandBias.R I get an error that the input is incorrect.  It looks like teststrandbias expects a 38 column file from VarDict but I am getting a 40 column table.  Any thoughts?  

Here is my command
VarDict -D -G /fdb/GATK_resource_bundle/b37/human_g1k_v37.fasta -f $AF_THR  -a 10:0.95         -N "NY152" -b mapping/NY152.merged.bam -C -c 1 -S 2 -E 3 -g 4  test.interval.bed

**Comment by mjafin** [comment]
Hi @reddpoint, thanks for your interest in VarDict and sorry about the problems. Just out of interest, have you tried without the `-D` flag? Further, you don't need to explicitly specify the `-a` flag as VarDict will know when to use amplicon calling based on the bed file format. 

Additionally, can you paste a few lines from your bed file here to help with debugging?

**Comment by reddpoint** [comment]
Yep that fixed it.  Taking out the -D flag produced the correct amount of columns.

**Comment by mjafin** [comment]
Great, let us know if you have any other questions
