### ISSUE TITLE
VarDict Amplicon Mode throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wendymclee3** [AstraZeneca-NGS/VarDictJava#56]
I previously ran successfully using VarDict with the 6-column bed file without the amplicon mode. I then added the 7th and 8th column to the bed file and re-run the same sample using the amplicon mode, but failed. Here it is the error:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at htsjdk.samtools.Cigar.getCigarElement(Cigar.java:57)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1498)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2556)
	at com.astrazeneca.vardict.VarDict.ampVardictNotParallel(VarDict.java:5518)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:60)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)

Here is how my 8-column bed file looks like:

chr1	4367240	4367362	rs1490413	1	+	4367262	4367342
chr1	45973896	45974012	r2275276	1	+	45973918	45973991
chr1	67861470	67861609	rs2229546	1	+	67861490	67861589
chr1	89388893	89389015	rs7532151	1	+	89388922	89388987
chr1	107984045	107984164	rs776284	1	+	107984068	107984143
chr1	167849380	167849521	rs203849	1	+	167849401	167849500
chr1	179520426	179520568	rs1410592	1	+	179520447	179520548
chr1	209811837	209811940	rs2076356	1	+	209811857	209811920

**Comment by mjafin** [comment]
Hi @wendymclee3, thanks for trying VarDict and sorry about the error. 
Just a quick check, have you verified that for each bed line col3<col7<col8<col4 ?

Other than that, could you let us know which aligner you used (if not bwa-mem) and if you did any explicit indel-realignment?

If you could send us a reproducible example including a small bam and bed file we can take a further look.

**Comment by wendymclee3** [comment]
Hi @mjafin. Thanks for the quick response. In the VarDict example, col3 is not less than col7. Here is the VarDict example bed: 

chr1    46713345        46713502        RAD54L  0       .       46713363        46713481
chr1    46713418        46713578        RAD54L  0       .       46713435        46713561

We did use bwa-mem and we didn't do any indel-realignment. I will email you the bam and bed files. Thanks for your help.

**Comment by wendymclee3** [comment]
Or what is the best way to share the bam and bed files with you?

**Comment by wendymclee3** [comment]
Attached are the down-sampled bam file and the bed file

[TroubleshootVarDictAmpliconMode.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/579120/TroubleshootVarDictAmpliconMode.zip)

**Comment by wendymclee3** [comment]
Here are the bed and bam files: [Troubleshoot_VarDict_bam_and_bed.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/579135/Troubleshoot_VarDict_bam_and_bed.zip)

**Comment by mjafin** [comment]
Sorry @wendymclee3 I got my columns mixed up, this is what I meant:
col2<col7<col8<col3
Does this hold for your bed file?

@malperovich @ZLyanov do you guys have any cycles for checking out the bam and bed file error?

**Comment by wendymclee3** [comment]
I checked the 4 columns, and they agree with col2<col7<col8<col3 rule

**Comment by mjafin** [comment]
Thanks, let's wait for Zaal and Mikhail to get back to us. 

Out of curiosity is your data from a Qiagen or similar PCR amplicon panel?

**Comment by wendymclee3** [comment]
Our data is from an in-house designed amplicon panel.

**Comment by ZLyanov** [comment]
@zhongwulai 
Dear Zhongwu,
It seems that the fix of issue https://github.com/AstraZeneca-NGS/VarDictJava/issues/51 by commenting out line 1462 in VarDict.java is the of this issue. The reason is that unmapped reads are not skipped now, and java version fails when it tries to work with cigar "*" (for example, line 1498). Can unmapped reads just be skipped?

**Comment by wendymclee3** [comment]
Thanks @zhongwulai. It works when I filtered out the unmapped reads.

**Comment by zhongwulai** [comment]
Yes, mapped reads should be skipped.

**Comment by zstudent** [comment]
@zhongwulai ok, thank you! We will update the java version soon.

**Comment by ZLyanov** [comment]
@zhongwulai ok, thank you! We will update the java version soon.
