### ISSUE TITLE
MNP or Complex events

### ISSUE THREAD

**Issue by microtsiu** [AstraZeneca-NGS/VarDictJava#57]
Hello VarDict Team,

In our testing of VarDict with low frequence variations, it is seemed has some bugs, see the picture. my expected result is G>A, but VarDict called is TG>CA, and frequence is 2e-04.
![image](https://cloud.githubusercontent.com/assets/3345798/20820385/e1359128-b875-11e6-9631-610f7638413d.png)

best,
mico

**Comment by PolinaBevad** [comment]
@microtsiu, hello!
We will close this issue because there were a lot of changes in VarDict since 2016. MNV finding was also changed. If you still facing the same problem, please re-open this issue.
Thank you for the participation!
