### ISSUE TITLE
VarDict resources characteristics on paired WGS data

### ISSUE THREAD

**Issue by schelhorn** [AstraZeneca-NGS/VarDictJava#58]
We are currently looking into using VarDict in paired WGS mode and were wondering what the sweet spot(s) in terms of memory and CPU requirements on a single node versus a split approach over multiple nodes (using the bcbio approach) are. 

More specifically, 

* what is the approximate maximum memory demand per single process for paired 50x WGS libraries, and how does it scale with the number of threads of that process? 
* approximately how many threads can reasonably be driven by a single process before it makes more sense to start another (multithreaded) process on another chunk of the same input alignment instead?
* last, are these numbers approximately equivalent for paired WES libraries, where a BED file of enriched regions can be specified to VarDict?

Thanks!

**Comment by mjafin** [comment]
Hi @schelhorn, thanks for opening the discussion around scaling. We don't internally use (and neither does bcbio) the multithread features of VarDictJava itself but parallelise by splitting to regions as you know, so each job should be using roughly 100% of a thread. Thus I'm probably not best placed to answer your questions. That said..
- Memory requirements for VarDict should scale with the width of the region and not depth. 
- I'm typically seeing VarDictJava  processes using up to 1-3GB RAM

Further, EPAM just released VarDictJava 1.4.7 that greatly reduces the number of (sub?) threads and speeds up VarDict further. 

Would be great hear your experiences and what you're seeing

**Comment by ATpoint** [comment]
Hello, we are currently starting to use VarDictJava 1.5.0 for our WGS data. Could you be so kind and share your experiences with it and give recommendations about altering the default settings. I noticed some discussion about the filtering (#35 in VarDict) to be used. For me as a user, is there anything you can recommend which is not already stated in the documentation by now?

-Thanks!

**Comment by mjafin** [comment]
Hi @ATpoint, we use VarDict in bcbio with pretty default settings, see the integration code here https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/vardict.py 

Hope this helps some. Really depends on depth, T/N or tumour-only etc.

**Comment by schelhorn** [comment]
Defaults are fine; you can play around with the number of cores since it scales linearly at least until 4 cores or so in our setting. Perhaps that makes sense if IO is an issue. Of course, in the end that only results in a different packaging of the jobs. But that really depends on your specific setup.

**Comment by PolinaBevad** [comment]
@schelhorn, hello!
I will close the issue, as all questions have been resolved. You can always reopen it if you have new questions on this topic!
Thanks a lot for the discussion!
