### ISSUE TITLE
Handling of overlapping reads from short inserts?

### ISSUE THREAD

**Issue by tfenne** [AstraZeneca-NGS/VarDictJava#60]
I'm curious what you recommend for sequencing data that has some inserts that are shorter than 2x the read length such that some genomic bases are read in both R1 and R2?

I believe I am seeing cases in the data where VarDictJava is counting both reads from the pair for supporting evidence for a variant, and I am getting back inflated AFs and ADs.  Do you recommend that users trim overlapping reads before calling through Vardict?  Thanks!

**Comment by mjafin** [comment]
@tfenne thanks for raising this for discussion. Are you saying that you have very large variability in your fragment sizes and the very short fragments are more prevalent in the clones/cells with the variants, thus biasing the AF/AD values? Like in cfDNA the tumour DNA fragments would be around 170bp but the germline DNA might be longer fragments

@zhongwulai have you got any ideas?

**Comment by tfenne** [comment]
Hi @mjafin ... the problem is more that I'm doing some work where I'm really trying to push the limit of detection in terms of minor allele frequency, seeing how low we can go and where the errors come from at very low frequency, and how best to squash them.  So it's not so much that the tumor DNA, or the mutated inserts are preferentially short, it more of a sampling problem.

E.g. if a random 5-10% of my library has inserts << 2xread_length, then for high MAF variants that's fine as it'll come out in the wash.  But where I'm looking for mutations supported by, e.g., 2, 3 or 4 reads I run into sampling problems.  Somewhat frequently I'm seeing what looks like a library prep artifact (an error introduced in library prep, so it's present in the DNA being sequenced in both reads) in the overlap section of 1 or 2 templates.  And instead of counting that as 1 or 2 observations, it's getting counted as 2 or 4, and triggering calling.

**Comment by mjafin** [comment]
Thanks for the explanation. @zhongwulai knows the internal workings of VarDict more than anyone else so would be best placed to answer this one.

**Comment by dh10** [comment]
I have encountered @mjafin 's point regarding two libraries with different fragment sizes. Merging or trimming overlaps are one solution obviously (and has its own issues). However, it may also be of value to know the count of ALT and REF alleles arising from overlaps possibly as a format field and let the user filter and adjust if desired. One can also envision a overlap-adjusted VAF in analogy to ADJAF. The presence of overlap may lend more confidence to some low frequency mutations as artifacts are sometimes present on R2 but not R1 (or vice versa) in the overlap. Not sure if VarDict can easily parse this out however.  

ROVER does this to some extent: http://scfbm.biomedcentral.com/articles/10.1186/1751-0473-9-3

**Comment by tfenne** [comment]
@zhongwulai any thoughts on whether this is something that is desirable to be fixed in VarDict itself?  

@dh10 I agree with you on the additional information when the basecall is different in R1 vs. R2, but don't think it makes sense to output two AFs.  Each template really should only be counted once as an independent observations - the best thing to do would be to use the information from both reads when there is an overlap to generate a single observation, and then use that.  This is of course, rather tricky, but a first attempt that wouldn't introduce much bias might simply be to a) exclude bases when R1 and R2 disagree, and b) include the base once with the higher of the two quality scores, when the bases agree.

**Comment by vinogradovs** [comment]
@tfenne we at EPAM have discussed some possible ways how to fix this in VarDict itself.
May we ask you to provide us with some data samples containing the overlapping reads?

**Comment by dh10** [comment]
@tfenne I agree on not counting twice obviously and one doesn't want to make this too complicated

It is still useful to know how many of the supporting ALT and REF observations arose from overlapping pairs  especially with rare subclones

On Jan 10, 2017, at 4:31 PM, vinogradovs <notifications@github.com<mailto:notifications@github.com>> wrote:


@tfenne<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tfenne&d=DwMCaQ&c=lb62iw4YL4RFalcE2hQUQealT9-RXrryqt9KZX2qu2s&r=Kj-DtlG9LaAQRd3mIvRkmkQRrSAbM8RVhb0s7PuNk7E&m=DvwpiS9KgKwBwtGm6QRGV1LZCIYa6vWugFcxQRjTi9k&s=IDby0jo2oYfSJwdQtWBBF-F2PPbUGumqieMYDU-sRH4&e=> we at EPAM have discussed some possible ways how to fix this in VarDict itself.
May we ask you to provide us with some data samples containing the overlapping reads?

-

**Comment by mjafin** [comment]
We've discussed different options and the simplest thing to implement according to @zhongwulai  would be to stop reading the leftmost (rightmost) read when its mate starts. Obviously this is not as good as forming a consensus but probably much faster and a good start. Stay tuned.

**Comment by mjafin** [comment]
@tfenne we have an initial implementation to address the overlapping reads by just stopping reading the +ve strand read when encountering the start of a (properly aligned) -ve strand read. Would you be interested in testing it on your side, not just to check that the reads for your specific cases are counted correctly but also that you don't see unexpected drop in true positives elsewhere?

**Comment by tfenne** [comment]
@mjafin I'd be happy to.  I can compare a few samples run with my own clipping tool and then fed into the existing version of VarDictJava, vs. the built in support.  Can you point me at a branch I can build from?

**Comment by mjafin** [comment]
@ZLyanov can your team take a look at exposing the development branch with the initial fixes in?

**Comment by SilinPavel** [comment]
Here is a binary of VarDict that implements the Step 1 of Overlapping reads problem solution. @tfenne Could you please try it on your samples? (Development branch will follow shortly)
[VarDict-1.4.8_orf.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/724124/VarDict-1.4.8_orf.zip)

**Comment by SilinPavel** [comment]
@tfenne Development branch is here: https://github.com/AstraZeneca-NGS/VarDictJava/tree/f_processing_overlapping_reads

**Comment by chapmanb** [comment]
Tim, Miika, Pavel and Zaal;
I ran validations of the no overlapping read version against DREAM synthetic dataset 4. We needed to do a small post-calling filter tweak but after that the new version looks great. It's more sensitive and specific:

http://imgur.com/a/SF2a8

Thanks for the suggestion to tackle this.

**Comment by mjafin** [comment]
Excellent! 
@ZLyanov and @SilinPavel can you push out a new release for VarDictJava and merge the developmental branch into master when you're happy with your tests (which I imagine you have already run, in which case not other action besides merging and release).

**Comment by mjafin** [comment]
Closing issue, stand by for new release

**Comment by mjafin** [comment]
This seems to have come back to bite us. I noticed it with a missing EGFR L861Q variant. Analysis by EPAM:
```
Counters in perl: fwd: 111, rev: 127, bias flag: 2
Counters in java: fwd: 3, rev: 127, bias flag: 1
```
I don't know yet how prevalent this would be but definitely a source of false negatives.

**Comment by tfenne** [comment]
@mjafin I think the problem is that the observations are removed in a biased way - i.e. it looks like when there are overlapping reads that the forward observations are always removed, which is problematic.  Rather than undoing the existing change, I think the right thing to do is to randomize which observation is removed to ensure that the balance of both +/- and F/R is preserved.  In your example above I would hope to see the Java version emit something like the following, plus or minus stochastic differences:

```fwd: 54, rev: 73, bias flag: 2```

**Comment by mjafin** [comment]
Is anyone in favour or against using R1/R2 instead of +/- strand to decide which of the overlapping reads to use?

**Comment by tfenne** [comment]
@mjafin I think the right thing to do would be to just randomize - where the pair overlap use an RNG to make the decision.  E.g. generate a number between 0 and 1, and if < 0.5 discard R1 else discard R2.  That way it's hard to introduce any systematic bias.  I worry that using R1/R2 you'll fix the strand bias problem, but could, e.g. create a position in read bias problem.

**Comment by mjafin** [comment]
@tfenne 
Thanks for chiming in. The issue I can see with the RNG approach is that we'd have to store read names in memory wouldn't we? This would increase the memory footprint and is something I'd like to avoid as it will be unpredictable.
