### ISSUE TITLE
multi-allelic sites

### ISSUE THREAD

**Issue by bramslabbinck** [AstraZeneca-NGS/VarDictJava#65]
Multi-allelic sites are not called when running the amplicon-aware mode (unpaired). This in contrast to the default run with a 3-column bed file.
When inspecting the code of the method ampVarDict, I noticed that in case of multi-allelic sites only the first allele is retrieved. See line https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L5628, coding Variant tv = l.get(**0**); . This also holds for more code downstream. 
What is the reasoning behind this? Is it possible to also output multi-allelic sites?

**Comment by mjafin** [comment]
Hi @bramslabbinck, thanks for pointing this out. I spoke to @zhongwulai who thinks this is a reasonable request. Once this is fixed you still need to use the `-A` option in `var2vcf_valid.pl` to output all alleles. 

@ZLyanov could you and your team put this on the to-do list (possibly after the current pull requests are addressed)? According to Zhongwu: "The code would indeed need change.  It needs to loop through the array of good variants for that position and output the result, instead of just 1st most abundant one. I think just change it as the default behavior, no need to add option"

**Comment by ZLyanov** [comment]
@mjafin done: the issue is in our to-do list now.

**Comment by ekazachkova** [comment]
@bramslabbinck, @mjafin we`ve implimented the loop through the array of good variants. 
Please look at the [results](https://github.com/AstraZeneca-NGS/VarDictJava/files/802968/results.tar.gz). 
Is this what you expect? 
Also it will be great to get test data which better demonstrates this case.

Does it also make sense to consider the same update to the somatic postprocessing mode in somdict() method?
(we've checked it and seen that  it takes first allelled variation in several cases too).

**Comment by mjafin** [comment]
Amplicon aware mode is for tumor-only (not for paired runs) if that's what you mean. 

Maybe you raise another issue with `somdict()`?

**Comment by bramslabbinck** [comment]
@ekazachkova, at first sight it looks ok. Is there a possibility to share the branch so that I can test it myself?

**Comment by ekazachkova** [comment]
@bramslabbinck, sure. Have a look please ([branch](https://github.com/AstraZeneca-NGS/VarDictJava/tree/f_amp_multi-allelic)).

**Comment by ekazachkova** [comment]
@bramslabbinck, we have an idea how to fix it but our data is not demonstrative. Could you please provide a data which includes similar case?

**Comment by mjafin** [comment]
@bramslabbinck is the event reported twice in the vcf or just the output of VarDictJava? The vcf generating script should not report a variant twice but there could always be a bug.

**Comment by bramslabbinck** [comment]
@mjafin I noticed that in the case of overlapping amplicons, events are reported for each amplicon separately in the raw output of VarDict (i.e. tabular output). All specs such as depth, frequency, etc. are calculated solely based on the reads of each amplicon. It would be nice to have an option to report the events by chromosomal position covering all reads of all amplicons overlapping this position. Specs should then be calculated based on all reads covering this position, regardless the amplicon they belong to. Btw, this holds for all events, including the multi-allelic events. 
Thank you for your time and effort!

**Comment by mjafin** [comment]
@bramslabbinck I think there was a design decision by @zhongwulai regarding amplicons and only reporting the variant of one amplicon (the one estimated to be the "best"). In the vcf you should see each variant reported once only.

**Comment by bramslabbinck** [comment]
@mjafin I also looked at the output of the VCF file running the var2vcf_valid.pl with the -A option. Also in the vcf file, events are reported per position and per amplicon.

**Comment by bramslabbinck** [comment]
@mjafin as requested, I can hereby confirm that the multi-allelic sites in my data are now reported by the software!
I am still in favor of having variants reported solely by chromosomal position. I'll close this issue and open a new issue for this feature.
