### ISSUE TITLE
Issue with Hisat2 alignments

### ISSUE THREAD

**Issue by mjafin** [AstraZeneca-NGS/VarDictJava#66]
I noticed that certain hisat2 alignments produce negative read depths for the reference allele, attaching a bam file. 

[chr1test.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/780019/chr1test.zip)

My run call is 
```
vardict-java -G /ngs/reference_data/genomes/Hsapiens/hg38/seq/hg38.fa -f 0.05 -N Sample_3_490--5 -b chr1test.bam -c 1 -S 2 -E 3 -g 4 -Q 10 region.bed
```
where region bed can just be the region aroud `chr1:111449836-111449837`

The negative values throw R off in strand bias testing.

**Comment by cbrueffer** [comment]
Is there any more information on this? I'm about to start calling on a big sample set using HISAT2+VarDict and seeing this is a bit disconcerning.

**Comment by mjafin** [comment]
@cbrueffer you can certainly give it a go. I noticed that, likely due to improper CIGAR strings, VarDict produced negative values for allele depths. As a quick hack, I modified this
https://github.com/AstraZeneca-NGS/VarDict/blob/master/teststrandbias.R#L24
by
```
h <- fisher.test(matrix(c( max(0,d[i,10]) , max(0,d[i,11]) , max(0,d[i,12]) , max(0,d[i,13]) ), nrow=2))
```
It's not the right thing to do but gets you through. 

I got an absolutely stupid number of short indels coming from Hisat2 aligned files.

**Comment by cbrueffer** [comment]
Thanks for the update! So it just produces a lot of false positives (hopefully easy to filter out), or does it also also result in a false negatives?

**Comment by mjafin** [comment]
I don't have a benchmark RNA-seq data set so it's all anecdotal at the moment; I have no idea what I'm missing because of Hisat2.

**Comment by PolinaBevad** [comment]
@mjafin, hello!
My guess is this error fixed in #128. I tested the BAM you provide in the first message on master branch of VarDictJava and now there are no negative values in the read depths. 
Can we close this issue? If the problem appears again, we will reopen it.

**Comment by mjafin** [comment]
Works for me

**Comment by PolinaBevad** [comment]
Thanks!
