### ISSUE TITLE
Vardict result annotation

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [AstraZeneca-NGS/VarDictJava#67]
Have any hint on  how to annotate  the  vardict results using annovar or snpeff?

**Comment by mjafin** [comment]
Hi @bioinfo-dirty-jobs,
We don't use Annovar internally (you need a licence unless academic) but SnpEff is brilliant. You can find all SnpEff documentation at http://snpeff.sourceforge.net/SnpEff.html and report any issues at  https://github.com/pcingola/SnpEff/
