### ISSUE TITLE
What is difference between VarDict and VarDictJava?

### ISSUE THREAD

**Issue by Tinalxt** [AstraZeneca-NGS/VarDictJava#70]
Hi,I am new with VarDict and have problems with it. When I run the runVarDict_BAM.sh in the VarDict-master folder for calling the variants, I called 8 sites that I need, but when I run the version of VarDictJava with the same parameters, I only called 5 or 6 variants that I need. So I want to know whether the VarDictJava filters something or how can I get the same result when I use VarDictJava?

**Comment by mjafin** [comment]
Hi @Tinalxt, VarDictJava was originally a direct port of VarDict itself but we are in the process of deprecating the Perl version and thus it will be behind VarDictJava in terms of functionality. I would recommend sticking to VarDictJava instead of using vardict.pl.

**Comment by Tinalxt** [comment]
I got the different vcf when I run the VarDict and VarDictJava. I grep 8 sites that I need. In the result of perl, I got 8 sites that I needed, but in the result of  java, I only got 7sites that I needed. I found what I lost is different from other with "BIAS=2:1". I want to know whether I can set some parameters to not filter the "BIAS=2:1" in the Java version? Thank you!


Perl:
le ss_2.vcf|grep -E '55259515|55249071|25398284|115256530|115256536|178936091|55248998|55242464'
chr1	115256536	.	C	T	411	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1069;VD=76;AF=0.0711;BIAS=2:2;REFBIAS=117:875;VARBIAS=8:68;PMEAN=43.1;PSTD=1;QUAL=65.8;QSTD=1;SBF=0.85448;ODDRATIO=1.13643;MQ=60;SN=152;HIAF=0.0711;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.2;HICNT=76;HICOV=1069;LSEQ=ACTGTACTCTTCTTGTCCAG;RSEQ=TGTATCCAGTATGTCCAACA	GT:DP:VD:AD:AF:RD:ALD	0/1:1069:76:992,76:0.0711:117,875:8,68
chr3	178936091	.	G	A	424	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1480;VD=90;AF=0.0608;BIAS=2:2;REFBIAS=171:1218;VARBIAS=10:80;PMEAN=41.2;PSTD=1;QUAL=65.4;QSTD=1;SBF=0.86855;ODDRATIO=1.12304;MQ=55.7;SN=180;HIAF=0.0608;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.3;HICNT=90;HICOV=1480;LSEQ=ATCCTCTCTCTGAAATCACT;RSEQ=AGCAGGAGAAAGATTTTCTA	GT:DP:VD:AD:AF:RD:ALD	0/1:1480:90:1389,90:0.0608:171,1218:10,80
chr7	55242464	.	AGGAATTAAGAGAAGC	A	371	PASS	SAMPLE=SS_2;TYPE=Deletion;DP=1557;VD=53;AF=0.034;BIAS=2:2;REFBIAS=205:1291;VARBIAS=3:50;PMEAN=36;PSTD=1;QUAL=64.9;QSTD=1;SBF=0.10195;ODDRATIO=2.64535;MQ=60;SN=106;HIAF=0.0340;ADJAF=0.0071;SHIFT3=0;MSI=4;MSILEN=1;NM=0.2;HICNT=53;HICOV=1557;LSEQ=TAAAATTCCCGTCGCTATCA;RSEQ=AACATCTCCGAAAGCCAACA	GT:DP:VD:AD:AF:RD:ALD	0/1:1557:53:1496,53:0.034:205,1291:3,50
chr7	55248998	.	A	ATGGCCAGCG	422	PASS	SAMPLE=SS_2;TYPE=Insertion;DP=2111;VD=86;AF=0.0407;BIAS=2:2;REFBIAS=483:1538;VARBIAS=13:73;PMEAN=38.5;PSTD=1;QUAL=65.7;QSTD=1;SBF=0.06857;ODDRATIO=1.76316;MQ=60;SN=172;HIAF=0.0407;ADJAF=0.0062;SHIFT3=12;MSI=1.333;MSILEN=1;NM=0.3;HICNT=86;HICOV=2111;LSEQ=CCCTCCAGGAAGCCTACGTG;RSEQ=TGGCCAGCGTGGACAACCCC	GT:DP:VD:AD:AF:RD:ALD	0/1:2111:86:2021,86:0.0407:483,1538:13,73
chr7	55249071	.	C	T	450	PASS	SAMPLE=SS_2;TYPE=SNV;DP=2596;VD=131;AF=0.0505;BIAS=2:2;REFBIAS=377:2085;VARBIAS=17:114;PMEAN=36.9;PSTD=1;QUAL=64.1;QSTD=1;SBF=0.53336;ODDRATIO=1.21244;MQ=60;SN=262;HIAF=0.0505;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.2;HICNT=131;HICOV=2596;LSEQ=CTCCACCGTGCAGCTCATCA;RSEQ=GCAGCTCATGCCCTTCGGCT	GT:DP:VD:AD:AF:RD:ALD	0/1:2596:131:2462,131:0.0505:377,2085:17,114
chr7	55259515	.	T	G	434	PASS	SAMPLE=SS_2;TYPE=SNV;DP=2396;VD=111;AF=0.0463;BIAS=2:2;REFBIAS=293:1992;VARBIAS=18:93;PMEAN=37.5;PSTD=1;QUAL=63.9;QSTD=1;SBF=0.31033;ODDRATIO=1.31570291428196;MQ=60;SN=222;HIAF=0.0463;ADJAF=0;SHIFT3=0;MSI=2;MSILEN=1;NM=1.3;HICNT=111;HICOV=2396;LSEQ=CAAGATCACAGATTTTGGGC;RSEQ=GGCCAAACTGCTGGGTGCGG	GT:DP:VD:AD:AF:RD:ALD	0/1:2396:111:2285,111:0.0463:293,1992:18,93
chr12	25398284	.	C	T	450	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1817;VD=119;AF=0.0655;BIAS=2:2;REFBIAS=225:1463;VARBIAS=18:101;PMEAN=40.4;PSTD=1;QUAL=65.3;QSTD=1;SBF=0.57807;ODDRATIO=1.15868142054342;MQ=60;SN=238;HIAF=0.0655;ADJAF=0;SHIFT3=0;MSI=2;MSILEN=1;NM=1.2;HICNT=119;HICOV=1817;LSEQ=AGGCACTCTTGCCTACGCCA;RSEQ=CAGCTCCAACTACCACAAGT	GT:DP:VD:AD:AF:RD:ALD	0/1:1817:119:1688,119:0.0655:225,1463:18,101

Java:
le ss_2_p.vcf|grep -E '55259515|55249071|25398284|115256530|115256536|178936091|55248998|55242464'
chr1	115256530	.	G	T	400	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1110;VD=79;AF=0.0712;BIAS=2:1;REFBIAS=115:913;VARBIAS=3:76;PMEAN=36.4;PSTD=1;QUAL=63.5;QSTD=1;SBF=0.03718;ODDRATIO=3.18871;MQ=60;SN=158;HIAF=0.0712;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.4;HICNT=79;HICOV=1110;LSEQ=CATGGCACTGTACTCTTCTT;RSEQ=TCCAGCTGTATCCAGTATGT	GT:DP:VD:AD:AF:RD:ALD	0/1:1110:79:1028,79:0.0712:115,913:3,76
chr1	115256536	.	C	T	411	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1069;VD=76;AF=0.0711;BIAS=2:2;REFBIAS=117:875;VARBIAS=8:68;PMEAN=43.1;PSTD=1;QUAL=65.8;QSTD=1;SBF=0.85448;ODDRATIO=1.13643;MQ=60;SN=152;HIAF=0.0711;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.2;HICNT=76;HICOV=1069;LSEQ=ACTGTACTCTTCTTGTCCAG;RSEQ=TGTATCCAGTATGTCCAACA	GT:DP:VD:AD:AF:RD:ALD	0/1:1069:76:992,76:0.0711:117,875:8,68
chr3	178936091	.	G	A	424	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1480;VD=90;AF=0.0608;BIAS=2:2;REFBIAS=171:1218;VARBIAS=10:80;PMEAN=41.2;PSTD=1;QUAL=65.4;QSTD=1;SBF=0.86855;ODDRATIO=1.12304;MQ=55.7;SN=180;HIAF=0.0608;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.3;HICNT=90;HICOV=1480;LSEQ=ATCCTCTCTCTGAAATCACT;RSEQ=AGCAGGAGAAAGATTTTCTA	GT:DP:VD:AD:AF:RD:ALD	0/1:1480:90:1389,90:0.0608:171,1218:10,80
chr7	55242464	.	AGGAATTAAGAGAAGC	A	371	PASS	SAMPLE=SS_2;TYPE=Deletion;DP=1557;VD=53;AF=0.034;BIAS=2:2;REFBIAS=205:1291;VARBIAS=3:50;PMEAN=36;PSTD=1;QUAL=64.9;QSTD=1;SBF=0.10195;ODDRATIO=2.64535;MQ=60;SN=106;HIAF=0.0340;ADJAF=0.0071;SHIFT3=0;MSI=4;MSILEN=1;NM=0.2;HICNT=53;HICOV=1557;LSEQ=TAAAATTCCCGTCGCTATCA;RSEQ=AACATCTCCGAAAGCCAACA	GT:DP:VD:AD:AF:RD:ALD	0/1:1557:53:1496,53:0.034:205,1291:3,50
chr7	55248998	.	A	ATGGCCAGCG	422	PASS	SAMPLE=SS_2;TYPE=Insertion;DP=2111;VD=86;AF=0.0407;BIAS=2:2;REFBIAS=483:1538;VARBIAS=13:73;PMEAN=38.5;PSTD=1;QUAL=65.7;QSTD=1;SBF=0.06857;ODDRATIO=1.76316;MQ=60;SN=172;HIAF=0.0407;ADJAF=0.0062;SHIFT3=12;MSI=1.333;MSILEN=1;NM=0.3;HICNT=86;HICOV=2111;LSEQ=CCCTCCAGGAAGCCTACGTG;RSEQ=TGGCCAGCGTGGACAACCCC	GT:DP:VD:AD:AF:RD:ALD	0/1:2111:86:2021,86:0.0407:483,1538:13,73
chr7	55249071	.	C	T	450	PASS	SAMPLE=SS_2;TYPE=SNV;DP=2596;VD=131;AF=0.0505;BIAS=2:2;REFBIAS=377:2085;VARBIAS=17:114;PMEAN=36.9;PSTD=1;QUAL=64.1;QSTD=1;SBF=0.53336;ODDRATIO=1.21244;MQ=60;SN=262;HIAF=0.0505;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.2;HICNT=131;HICOV=2596;LSEQ=CTCCACCGTGCAGCTCATCA;RSEQ=GCAGCTCATGCCCTTCGGCT	GT:DP:VD:AD:AF:RD:ALD	0/1:2596:131:2462,131:0.0505:377,2085:17,114
chr7	55259515	.	T	G	434	PASS	SAMPLE=SS_2;TYPE=SNV;DP=2396;VD=111;AF=0.0463;BIAS=2:2;REFBIAS=293:1992;VARBIAS=18:93;PMEAN=37.5;PSTD=1;QUAL=63.9;QSTD=1;SBF=0.31033;ODDRATIO=1.31570291428196;MQ=60;SN=222;HIAF=0.0463;ADJAF=0;SHIFT3=0;MSI=2;MSILEN=1;NM=1.3;HICNT=111;HICOV=2396;LSEQ=CAAGATCACAGATTTTGGGC;RSEQ=GGCCAAACTGCTGGGTGCGG	GT:DP:VD:AD:AF:RD:ALD	0/1:2396:111:2285,111:0.0463:293,1992:18,93
chr12	25398284	.	C	T	450	PASS	SAMPLE=SS_2;TYPE=SNV;DP=1817;VD=119;AF=0.0655;BIAS=2:2;REFBIAS=225:1463;VARBIAS=18:101;PMEAN=40.4;PSTD=1;QUAL=65.3;QSTD=1;SBF=0.57807;ODDRATIO=1.15868142054342;MQ=60;SN=238;HIAF=0.0655;ADJAF=0;SHIFT3=0;MSI=2;MSILEN=1;NM=1.2;HICNT=119;HICOV=1817;LSEQ=AGGCACTCTTGCCTACGCCA;RSEQ=CAGCTCCAACTACCACAAGT	GT:DP:VD:AD:AF:RD:ALD	0/1:1817:119:1688,119:0.0655:225,1463:18,101

**Comment by mjafin** [comment]
Hi @Tinalxt, I think you may have mixed the java and perl labels..?
In any case, the first variant on the second list (missing on the first list) seems to have three forward reads and 76 reverse reads, so likely an issue with strand bias. 

There are differences now between the Java and Perl versions like I mentioned as we're planning to drop the perl version altogether. One of the differences that could cause this is "double counting", see https://github.com/AstraZeneca-NGS/VarDictJava/issues/60, fixed only in the Java version. It is possible your read pairs may have an overlap, such that the three forward reads supporting the variant also have the variant in the reverse reads. In the Java version we stop reading the first read once the beginning of the second read is reached (if there is an overlap). I suspect this could lead to no forward reads supporting the variant and thus the strand bias flag going up.

There is a plan to do less hard-filtering based on strand bias in VarDictJava: https://github.com/AstraZeneca-NGS/VarDictJava/issues/62 but these fixes are not yet in.

**Comment by ekazachkova** [comment]
@Tinalxt, it seems that such differences might be caused by fixing the overlapping reads problem [issue#60](https://github.com/AstraZeneca-NGS/VarDictJava/issues/60). If you'd like to check this furher, you could try running previous VarDictJava version (v1.4.8) (or checkout to commit a69332f) against your data to see whether the differences persist.
