### ISSUE TITLE
Does hisat2_extract_snps_haplotypes_VCF.py handle unphased variants correctly?

### ISSUE THREAD

**Issue by mce1** [AstraZeneca-NGS/VarDictJava#71]
Hi there,

I use hisat2_extract_snps_haplotypes_VCF.py to extract snps and haplotypes from a vcf-file. My vcf-files contains some variants which are phased (i.e. 1|0) and a majority which are not (i.e. 1/0). The python script, however, appears not to distinguish between the two but seems to treat all variants as if they were phased. As a result, it constructs haplotypes from snps that are not phased. Is this correct or do I miss something?

I don't know what exactly hisat2-build does with the haplotype-file, but if it uses the haplotypes as fixed blocks of variants in the index this might result in unwanted behaviour, as some combinations of variants (which can actually occur because the variants are not phased or are phased in a manner different from what the haplotype-file assumes) will not be represented. Can/should this be changed or does it not really matter?

Cheers,

mce1

**Comment by mjafin** [comment]
Hi @mce1, 
I wonder if you used VarDict for any part of your analysis? Your question might be better placed at https://github.com/infphilo/hisat2/issues
