### ISSUE TITLE
Error with Amplicon Calling

### ISSUE THREAD

**Issue by jamie-a** [AstraZeneca-NGS/VarDictJava#72]
2 issues actually;

1) I've prepared an amplicon style bed file as specified, but whenever I run with the -a option I get this error message:

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at com.astrazeneca.vardict.VarDict.toRegions(VarDict.java:185)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:82)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)`

If I omit the the -a, it runs fine.

2) When calling in amplicon aware mode (which I am assuming is still happening as the bed file is in amplicon format, even though I'm leaving out the -a option), I'm having an issue with variants not being called when they overlap a primer for one amplicon. I'm aware that primer variants are deliberately ignored, but it seems like this might be happening even when the site is covered by 2 amplicons. In one it's in primer region but in the other it's right in the middle of the amplicon, and viewing in IGV shows a pretty perfect 50:50 het. I have a few of these and the variants have been separately Sanger validated.

**Comment by mjafin** [comment]
Hi @jamie-a,
To be able to help you better could you provide a slice of your bam file and the region in your amplicon format bed file?

**Comment by jamie-a** [comment]
Yes for sure, I'll send over email.

**Comment by jamie-a** [comment]
Hi Miika,

So here's the amplicon bed section specific to one of the variants:

chr16    23641234    23641503    PALB2    .    23641258 23641479
chr16    23641415    23641699    PALB2    .    23641439 23641675

And I've attached an extract of chr16 from the sample in question.

Variant is 16_23641485_T_G.

Cheers,

Jamie.

**Comment by jamie-a** [comment]
[chr16.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/878620/chr16.tar.gz)
So here's the amplicon bed section specific to one of the variants:

chr16    23641234    23641503    PALB2    .    23641258    23641479
chr16    23641415    23641699    PALB2    .    23641439    23641675

And I've attached an extract of chr16 from the sample in question.

Variant is 16_23641485_T_G.

**Comment by mjafin** [comment]
Thanks Jamie, I like problems that solve themselves :)

You may want to try VarDict again after the fixes in this ticket https://github.com/AstraZeneca-NGS/VarDictJava/issues/68#issuecomment-290067163 are in too.

**Comment by jamie-a** [comment]
Ah ok -//I guess that relates with #65 as well? Thanks for the info
