### ISSUE TITLE
Update VarDict for whitespace in sample name fix

### ISSUE THREAD

**Issue by nh13** [AstraZeneca-NGS/VarDictJava#76]
I am wondering what needs to be done to get VarDictJava to use this fix in its master branch: https://github.com/AstraZeneca-NGS/VarDict/pull/47

Thanks for helping us out!

**Comment by mjafin** [comment]
Hi @nh13, the fixes were applied to the `var2vcf` functions that follow and are not part of VarDict perl or VarDictJava. Are you asking us if we could incorporate the `var2vcf` perl scripts into Java at some point?

**Comment by nh13** [comment]
I see that VarDict is a submodule. I think it pulls the master branch of VarDict, is that correct? If so, then I just need to update the submodule to get the version of the script.

**Comment by mjafin** [comment]
Got it. The guys are on it.

**Comment by SilinPavel** [comment]
@nh13 Done! 
@mjafin Should we release 1.5.1?

**Comment by nh13** [comment]
@SilinPavel thank-you!  A release would be helpful so I can update the tag in my docker build.

**Comment by mjafin** [comment]
Yes please if it helps.

**Comment by SilinPavel** [comment]
@nh13, @mjafin  done!
https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.5.1
