### ISSUE TITLE
Multi-sample variant calling by VarDict

### ISSUE THREAD

**Issue by samkh918** [AstraZeneca-NGS/VarDictJava#77]
Hello,

My apologies if this has already been addressed elsewhere, I was wondering if VarDict can also perform "multi-sample" variant calling by accepting multiple BAM files as input so that it would retain the 0/0 genotypes of a family member at positions where another family member has a non-REF variant.

Thanks for your help.

**Comment by mjafin** [comment]
Hi @samkh918, VarDict is designed more as a cancer variant caller than population caller. Multi sample calling isn't supported and we have no current plans of adding support for multi sample calling.

**Comment by samkh918** [comment]
Thank you @mjafin for your reply.
