### ISSUE TITLE
Ouput only Somatic option doesn't seem to work in the latest revision

### ISSUE THREAD

**Issue by OgnjenSB** [AstraZeneca-NGS/VarDictJava#82]
In the last revision (and perhaps some earlier ones) the option -M doesn't seem to have any effect on the output. I cross-tested the outputs from the new previous tool with an older version, and the old TSV output from TestSomatic.R with the new tool, and all runs output STATUS=Germline mutations as well.

Do you mind taking a look?

Thanks in advance!

P.S. If I can help in any way, please tell me!

**Comment by mjafin** [comment]
Hi @OgnjenSB sorry about the problems. Do you have any small test data you could show this behaviour on? Just a slice of BAM where you previously saw different behaviour (and let us know which genome you used).

**Comment by OgnjenSB** [comment]
Thank you very much for a prompt reply. I can give you the data as it is public, I am just not sure how is this done on Git. What is a common practice?
Also,if you have an account on Seven Bridges platform, I can invite you to the project, all the runs are there, with files and logs.

Thanks again!

**Comment by nkarulin** [comment]
Hello @OgnjenSB

You could try to test c04bfdec2c0cd26cb087fdef917394c5b2e28a39 revisoin.

There were changes from @tfenne, that "clean up" CIGAR replacing insertions cigar elements by softclip in some cases. But in that cases an amount of filtered by option -M reads should only increase.

Call you please share launch parameters on which you expect the behavior?

**Comment by sanja-m** [comment]
Hi @mjafin.
Thank you for a response!

Here are the test files, only five mutations were extracted, 4 SNVs and 1 indel. Bed file with covered positions is also attached. The reference genome is grch37.
Also want to point out that we got the same results (the same number of mutation) when we turn on the parameter -M in command line, and when we do not. There are lines with STATUS=Germline mutations.  

If you need anything else from our side, please let us know.

[BAM_for_testing.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/1084809/BAM_for_testing.zip)

**Comment by sanja-m** [comment]
So sorry for the error in the archive I sent in previous comment, here is the correct one. 
Once again, so sorry for the inconvenience.

[BAM_files_for_testing.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/1084954/BAM_files_for_testing.zip)

**Comment by kamyshova** [comment]
Hello @sanja-m 
M option just tells VarDict to skip reads with length of match (with insertions) region less then M. The majority of reads in your samples has match region length equal to 101 (7147 reads in normal and 7212 in tumor). The distribution of reads with other match regions lengths is in the chart below. 
![reads dist on match length](https://user-images.githubusercontent.com/23356251/27436564-54fd9eb6-5768-11e7-8ad7-e5eca2bd58c0.png)
Is it possible that the value of M option you pass is too low? We start seeing changes of variations fields on your samples with value of M=36. When M=100 the deletion at 128587343 position is not shown.

**Comment by OgnjenSB** [comment]
Hello @kamyshova ,

I apologize sincerely for not being more explicit. We were talking about var2vcf_somatic tool, and the -M option that is supposed to output only somatic mutations, but seems to output all of them. We mistakenly steered you towards the main Java Tool which works fine for us.
Sorry again for the confusion!

**Comment by OgnjenSB** [comment]
Hi!
Just a small reminder, although I am sure you are quite busy. Did we clearly communicate the problem, or do you need more info from us?

Thanks!

**Comment by sanja-m** [comment]
Hello,

@mjafin, @nkarulin Are there any news on this topic? Thanks.

Best

**Comment by kamyshova** [comment]
Hello, @OgnjenSB
This is VarDict Java repository, so it's better to refer this issue to the original Perl VarDict repository. 
As far as we understand, var2vcf_somatic.pl was deprecated in favour of var2vcf_paired.pl. 
Perhaps you should try using the var2vcf_paired.pl script.
Hopefully @mjafin will respond in more detail on Monday.

Sincerely

**Comment by mjafin** [comment]
Yes, please use `var2vcf_paired.pl` and not the deprecated `var2vcf_somatic.pl` script.
