### ISSUE TITLE
what's the different between var2vcf_somatic.pl and var2vcf_paired.pl 

### ISSUE THREAD

**Issue by MIAOKUI** [AstraZeneca-NGS/VarDictJava#85]
Hi 
I do somatic mutation in paired mode. I notice that the latest version of vardict and vardict java the github quick start replace var2vcf_somatic.pl with var2vcf_paired.pl. 
What's the difference between these two filtering script. Should replace in our old pipeline ?

**Comment by mjafin** [comment]
Hi @MIAOKUI, `var2vcf_somatic.pl` has been deprecated some time ago already in favour of  `var2vcf_paired.pl`. Please use only `var2vcf_paired.pl`. Sorry about the confusion.
