### ISSUE TITLE
Different mutation between vardict and vardictjava

### ISSUE THREAD

**Issue by MIAOKUI** [AstraZeneca-NGS/VarDictJava#86]
Hi  

I try to compare vardict and vardictjave with same parameter, but I got about half of the mutation different from each others. The command as follows
vardict java
#!/bin/bash 
/gpfs/software/pipeline/softwares/VarDictJava/build/install/VarDict/bin/VarDict -f 0.001 -c 1 -S 2 -E 3  -G /gpfs/software/pipeline/pipeline/database/ref/hg19/hg19.fasta -N "tumor|normal" -b "./tumor.final.bam|normal.final.bam" /gpfs/software/pipeline/pipeline/region/region_59_177k/59gene_1_Regions_10_rs.merge.bed | /gpfs/software/pipeline/softwares/VarDictJava/VarDict/testsomatic.R | /gpfs/software/pipeline/softwares/VarDictJava/VarDict/var2vcf_paired.pl -N "tumor|normal" -f 0.001  > ./vardict_pair_java_var2vcf_paired.vcf

vardict perl #!/bin/bash 
/gpfs/software/pipeline/pipeline/tools/VarDict/vardict.pl -f 0.001 -c 1 -S 2 -E 3 -G /gpfs/software/pipeline/pipeline/database/ref/hg19/hg19.fasta -N "tumor|normal" -b "./tumor.final.bam|normal.final.bam" /gpfs/software/pipeline/pipeline/region/region_59_177k/59gene_1_Regions_10_rs.merge.bed | /gpfs/software/pipeline/pipeline/tools/VarDict/testsomatic.R | /gpfs/software/pipeline/pipeline/tools/VarDict/var2vcf_somatic.pl  > ./vardict_pair.vcf

In the result 
vardict perl found 7185 + 3977 points and vardict java found 3977+1853. And 3977 was overlaped. 

I wondering this happened? Which one is should I trust?

**Comment by mjafin** [comment]
VarDictJava has new features and functionality (such as not double counting variants in overlapping mates) not implemented in VarDict perl. I would suggest using VarDict Java.
