### ISSUE TITLE
Malformed query; start point lies after end point + Error in scan: line did not have 34 elements

### ISSUE THREAD

**Issue by dgellerup** [AstraZeneca-NGS/VarDictJava#89]
I am using the following command:

AF_THR=0.01
vardict-java -D -G reference.fa -f $AF_THR -N SmoothMuscle -b SmoothMuscle_sorted.bam -c 1 -S 2 -E 3 -g 4 SmoothMuscle_sorted.bed | teststrandbias.R | var2vcf_valid.pl -N SmoothMuscle -E -f $AF_THR > SmoothMuscle.vcf

I received this error message:

Exception in thread "main" htsjdk.samtools.SAMException: Malformed query; start point 386 lies after end point 0
at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:215)
	at com.astrazeneca.vardict.VarDict.retriveSubSeq(VarDict.java:1056)
	at com.astrazeneca.vardict.VarDict.getREF(VarDict.java:3258)
	at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:323)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:278)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:89)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 2 did not have 34 elements
Calls: read.table -> scan
Execution halted

I am running VarDict Java obtained from Bioconda.

The first lines of my bed file look like this:

1	10000	10099	D3NQ4HQ1:908:HHJKCBCXY:2:2203:8297:31768 2:N:0:CAAAAG	3	-
1	10001	10107	D3NQ4HQ1:908:HHJKCBCXY:2:1113:7965:47878 2:N:0:CAAAAG	3	+
1	10005	10104	D3NQ4HQ1:908:HHJKCBCXY:2:2203:8297:31768 1:N:0:CAAAAG	21	+
1	10067	10135	D3NQ4HQ1:908:HHJKCBCXY:2:2110:7371:23223 2:N:0:CAAAAG	2	+
1	10069	10150	D3NQ4HQ1:908:HHJKCBCXY:2:1114:19506:26060 2:N:0:CAAAAG	2	+

I'm not sure how to share the content of my bam file, as it is 2GB in size. I used the Joint Genome Institute's bbTools suite to trim, merge, dedupe, map, and recalibrate my sequences, and Samtools to sort and index my bam.

**Comment by mjafin** [comment]
Hi @dgellerup, Apologies for the late reply. Just to confirm your bam files are BWA-mem aligned and you modified them somehow using bbTools?

If you were able to narrow down the exact locus where this happens by trying subsets of the bed file maybe you can identify a region that you could slice off the bam?

**Comment by drsuuzzz** [comment]
i found that this warning happens when VarDict is given a bed file with regions of length 1 bp.  By removing these from the file, VarDict continues without errors.  But this implies that there is a n-1 <=0 problem that is not handled correctly by VarDict.

**Comment by mjafin** [comment]
@drsuuzzz Thanks for the heads-up. Can you give an example bed line please and your run command?

**Comment by drsuuzzz** [comment]
Sure.  
bed line:

chr1\t3782375\t3782376\tuc009vln.1_cds_2_0_chr1_3782376_f\t0\t+

and 
run command

VarDict -th 8 -G hg19.fa -f $VARDICT_FREQ -N $prefix -b ${tnbam} $VARDICT_PARAMS coding.bed 2>${prefix}.vardict.errs | Rscript testsomatic.R | perl var2vcf_paired.pl -N ${tnname} -f $VARDICT_FREQ $FILTER_PARAMS > ${prefix}.somatic.vcf

**Comment by drsuuzzz** [comment]
oops. You may need this.  I don't think it matters but just in case
VARDICT_PARAMS="-k 0 -Q 20 -z 1 -c 1 -S 2 -E 3"
VARDICT_FREQ=0.1
FILTER_PARAMS="-S -M -I 6 -P 1 -d 20"

**Comment by nkarulin** [comment]
Hello, @drsuuzzz !
Are you sure, that the reason is presence of 1-length regions?
It looks like your BAM file does not contain the sequence that is in the BED in its header. Is that the case?

**Comment by drsuuzzz** [comment]
Hi! Yes, I'm sure.  Didn't provide a BAM file though.  Could you be responding to a different issue?

**Comment by nkarulin** [comment]
The point is that in general VarDict correctly handles 1-length regions. At least there in no runtime exception.

But you will sure have htsjdk.samtools.SAMException with that stacktrace if your BAM does not contains `@SQ` field in its header with value of your region's chromosome.

Could you please show at least your BAM file's header and a BED line which was removed to avoid the exception?

**Comment by PolinaBevad** [comment]
@drsuuzzz, hello! 
The same error can occur if you use wrong fasta (not the one BAM was aligned to) and the part of BAM will lie after the end of the chromosome. The same can happen if BED file contains regions that are not presented in fasta file. 
Please, check if regions that you deleted are in fasta and in BAM file.
Since there is no reply from you on the last comment, I will close this issue, but you can reopen it if you have any questions about this topic.
