### ISSUE TITLE
Whole-genome runs

### ISSUE THREAD

**Issue by kscheffler** [AstraZeneca-NGS/VarDictJava#95]
Is there a recommendation for how to run VarDict on a whole-genome tumor-normal pair? I saw some old mentions of a bed file for this purpose in issues on the VarDict distro (linked below), but I don't see the bed file itself. Based on numbers given there and on VarDictJava being 10x faster, I imagine it should run in <12 hours on a single node.

https://github.com/AstraZeneca-NGS/VarDict/issues/18
https://github.com/AstraZeneca-NGS/VarDict/issues/2

**Comment by mjafin** [comment]
Hi @kscheffler, the easiest way to run VarDict in parallel is via bcbio-nextgen. If you want to manually run VarDict it's good to split the genome into short intervals as VarDict's memory use depends on the interval lengths.

**Comment by kscheffler** [comment]
Ok, thanks - I'll give it a try.

**Comment by PolinaBevad** [comment]
@kscheffler, hello!
I will close this issue. If you have any additional questions on this topic, please, reopen it.
