### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by annaquaglieri16** [AstraZeneca-NGS/VarDictJava#96]
Hi there, 

I am trying to run VarDict on my RNA-Seq data and I keep getting the same error but cannot understand the cause. I ma running it in the most simple way just to debug it.

genome_fasta=/home/users/allstaff/quaglieri.a/PHD_project/GEO_Leucegene_data/genomes/hg19/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa

less $genome_fasta

unix402 639 % less $genome_fasta
>chrM
GATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCAT
TTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTG
GAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATT
CTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACCTACTA
.....

I checked and the fasta index exists. 

bamin=/wehisan/general/user_managed/grpu_majewski_3/quaglieri.a/GEO_Leucegene_data/hg19_aligned/STAR_2pass_CD34/SRX322298Aligned.reorderedDupl.rg.bam

$bamin is a regular healthy bamfile.

Here is the error message:

module load vardict # vardict/1.5.1(default)

vardict -b $bamin -G $genome_fasta -f 0.01
Exception in thread "main" java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at com.astrazeneca.vardict.VarDict.readBedFile(VarDict.java:218)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:61)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)

Any suggestion about the possible source of this error message?

Thanks for your help, 

Anna

**Comment by mjafin** [comment]
Hi @annaquaglieri16, VarDict should really be run on subsets of the genome, that is you need to provide coordinates where you want to call variants in. I would suggest turning to a pipeline engine such as bcbio-nextgen to analyse your samples as the details of manually parallelising VarDict can be quite daunting.

**Comment by annaquaglieri16** [comment]
Sorry for my huge delay! But I stopped working on that project for a while. Thanks for your help. That makes sense!

Anna
