### ISSUE TITLE
Empty output in amplicon mode

### ISSUE THREAD

**Issue by bwubb** [AstraZeneca-NGS/VarDictJava#98]
Greetings,

  I am attempting to run VarDictJava amplicon mode on single read data that was created from merging paired amplicon reads. I do not receive any errors or output. As far as I can see my bam file looks fine, its mapped, and validates checks, and GATK has been able to use them successfully. Perhaps there is some other silent incompatibility/requirement with single end data? Issue #63 seemed to indicate this type of read data was allowed.

Thanks!

-bwubb

**Comment by mjafin** [comment]
Hi @bwubb, I don't think we have any expertise in running single read data in amplicon mode. Is it possible to use the original paired end data instead?

**Comment by bwubb** [comment]
Hi @mjafin , I certainly can and will work that up. I assume then, there is some sort of read pair check? I read somewhere that merging amplicon paired reads that overlap into a single read is better for global/local alignment, but I dont really know if that is true.

Anyway if this is not any sort error/bug then we can close this issue. 

Thank you for the reply!

**Comment by bwubb** [comment]
Re-running from paired read data did not actually yield any variants either. Perhaps VarDict amplicon is not compatible with alignments made with bbmap? My next test, will have to be a bwa alignment.

**Comment by mjafin** [comment]
@bwubb Apologies, I didn't realise you had used another aligner. Yes we would recommend using bwa and VarDict should work with both paired and singleton alignments. That said, you'll have much better success in amplicon mode if you have paired reads.

We've also tried MiniMap2 and as it produces bwa-like alignments it should work OK too.

**Comment by bwubb** [comment]
@mjafin No need to apologize because I did not mention it; instead thinking it was the single-end reads and focusing on that. While this is starting to deviate from the original topic, I was hoping you might be able to explain or point me to what criteria VarDict might look for in a read to ignore? Perhaps there is something I can change about my bams.

**Comment by bwubb** [comment]
My apologies that I left this open for so long. The issue was with bbmap.

bbmap is one of the aligners that uses the full header present in your fasta file when creating the index and passes it along to alignment file. If there are spaces in the header name they are written to alignment. Some downstream programs have a problem with this.

You can use the option "trd=t" to truncate the fasta header names after the first space in the name.

Now vardict works as intended, even on single end data. Hopefully someone else will find this mistake useful.
